- pkg/apis/datadoghq/v1alpha1/const.go
- pkg/controller/datadogagentdeployment/agent_test.go
- pkg/controller/datadogagentdeployment/const.go
- pkg/controller/datadogagentdeployment/utils.go
- Adds the `KUBERNETES=yes` environment variable to the Agent's container.
- Adds the `DD_KUBERNETES_KUBELET_HOST` env var to retrieve kubelet host using the downward API 
The `KUBERNETES` env var is required to configure the config `kubelet` check via the [entrypoint script](https://github.com/DataDog/datadog-agent/blob/master/Dockerfiles/agent/entrypoint/50-kubernetes.sh#L3).
> Activate kubelet check

- Makefile
- deploy/operator.yaml
- go.mod
- go.sum
- hack/verify-license.sh
- pkg/controller/datadogagentdeployment/agent_rbac.go
- pkg/controller/datadogagentdeployment/clusteragent.go
- pkg/controller/datadogagentdeployment/clusteragent_metricsserver.go
- pkg/controller/datadogagentdeployment/clusterchecksrunner.go
- pkg/controller/datadogagentdeployment/clusterchecksrunner_rbac.go
- pkg/controller/datadogagentdeployment/common_rbac.go
- pkg/controller/datadogagentdeployment/datadogagentdeployment_controller.go
- pkg/controller/datadogagentdeployment/datadogagentdeployment_controller_test.go
- test/e2e/datadogagentdeployment_test.go
- test/e2e/utils/new.go
- test/e2e/utils/wait.go
* fix `go.mod`
* Only update status if needed in the main reconcile() fonction
* Refactor reconcile() sub fonction call
* An Operator logs streaming in e2e test
* Improve `make validate` output
> [operator] fix multi status update in reconcile()

- chart/datadog-operator/templates/pod_disruption_budget.yaml
Add Pod Disruption Budget to the Datadog operator.
Ensure that there is always a `datadog-operator` instance up and running.
Even when the cluster autoscaler is scaling down the cluster for example.
> Add Pod Disruption Budget to the Datadog operator

- pkg/apis/datadoghq/v1alpha1/test/new.go
- pkg/controller/datadogagentdeployment/clusteragent.go
- pkg/controller/datadogagentdeployment/datadogagentdeployment_controller_test.go
- Do not create Agent DaemonSet / CLC Runner deployments until the Cluster Agent has at least 1 available replica
Better component synchronization: Make sure the Cluster Agent is ready before creating Agent DaemonSet / CLC Runner deployments
> Make component synchronization more robust

- pkg/controller/datadogagentdeployment/clusteragent.go
- pkg/controller/datadogagentdeployment/clusterchecksrunner.go
Update status after deleting the cluster agent or the cluster check runners
Keep the `DatadogAgentDeployment` status up-to-date
> [Fix] Update CR status after disabling cluster agent and clc runners

- Makefile
- chart/datadog-operator/templates/role.yaml
- deploy/role.yaml
- docs/how-to-contribute.md
- docs/quick-start.md
- examples/datadog-agent-with-clusteragent.yaml
- examples/datadog-agent-with-dca-clusterchecksrunner.yaml
- examples/datadog-agent-with-tolerations.yaml
- examples/datadog-agent.yaml
- go.sum
- pkg/controller/datadogagentdeployment/clusteragent.go
- pkg/controller/datadogagentdeployment/clusterchecksrunner.go
- pkg/controller/datadogagentdeployment/datadogagentdeployment_controller.go
- pkg/controller/datadogagentdeployment/datadogagentdeployment_controller_test.go
- pkg/controller/datadogagentdeployment/poddisruptionbudget.go
- pkg/controller/datadogagentdeployment/utils.go
Add management of PDB for Cluster Agent and Cluster Checks Runner.
Currently the PDB configuration is static and automatically created if corresponding component should exist. We set MinAvailable to 1 for both currently, which should be enough for our use cases (though for cluster checks runner we might want to implement something smarter eventually)
> Add PodDisruptionBudget management

- pkg/apis/datadoghq/v1alpha1/datadogagentdeployment_types.go
- pkg/controller/datadogagentdeployment/agent.go
- pkg/controller/datadogagentdeployment/clusteragent.go
- pkg/controller/datadogagentdeployment/clusterchecksrunner.go
- pkg/controller/datadogagentdeployment/datadogagentdeployment_controller.go
- pkg/controller/datadogagentdeployment/utils.go
Actually compute status and displays it in `kubectl get dad` output.
Currently it's implemented for the Deployments and (Extended)DaemonSets we have.
```
NAME            ACTIVE   AGENT                 CLUSTER-AGENT     CLUSTER-CHECKS-RUNNER   AGE
datadog-agent   True     Progressing (1/0/1)   Running (2/2/2)   Progressing (2/0/2)     24h
```
I've changed existing statuses and put all supported objects to have the same status:
- Progressing (is deployed, but no pod ready)
- Running (is deployed, with at least 1 pod ready)
- Updating (rolling update on-going, i.e. number of requested != number of uptodate PODs)
- Failed (creation of the target resource failed or Kubernetes reported a failed state - only for Deployments)
The numbers are Requested / Ready / Uptodate.
Flagging the PR as WIP as …
> Add proper status in `get dad` display

- deploy/crds/datadoghq.com_datadogagentdeployments_crd.yaml
- docs/quick-start.md
- pkg/apis/datadoghq/v1alpha1/datadogagentdeployment_types.go
- pkg/apis/datadoghq/v1alpha1/test/new.go
- pkg/apis/datadoghq/v1alpha1/zz_generated.openapi.go
- pkg/controller/datadogagentdeployment/agent_test.go
- pkg/controller/datadogagentdeployment/clusteragent.go
- pkg/controller/datadogagentdeployment/datadogagentdeployment_controller_test.go
- pkg/controller/datadogagentdeployment/utils.go
Adds configuration to mount user defined volumes in the node and cluster agent containers.
Certain use cases require configuration of user provided volumes in the node and cluster agent containers.
> Add support for additional volumes in node and cluster agent pod configs

- pkg/controller/datadogagentdeployment/utils.go
- test/e2e/datadogagentdeployment_test.go
Rename a couple of variables to avoid linting warnings in vscode (by default it uses `golint`)
Warning free bliss :)
```
$ golint pkg/controller/... test/...                                                                                                                                                                                         (kind-kind/default)
pkg/controller/datadogagentdeployment/utils.go:358:70: func parameter needApiKey should be needAPIKey
test/e2e/datadogagentdeployment_test.go:41:2: don't use underscores in Go names; var dd_api_key should be ddAPIKey
```
> Rename a couple of vars to avoid golint warnings

- deploy/crds/datadoghq.com_datadogagentdeployments_crd.yaml
- pkg/apis/datadoghq/v1alpha1/datadogagentdeployment_types.go
- pkg/apis/datadoghq/v1alpha1/test/new.go
- pkg/apis/datadoghq/v1alpha1/zz_generated.openapi.go
- pkg/controller/datadogagentdeployment/agent.go
- pkg/controller/datadogagentdeployment/agent_test.go
- pkg/controller/datadogagentdeployment/clusteragent.go
- pkg/controller/datadogagentdeployment/clusterchecksrunner.go
- pkg/controller/datadogagentdeployment/datadogagentdeployment_controller_test.go
- pkg/controller/datadogagentdeployment/utils.go
- Allow customizing `daemonsetName` for agent's DaemonSet or ExtendedDaemonSet.
- Allow customizing `deploymentName` for cluster agent's deployment.
These can be used to "migrate" from existing helm-created resources.
Providing a path to migrate from helm-provisioned Datadog agent deployments.
> Provide config settings for custom names for Agent daemonset and DCA deployment

- chart/datadog-operator/templates/datadoghq.com_datadogagentdeployments_crd.yaml
- chart/datadog-operator/templates/datadoghq.com_datadogagents_crd.yaml
When CRD was renamed (`DatadogAgentDeployment` => `DatadogAgent`) the symlink in the helm chart didn't get updated, this updates the chart with the correct symlink target.
> Correct symlink in helm chart broken due to CRD rename

- pkg/controller/datadogagent/datadogagent_controller.go
- pkg/controller/datadogagent/datadogagent_controller_test.go
- pkg/controller/datadogagent/secret.go
- pkg/controller/utils/condition/condition.go
- pkg/controller/utils/datadog/forwarders_manager.go
- pkg/controller/utils/datadog/metrics_forwarder.go
Avoid race condition update of the DatadogAgentStatus. 
before 2 differents goroutine may update the DatadogAgentStatus at the same time. that leads to concurrent update errors. 
> Reconcile() updates now MetricsForwarder.Status in DatadogAgentStatus

- pkg/apis/datadoghq/v1alpha1/const.go
- pkg/controller/datadogagent/agent.go
- pkg/controller/datadogagent/agent_test.go
- pkg/controller/datadogagent/utils.go
This is to handle the cases where the docker daemon is restarted.
In this case, the docker daemon will recreate its docker socket.
On k8s context, the containers will not be restarted.
And, if the agent container bind-mounted directly the socket, the container would still have access to the old socket instead of the one of the new docker daemon.
As a consequence, with a bind-mount of the socket directly, a docker restart disconnects the agent from docker forever; until the agent POD is destroyed and recreated.
On the other hand, if we bind-mount the directory containing the socket, when the daemon recreates a new socket following a restart, it will be visible from the agent container. The agent will be disconnected from the old socket, and it will reconnect on the new one.
> Mount the directory containing the docker socket instead of the socket itself

- deploy/crds/datadoghq.com_datadogagents_crd.yaml
- pkg/apis/datadoghq/v1alpha1/datadogagent_types.go
- pkg/apis/datadoghq/v1alpha1/zz_generated.deepcopy.go
- pkg/apis/datadoghq/v1alpha1/zz_generated.openapi.go
- pkg/controller/datadogagent/clusteragent.go
- pkg/controller/datadogagent/clusterchecksrunner.go
- pkg/controller/datadogagent/utils.go
Add missing fields in `DatadogAgent` CRD,  for `agent`, `cluster-agent`,  `clustercheckrunner` pods
* `AdditionnalAnnotations`
* `AdditionnalLabels`
* `PriorityClassName`
for the Agent configuration:
* `hostNetwork`
* `hostPID`
* `dnsConfig`
* `dnsPolicy`
for `system-probe`: add the possibility to overwrite the default `securityContext`
> [WIP] Add missing fields in DatadogAgent CRD

- deploy/crds/datadoghq.com_datadogagents_crd.yaml
- pkg/apis/datadoghq/v1alpha1/const.go
- pkg/apis/datadoghq/v1alpha1/datadogagent_types.go
- pkg/apis/datadoghq/v1alpha1/test/new.go
- pkg/apis/datadoghq/v1alpha1/zz_generated.deepcopy.go
- pkg/apis/datadoghq/v1alpha1/zz_generated.openapi.go
- pkg/controller/datadogagent/clusteragent.go
- pkg/controller/datadogagent/clusteragent_test.go
- pkg/controller/datadogagent/clusterchecksrunner.go
- pkg/controller/datadogagent/clusterchecksrunner_test.go
- pkg/controller/datadogagent/const.go
- configure env vars for the cluster agents
- configure env vars for the cluster checks runner
- configure volumes for the cluster checks runner
- configure the volume mounts for the cluster checks runner
- configure `DD_CLC_RUNNER_ENABLED` and `DD_CLC_RUNNER_HOST` by default
> Extend DCA and CLC Runners config

- README.md
Removes the disclaimer, only leaving the Alpha version as a warning on the state of this project.
> Removing usage disclaimer

- pkg/apis/datadoghq/v1alpha1/const.go
- pkg/controller/datadogagent/agent_test.go
- pkg/controller/datadogagent/utils.go
Explicitly set DOCKER_HOST
Following f3e7d709, the docker socket is at a non-standard location inside the agent container.
This change implements the same behavior as the one introduced in helm/charts#21300
> Explicitly set DOCKER_HOST

- chart/datadog-operator/templates/role.yaml
- deploy/operator.yaml
- deploy/role.yaml
- pkg/controller/datadogagent/agent.go
* Fix `ClusterRole` for extendeddaemonset support
* Add Probes in `/deploy/operator.yaml`  operator deployment
* Fix status update when ExtendedDaemonset is used
> fix DatadogAgent.Status when EDS activated

- cmd/kubectl-datadog/get/get.go
Small bug fix in the kubectl plugin:
the components status  in `kubectl datadog get` was using
`State` instead of `Status`
so the displayed status was: `Running` instead of `Running (3/3/3)`
for example.
> [Plugin] fix component status

- chart/datadog-operator/templates/deployment.yaml
- chart/datadog-operator/values.yaml
- cmd/manager/main.go
- deploy/operator.yaml
Change the probes port from `8080` to `9090`, also make it parametrisable.
the Operatorhub.io validation process inject a container that use also the port `8080`. in order to make the validation test working.
> change probes port, make it configurable

- deploy/crds/datadoghq.com_datadogagents_crd.yaml
- pkg/apis/datadoghq/v1alpha1/const.go
- pkg/apis/datadoghq/v1alpha1/datadogagent_types.go
- pkg/apis/datadoghq/v1alpha1/test/new.go
- pkg/apis/datadoghq/v1alpha1/zz_generated.openapi.go
- pkg/controller/datadogagent/datadogagent_controller_test.go
- pkg/controller/datadogagent/utils.go
Add `secCompProfileName` parameter in system-probe spec.
In order to ease the debuging of `system-probe` container, add the possibility to provides another seccomp profile.
> Add SecCompProfileName for system-probe

- .goreleaser.yml
- datadog.yaml
- Prepare the `goreleaser` manifest
- Adapt the `krew` manifest
> Prepare release tooling

- cmd/kubectl-datadog/agent/check/check.go
- Make sure `agent status --json` returns a valid json
`agent status --json` prints the logs if `DD_LOG_LEVEL` is set in the agent container => invalid json
> [Plugin] Add DD_LOG_LEVEL=off to get agent status

- deploy/crds/datadoghq.com_datadogagents_crd.yaml
- deploy/olm-catalog/datadog-operator/0.1.3/datadog-operator.v0.1.3.clusterserviceversion.yaml
- deploy/olm-catalog/datadog-operator/0.1.3/datadoghq.com_datadogagents_crd.yaml
- deploy/operator.yaml
- hack/generate-olm-bundle.sh
- pkg/apis/datadoghq/v1alpha1/datadogagent_types.go
- pkg/apis/datadoghq/v1alpha1/zz_generated.openapi.go
Add more information in the OLM file to improve the display in the Operatorhub.io
missing description and example in the page https://operatorhub.io/operator/datadog-operator
> Improve description in OML file

- deploy/crds/datadoghq.com_datadogagents_crd.yaml
- pkg/apis/datadoghq/v1alpha1/const.go
- pkg/apis/datadoghq/v1alpha1/datadogagent_default.go
- pkg/apis/datadoghq/v1alpha1/datadogagent_types.go
- pkg/apis/datadoghq/v1alpha1/test/new.go
- pkg/apis/datadoghq/v1alpha1/zz_generated.deepcopy.go
- pkg/apis/datadoghq/v1alpha1/zz_generated.openapi.go
- pkg/controller/datadogagent/agent_test.go
- pkg/controller/datadogagent/clusteragent.go
- pkg/controller/datadogagent/clusterchecksrunner.go
- pkg/controller/datadogagent/clusterchecksrunner_test.go
- pkg/controller/datadogagent/datadogagent_controller_test.go
- pkg/controller/datadogagent/utils.go
- test/e2e/datadogagent_test.go
- Get rid of `clusterChecksRunnerEnabled`
- Enable endpoint checks - be aligned with the helm chart
> Fix CLC config

- docs/getting_started.md
Fix the .zip version to fit with the last datadog-operator docker image release.
sync the chart version and the docker image in the `getting_started.md` documentation
> fix zip file version in getting_started.md

- pkg/controller/datadogagent/clusteragent.go
- pkg/controller/datadogagent/utils.go
Fix panic in case of missing `ClusterChecksEnabled` property in the CR.
Panics are uncool.
> Fix panic in case of missing `ClusterChecksEnabled` property in the CR

- deploy/crds/datadoghq.com_datadogagents_crd.yaml
- pkg/apis/datadoghq/v1alpha1/datadogagent_types.go
- pkg/apis/datadoghq/v1alpha1/zz_generated.openapi.go
- pkg/controller/datadogagent/systemprobe.go
- pkg/controller/datadogagent/utils.go
Add `SecCompCustomProfileConfigMap` for `system-probe`.
Implement the following behaviours regarding the `seccomp` profile for `system-probe`:
(“ConfigMap” is a shortcut for “the ConfigMap containing the seccomp profile for `system-probe`.
“init container” is a shortcut for “the init container that copies the seccomp profile from the ConfigMap to the host.)
* Let the operator use its own `seccomp` profile:
* create a ConfigMap
* use an init container to copy its content to the hosts.
* ```
systemProbe:
enabled: true
* Make `system-probe` use the default `seccomp` profile:
* do **not** create the ConfigMap
* do **not** create the init container
* ```
systemProbe:
enabled: true
secCompProfileName: runtime/default
* Make `system-probe` use a `seccomp` profile that is already available on the …
> Add SecCompCustomProfileConfigMap for system-probe

- docs/cluster_agent_setup.md
- docs/custom_check.md
- docs/getting_started.md
- examples/datadog-agent-all.yaml
- examples/datadog-agent-with-clusteragent.yaml
- examples/datadog-agent-with-dca-clusterchecksrunner.yaml
- examples/datadog-agent-with-tolerations.yaml
- examples/datadog-agent.yaml
- pkg/controller/datadogagent/agent.go
- pkg/controller/datadogagent/agent_test.go
- pkg/controller/datadogagent/clusteragent.go
- pkg/controller/datadogagent/clusteragent_test.go
- pkg/controller/datadogagent/clusterchecksrunner_test.go
- pkg/controller/datadogagent/datadogagent_controller.go
- pkg/controller/datadogagent/datadogagent_controller_test.go
- test/e2e/datadogagent_test.go
- Recommend naming the CR `datadog`
- The DS or EDS created by the operator are named `<cr name>-agent` 
Avoid generating unnecessary long resource names
datadog-agent-cluster-agent -> datadog-cluster-agent
datadog-agent-cluster-checks-runner -> datadog-cluster-checks-runner
> Align resource names

- pkg/apis/datadoghq/v1alpha1/test/new.go
- pkg/controller/datadogagent/agent.go
- pkg/controller/datadogagent/agent_test.go
- pkg/controller/datadogagent/clusteragent.go
- pkg/controller/datadogagent/clusteragent_test.go
- pkg/controller/datadogagent/clusterchecksrunner.go
- pkg/controller/datadogagent/clusterchecksrunner_test.go
- pkg/controller/datadogagent/datadogagent_controller_test.go
- pkg/controller/datadogagent/secret.go
- pkg/controller/datadogagent/utils.go
- pkg/controller/utils/shared_utils.go
Ensure the API and APP key are read from the secret
```
$ kubectl --context gke_datadog-sandbox_europe-west4-c_lenaic --namespace datadog-agent-operator describe pod/datadog-agent-cluster-agent-7bcd56d9c9-lztvp pod/datadog-agent-cluster-checks-runner-649ff5b589-q6v47 pod/datadog-agent-agent-8xdbx | grep -E "^Name:|Environment:|DD_CLUSTER_AGENT_AUTH_TOKEN:|DD_API_KEY:|DD_APP_KEY:" | sed "s|$DD_API_KEY|DD_API_KEY_IN_CLEAR_CONCEALED_HERE|; s|$DD_APP_KEY|DD_APP_KEY_IN_CLEAR_CONCEALED_HERE|"
Name:         datadog-agent-cluster-agent-7bcd56d9c9-lztvp
Environment:
DD_CLUSTER_AGENT_AUTH_TOKEN:               <set to the key 'token' in secret 'datadog-agent-cluster-agent'>  Optional: false
DD_API_KEY:                                DD_API_KEY_IN_CLEAR_CONCEALED_HERE
DD_APP_KEY: …
```
> Ensure the API and APP key are read from the secret

- docs/getting_started.md
- docs/kubectl-plugin.md
Add documentation about the kubeclt plugin
the kubectl plugin is now part of the release process.
> Add kubectl datadog plugin doc

- cmd/kubectl-datadog/flare/flare.go
- pkg/apis/datadoghq/v1alpha1/datadogagent_default.go
- pkg/controller/datadogagent/agent_rbac.go
- pkg/controller/datadogagent/agent_test.go
- pkg/controller/datadogagent/clusteragent.go
- pkg/controller/datadogagent/clusteragent_test.go
- pkg/controller/datadogagent/clusterchecksrunner.go
- pkg/controller/datadogagent/clusterchecksrunner_test.go
- pkg/controller/datadogagent/utils.go
While trying Datadog Operator for my use case, I started noticing that no matter if I had set `Site` to `EU`, my agents would try to send data to `https://app.datadoghq.com`. 
After inspecting the generated manifests for both the datadog agent and the datadog cluster agent, I noticed that even though `DD_SITE` was set to `EU`, a `DD_DD_URL` env var was populated and set to `https://app.datadoghq.com`, overriding `DD_SITE`.
In the documentation, it is said that `DD_DD_URL` is optional, and should only be set when one wants to override the endpoint that `DD_SITE` would make Datadog Agent use (for example if you use a proxy, or need a mock endpoint, etc...)
After looking through the codebase, I noticed that `DD_DD_URL` was indeed set by default. This PR is addressing this issue
Solving my …
> Honor DD_SITE by not adding DD_DD_URL env var by default

- pkg/apis/datadoghq/v1alpha1/test/new.go
- pkg/controller/utils/datadog/metrics_forwarder.go
- pkg/controller/utils/datadog/metrics_forwarder_test.go
This PR:
*  Adds a field to the `metricsForwarder` struct: `baseURL`
* Adds a `getBaseURL` method that returns the appropriate base URL based on the `ddUrl` or `site` fields in the definition of the agent
* Sets the base URL after the client has been initialized
* Adds the base URL used when error-ing out on invalid credentials.
After submitting #90 and testing it out, I realized that the operator was also trying to push metrics, grabbing the credentials from the agent. Unfortunately the metrics forwarder wasn't using the DD_SITE / DD_DD_URL setting and would use the default of the client SDK, which is `https://api.datadoghq.com`
I've tested this successfully in a 1.16 EKS cluster, using `site: datadoghq.eu`
PS: The validation build failure doesn't seem to be related to my changes.
> Use DdSite or DdUrl for MetricsForwarder API client

- pkg/controller/datadogagent/agent.go
This PR fixes https://github.com/DataDog/datadog-operator/issues/93
In `updateDaemonSet`, we create a new daemonset before checking if we need to make an update to the daemonset. Unfortunately, instead of passing the existing DS to the `updateDaemonSetStatus` method, we were passing the new one, which obviously had no containers running, resulting in the Agent having its status stuck in `Progressing (0/0/0)`.
Once we pass the existing DS, the status updates as expected.
Fixing my own issue
> Pass existing DS to updateDaemonSetStatus in updateDaemonSet when no change is required

- README.md
- chart/datadog-operator/templates/deployment.yaml
- chart/datadog-operator/values.yaml
- docs/secret_management.md
* Add documentation regarding "secret management" with the Operator 
* Add new parameter in the "Datadog-Operator" chart to allow the specification of the "secret backend command".
Helps user to deploy the agent with the "secret backend" activated on the operator and on the Agents deployed with the operator.
> [Doc] secret backend documentation

- deploy/crds/datadoghq.com_datadogmetrics_crd.yaml
- pkg/apis/datadoghq/v1alpha1/datadogmetric_types.go
- pkg/apis/datadoghq/v1alpha1/zz_generated.openapi.go
The CRD generator doesn't support `float64` as a type of a CRD field.
The suggested workaround is to used instead `resource.Quantity` but we choose to use `string`.
Related issue: https://github.com/kubernetes-sigs/controller-tools/issues/245
Fix the Master branch, that is broken due to a merge issue.
> Fix DatadogMetric generation with operator-sdk 0.17

- pkg/apis/datadoghq/v1alpha1/const.go
- pkg/controller/datadogagent/clusteragent.go
- pkg/controller/datadogagent/clusteragent_test.go
This PR creates a `DATADOG_HOST` environment variable that is defined when `metricsProviderEnabled = true`, as the client used to fetch the metrics from Datadog doesn't recognize either `DD_SITE` or `DD_DD_URL`.
It:
* Create a const `DatadogHost` that corresponds to the `DATADOG_HOST` environment variable name
* Adds a `getDatadogHost` method to `pkg/controller/datadogagent/clusteragent.go`
* Creates the `DATADOG_HOST` environment variable when `metricsProviderEnabled` is true
Addressing issue #103
> Set DATADOG_HOST according to DD_SITE or DD_DD_URL when MetricsProvider is enabled. Resolves #103

- .github/workflows/main.yml
- pkg/apis/datadoghq/v1alpha1/const.go
- pkg/apis/datadoghq/v1alpha1/datadogagent_types.go
- pkg/apis/datadoghq/v1alpha1/test/new.go
- pkg/controller/datadogagent/agent_test.go
- pkg/controller/datadogagent/utils.go
This PR adds the `hostPort` parameter to the Agent config, which allows exposing the Dogstatsd port to the cluster, and therefore receiving custom metrics from our applications.
I couldn't expose port 8125 to my applications without modifying manually the DaemonSet definition.
1. I saw that the `newDaemonSetfromInstance` method is not tested in `agent_test.go`. Therefore I added the test case to the `newExtendedDaemonSetfromInstance` method tests. I' m not sure whether this is an oversight or a design decision in an effort to reduce the amount of duplicated code, but I'm happy to write tests for `newDaemonSetFromInstance` if needed.
2. I'm also not sure if the lack of `hostPort` for Agent was by design. I saw that the APM Agent already had that setting. Please let me know if this isn't …
> Add hostPort for Agent

- README.md
- docs/getting_started.md
Fixes a minor typo and adds a link to the Helm chart for deploying the Datadog agent with the k8s operator
The motivation is to contribute to the documentation
N/A
> Fix minor typo and add Helm chart link

- deploy/crds/datadoghq.com_datadogagents_crd.yaml
- pkg/apis/datadoghq/v1alpha1/const.go
- pkg/apis/datadoghq/v1alpha1/datadogagent_default.go
- pkg/apis/datadoghq/v1alpha1/zz_generated.deepcopy.go
- pkg/apis/datadoghq/v1alpha1/zz_generated.openapi.go
- pkg/controller/datadogagent/clusteragent.go
- pkg/controller/datadogagent/datadogagent_controller_test.go
- pkg/controller/datadogagent/service.go
- Use 8443 as default port for the external metrics provider
443 doesn't work OOTB on openshift
> Use 8443 as default port for the external metrics provider

- pkg/controller/datadogagent/systemprobe.go
Do not panic when node agent isn't enabled
Panics are bad
> Fix nil pointer when DS Agent disabled

- pkg/apis/datadoghq/v1alpha1/datadogagent_default.go
Signed-off-by: cedric lamoriniere <cedric.lamoriniere@datadoghq.com>
fix the defaulting of the `ContainerCollectUsingFiles` logs parameter. 
If the `ContainerCollectUsingFiles` parameter is the only one not default, this parameter will not be default in the `LogSpec` struct. Which end up with a controller crash when it try to access this value.
> Fix logs configuration defaulting

- deploy/crds/datadoghq.com_datadogagents_crd.yaml
- pkg/apis/datadoghq/v1alpha1/const.go
- pkg/apis/datadoghq/v1alpha1/datadogagent_default.go
- pkg/apis/datadoghq/v1alpha1/datadogagent_types.go
- pkg/apis/datadoghq/v1alpha1/zz_generated.deepcopy.go
- pkg/apis/datadoghq/v1alpha1/zz_generated.openapi.go
- pkg/controller/datadogagent/agent_test.go
- pkg/controller/datadogagent/utils.go
This is to match a change to the datadog helm chart [1] adding the same
option. This option sets the maximum number of logs files that the
Datadog Agent will tail up to.
[1] https://github.com/helm/charts/pull/22347
> Add .Spec.Agent.Log.OpenFilesLimit

- docs/kubectl-plugin.md
- hack/release/README.md
Update the datadog krew plugin installation instructions.
We’ve opened a PR to add the `datadog` plugin into the `krew` index: kubernetes-sigs/krew-index#727
> Update the datadog krew plugin installation instructions

- docs/custom_check.md
- pkg/controller/datadogagent/clusterchecksrunner.go
- pkg/controller/datadogagent/clusterchecksrunner_test.go
- pkg/controller/datadogagent/utils.go
It's already possible to define`.Spec.Agent.Config.Checksd`, but this option is not propagated to
the Clusterchecks Runner. As a runner is basically an agent, we're just
reusing the same configuration.
This applies the same changes as this proposed change to
stable/datadog's Helm chart: https://github.com/helm/charts/pull/23139
> Propagate custom check definitions to CLC Runners

- .github/workflows/release.yaml
- chart/datadog-agent-with-operator/Chart.yaml
- chart/datadog-operator/Chart.yaml
- chart/datadog-operator/values.yaml
- docs/getting_started.md
- hack/release/generate-chart-tarball.sh
This helps with several things: it's no longer necessary to download an
archive of the entire repo, and it's impossible to have a mismatch
between the version of the chart being used, the release version, and
the links the documentation.
The documented `curl` oneliner in this PR doesn't work right now, as the tarball is not in the latest release. It can be added manually, so I'll upload both charts there once the PR is approved.
> Generate Helm chart as a release artifact

- deploy/crds/datadoghq.com_datadogmetrics_crd.yaml
- pkg/apis/datadoghq/v1alpha1/datadogmetric_types.go
Make `autoscalerReferences` optional as it's not filled by DCA ATM (will require DCA 1.9+)
> Fix DatadogMetric CRD: references should be optional (will be filled by DCA 1.9+)

- hack/release/generate-chart-tarball.sh
`datadog-agent-with-operator` has `datadog-operator` as a subchart, and
the previous version of the script would not perform any replacements on
subcharts, resulting in literal PLACEHOLDER_VERSION` being left behind.
> Replace PLACEHOLDER_VERSION in subcharts as well

- .gitlab-ci.yml
Allow in gitlab-ci to push the docker image latest tag, when it is a job triggered by a "tag"
> Activate push to latest when tag

- deploy/clusterrole.yaml
- deploy/clusterrole_binding.yaml
- deploy/olm-catalog/datadog-operator/0.2.3/datadog-operator.v0.2.3.clusterserviceversion.yaml
- deploy/olm-catalog/datadog-operator/0.2.3/datadoghq.com_datadogagents_crd.yaml
- deploy/olm-catalog/datadog-operator/datadog-operator.package.yaml
- deploy/service_account.yaml
> CSV version 0.2.3 allowing agent (not operator) to use SCCs on OpenShift

- pkg/controller/datadogagent/systemprobe.go
The new ebpf library we are using needs these additional syscalls. See https://github.com/DataDog/helm-charts/pull/18 for corresponding update to the Helm chart.
Without these syscalls, system-probe will `CrashLoopBackoff`.
> Add syscalls needed for 7.22.0 version of system-probe

- hack/generate-olm-bundle.sh
the Redhat validation script in the Redhat partner portable, only support bundle with one OLM version.
Redhat [docs](https://redhat-connect.gitbook.io/certified-operator-guide/ocp-deployment/operator-metadata/bundle-directory) related to the creation of the bundle
N/A
> Fix generate-olm-bundle.sh to only package one version

- hack/release/cluster-service-version-patch.yaml
Add a `DatadogMetrics` in the OLM ClusterServiceVersion patch.
Since we package the `DatadogMetrics` CRD in the OLM configuration. we also need to have an example to be validated by the Operatorhub.io CI process.
Generate a new Release locally with `make pre-release` command, then go to https://operatorhub.io/preview and copy/paste the content of the generated `csv` file. The DatadogMetrics example should be present in the description of the Operator.
> Add DatadogMetrics example in OLM

- deploy/crds/datadoghq.com_datadogagents_crd.yaml
- deploy/crds/v1/datadoghq.com_datadogagents_crd.yaml
- deploy/crds/v1beta1/datadoghq.com_datadogagents_crd.yaml
- pkg/apis/datadoghq/v1alpha1/datadogagent_types.go
- pkg/apis/datadoghq/v1alpha1/test/new.go
- pkg/apis/datadoghq/v1alpha1/utils.go
- pkg/apis/datadoghq/v1alpha1/zz_generated.deepcopy.go
- pkg/controller/datadogagent/datadogagent_controller_test.go
- pkg/controller/datadogagent/utils.go
Actually use `securityContext` attribute as PodSecurityContext
Use the `SecurityContext` attribute and verify that it's effectively used as PodSecurityContext in DaemonSet
> Actually use `securityContext` attribute as PodSecurityContext

- pkg/controller/datadogagent/agent_test.go
- pkg/controller/datadogagent/utils.go
If only the runtime security agent is enabled, the process won't be able
to start because it can't find the `datadog.yaml` that's available in
the `config` volume, as it was only mounted when the compliance agent
was enabled. Now, it's mounted if either of them is enabled.
This can be tested by enabling the security agent in three different permutations (only runtime, only compliance, and both), and checking that the process starts successfully.
> Always mount `config` volume when security agent is enabled

- docs/installation.md
In newer versions of the operator, untaring the release gives you directly the Helm chart. Fixing that in the installation instructions
> Fix helm chart path

- deploy/crds/datadoghq.com_datadogagents_crd.yaml
- deploy/crds/v1/datadoghq.com_datadogagents_crd.yaml
- deploy/crds/v1beta1/datadoghq.com_datadogagents_crd.yaml
- pkg/apis/datadoghq/v1alpha1/datadogagent_types.go
- pkg/apis/datadoghq/v1alpha1/test/new.go
- pkg/apis/datadoghq/v1alpha1/zz_generated.deepcopy.go
Replace `security.compliance.checkInterval` CRD field type from `time.Duration`
to `metav1.Duration`. 
Previously the checkInterval type in the `AgentDeployment.spec`
was `time.Duration`. So it wasn't possible to use a value like `20min`.
Now, with `metav1.Duration` type, it is possible and more align with the other
Duration fields in the CRD.
N/A
Deploy a DatadogAgent with the compliance feature activated and the `checkInterval` 
value set to `20s` for example. The Operator should be able to create the Daemonset without
`checkInterval` decoding error.
> Fix compliance checkInterval duration type

- .github/workflows/pr-linter.yml
See https://github.com/jesusvasquez333/verify-pr-label-action/issues/9#issuecomment-706639627
> Update `verify-pr-label-action` GH action to allow contributions from fork

- main.go
- pkg/config/config.go
Re-add handling of WATCH_NAMESPACE following migration to Operator SDK 1.0.
Setting WATCH_NAMESPACE should limit the watches set by Datadog Operator. Deploy Datadog Operator with `WATCH_NAMESPACE=<ns1>` and create two DatadogAgent objects in `ns1` and `ns2`. Datadog Operator should ignore `ns2`.
> Re-add handling of WATCH_NAMESPACE following migration to Operator SDK 1.0

- Makefile
- config/manager/kustomization.yaml
- config/rbac/role.yaml
- controllers/datadogagent/agent_test.go
- controllers/datadogagent/clusteragent.go
- controllers/datadogagent/utils.go
- controllers/datadogagent_controller.go
To auto-activate OOM and TCP checks, the core agent needs to have access to `system-probe` socket and configuration file.
RBAC declaration for NetworkPolicies was missing (Kustomize)
Fixed DCA RBAC to collect events following introduction of `Spec.ClusterAgent.Config.CollectEvents`
Activate system-probe OOM or TCP checks and verify they run in core agent.
> Fix scheduling of system-probe related checks in the core agent and missing permissions for network policies

- controllers/datadogagent/clusteragent.go
- controllers/datadogagent/utils.go
Since move from string to `metav1.Duration`, CheckInterval is not working anymore. It's because `String()` of a `metav1.Duration` is not what the Agent/ClusterAgent expects.
Activate compliance, set CheckInterval, checks the outputted check interval in the logs, should be the same value.
> Fix compliance CheckInterval set in DCA/SecAgent

- api/v1alpha1/const.go
- controllers/datadogagent/agent_test.go
- controllers/datadogagent/systemprobe.go
Logs and system-probe are both trying to use `/opt/datadog-agent/run` as an empty dir. In core agent, it results in a conflict in `volumeMounts`.
Changing system-probe to `/var/run/sysprobe` (same as in the Helm chart)
Deploy operator with a DatadogAgent with both logs and system-probe activated. Agent DaemonSet should deploy successfully.
> Fix system-probe and logs volumeMount conflict

- LICENSE-3rdparty.csv
- api/v1alpha1/groupversion_info.go
- api/v1alpha1/test/new.go
- cmd/kubectl-datadog/agent/upgrade/upgrade_test.go
- cmd/kubectl-datadog/clusteragent/upgrade/upgrade_test.go
- controllers/datadogagent/clusteragent.go
- controllers/datadogagent/clusteragent_test.go
- controllers/datadogagent/controller_test.go
Currently generating new CRD is broken.
No impact at runtime.
> Fix naming of GroupVersion to be in line with OperatorSDK v1

- controllers/datadogagent/clusterchecksrunner.go
- controllers/datadogagent/clusterchecksrunner_test.go
- controllers/datadogagent/utils.go
- Missing mount of system-probe config file causes process-agent inability to find sysprobe.sock
- CLC is currently using S6 while init containers already runs files in `cont-init.d`, removing s6 to align with Helm chart.
Deploy operator with system-probe and process-agent activated, process-agent should be able to find sysprobe.sock.
CLC must sill work properly.
> Fix missing mount of system-probe config in process agent and remove s6 from CLC (aligned on Helm chart)

- api/v1alpha1/test/new.go
- controllers/datadogagent/agent.go
- controllers/datadogagent/agent_test.go
- controllers/datadogagent/clusteragent.go
- controllers/datadogagent/clusterchecksrunner.go
- controllers/datadogagent/clusterchecksrunner_test.go
- controllers/datadogagent/systemprobe.go
- controllers/datadogagent/utils.go
Add missing `custom-config` volumeMount in `process-agent` and `trace-agent`. 
Fix `process-agent` and `trace-agent` configuration when the user provide a `customConfig`.
N/A
Create a new DatadogAgent deployment. In the agent.spec add a `customConfig` configMap. Check
If this configMap is properly mounted in the `process-agent` and the `trace-agent`.
> Fix process-agent and trace-agent custom-config configuration

- bundle/manifests/datadog-operator.clusterserviceversion.yaml
- bundle/manifests/datadoghq.com_datadogmetrics.yaml
- config/manifests/bases/datadog-operator.clusterserviceversion.yaml
- config/rbac/role.yaml
- controllers/datadogagent_controller.go
Add OpenShift use restricted SCC RBAC in controller annotations
Restricted SCC is usually default and having permissions to use is not always necessary, so can only be tested in specific environments (e.g. OpenShift dedicated)
> Fix missing OpenShift RBAC to use SCC

- api/v1alpha1/const.go
- api/v1alpha1/test/new.go
- controllers/datadogagent/agent.go
- controllers/datadogagent/agent_test.go
- controllers/datadogagent/clusteragent.go
- controllers/datadogagent/clusterchecksrunner.go
- controllers/datadogagent/common_configmap.go
- controllers/datadogagent/controller_test.go
- controllers/datadogagent/service.go
- pkg/controller/utils/comparison/comparison.go
Fix annotation hash generation used to detect a change in the `Daemonset|ExtendedDaemonset` spec.
The operator doesn't detect properly new change in the `Daemonset|ExtendedDaemonset`
Create and deploy the agent with the operator. Update a small option in the DatadogAgent manifest. the Daemonset should be updated.
> Fix Daemonset hash annotation generation

- controllers/datadogagent/agent_test.go
- controllers/datadogagent/clusteragent.go
- controllers/datadogagent/clusteragent_test.go
- controllers/datadogagent/clusterchecksrunner.go
- controllers/datadogagent/clusterchecksrunner_test.go
- controllers/datadogagent/utils.go
add `DD_SITE` envvar only if the value is provide in the `DatadogAgent.spec`
configuration.
Previously the `DD_SITE` env variables was always added even if the
value wasn't provided.
N/A
* Create a DatadogAgent without configuring the `spec.Site` setting, and verify
that the `DD_SITE` envvar is not added to the containers.
* Update the `DatadogAgent` to configure the `spec.Site`, then verify the presence
of the envvar in the updated pods.
> Fix DD_SITE env variable integration

- Dockerfile
- cmd/helpers/main.go
- cmd/helpers/secrets/secrets.go
- docs/secret_management.md
- main.go
- pkg/secrets/secrets.go
- pkg/secrets/types.go
- scripts/readsecret.sh
- Provide a secret helper to read k8s secrets via secret backend
- fixes https://github.com/DataDog/datadog-operator/issues/148
The operator helm chart will be updated to allow configuring `secretBackendArgs`
Mount the secret + Install the Datadog Operator with `secretBackendCommand=/readsecret.sh` and `secretBackendArgs=/etc/secret-volume` if your secrets are mounted in `/etc/secret-volume`. The datadog operator should be able to decrypt the secrets
> [SB] Add secrets helper

- controllers/datadogagent/clusteragent.go
- controllers/datadogagent/secret.go
Fix the following issues with Secret management:
* When a secret was provided for the API key but the APP key was provided in clear, the operator wrongly tried to create a secret for the APP key with the same name as the user-provided one for the API key.
* When a secret was provided for the API key and for the APP key, but the DCA token was not provided, the DCA pod manifest were referencing a secret for the token that was not created by the operator. The DCA pod were staying in `CreateContainerConfigError` state forever with a event saying `Error: secret "datadog" not found`.
Make things work!
Fixes #96
Fixes #191
Try to create a `datadogagent` CR with the following `credentials` part:
```
spec:
credentials:
appKey: PUTYOUROWNHERE
apiSecret:
keyName: api_key
secretName: …
```
> Fix issues with Secret management

- api/v1alpha1/datadogagent_default.go
- api/v1alpha1/datadogagent_default_test.go
Fix `spec.agent.config.dogstatsd` defaulting.
Previously if the `spec.agent.config.dogstatsd` is nil, the defaulting
was working properly, but if it was half defaulted, like:
```yaml
spec:
agent:
config:
dogstatsd:
dogstatsdOriginDetection: true
```
the function `IsDefaulted` was properly detecting that `useDogStatsDSocketVolume` was missing,
but the `Default()` wasn't updating properly the configuration.
Fix an issue where the Operator was in an infinit reconcile loop retry, because `IsDefault()` and `Default()`
functions weren't aligned.
Create a `DatadogAgent` with a `dogstatsd` confi not fully defaulted, like:
```
```yaml
spec:
agent:
config:
dogstatsd:
dogstatsdOriginDetection: true
```
after a defaulting tentative the configuration should …
```
> Fix Dogstatsd config defaulting

- api/v1alpha1/const.go
- controllers/datadogagent/clusteragent.go
- controllers/datadogagent/clusteragent_test.go
We used to use DATADOG_HOST for setting the external metrics endpoint,
since the Cluster Agent did not have specific support for setting the
external metrics endpoint directly. This has since been added:
https://github.com/DataDog/datadog-agent/pull/6952 -- so we use that and
remove all the decision making and fallbacks to the DCA itself.
Edit a `DatadogAgent` to add the key below, and check the DCA deployment to see the `DD_EXTERNAL_METRICS_PROVIDER_ENDPOINT` applied for the container with the appropriate value.
````
metadata:
name: datadog
spec:
clusterAgent:
config:
enabled: true
endpoint: "https://example.com"
```
> Use DD_EXTERNAL_METRICS_PROVIDER_ENDPOINT

- config/manager/manager.yaml
Increase to 250Mi the operator default resources
with only 100Mi the operator can be in crashloopbackoff when it is deployed in a large cluster.
Generate operator bundle and check that the `ClusterServiceVersion` resources contains the new settings
> Increase to 250Mi the operator default resources

- docs/getting_started.md
Fixes links to Helm chart in the Getting started documentation.
The links to Helm charts were broken.
> Update getting started guide links to helm charts

- controllers/datadogagent/clusteragent.go
- controllers/datadogagent/clusterchecksrunner_rbac.go
Fix the `ServiceAccountName` override feature for the `cluster-agent` and the `cluster-check-runner` deployment.
The ServiceAccount created doesn't used the `ServiceAccountName` provided by the user for the
`cluster-agent` and the `cluster-check-runner` deployment.
Create a new `DatadogAgent` with the `ServiceAccountName` override. Check if the service account created use the
proper name.
> Fix ServiceAccountName override

- controllers/datadogagent/agent_rbac.go
- controllers/datadogagent/clusteragent.go
- controllers/datadogagent/clusterchecksrunner_rbac.go
- controllers/suite_test.go
* Fix ClusterRoleBinding update when the serviceAccountName as changed.
Users can change the ServiceAccountName used by the agent, cluster-agent or cluster-check-runner if they want.
But until not the `ClusterRoleBinding` for the cluster-agent and the cluster-check-runner wasn't updated according to the new ServiceAccountName.
1. Create a Simple DatadogAgent cr. wait that the agent, cluster-agent and cluster-check-runner are ready. 
2. Update the DatadogAgent by specifying new ServiceAccountName. 
3. check if the RoleBinding and ClusterRoleBinding are properly updated.
> Fix cluster role binding update

- controllers/datadogagent/utils.go
- controllers/datadogagent/utils_test.go
- controllers/testutils/new.go
Add missing `ConfigMap` used for the agent custom config (`datadog.yaml`) into he security-agent config.
Fix security-agent configuration issue.
N/A
Create a new DatadogAgent with security-agent compliance enabled. Also configure a custom agent configuration with the configMap option.
The security-agent should have this custom config configmap mounted.
> Add custom config in securty-agent container

- controllers/datadogagent/agent_test.go
- controllers/datadogagent/utils.go
Inject the required env vars to let the process agent communicate with the DCA
The process agent gets the cluster ID from the DCA
Fix https://github.com/DataDog/datadog-operator/pull/195
Same as https://github.com/DataDog/datadog-operator/pull/195
> [Fix][OrchExplorer] Allow the process agent to connect to the DCA

- api/v1alpha1/const.go
- api/v1alpha1/datadogagent_types.go
- api/v1alpha1/zz_generated.openapi.go
- config/crd/bases/v1/datadoghq.com_datadogagents.yaml
- config/crd/bases/v1beta1/datadoghq.com_datadogagents.yaml
- controllers/datadogagent/utils.go
Fix some issues with UDS paths that do not allow using both UDS at the same time
Activate `agent.apm.unixDomainSocket.enabled` and `agent.config.dogstatsd.unixDomainSocket.enabled`
> Fix duplicate paths for UDS Sockets

- controllers/datadogagent/clusteragent.go
Grant access to the `Lease` objects.
In recent versions of Kubernetes, the leader election mechanism has transitioned from dedicated annotations on `Endpoints` objects to dedicated `Lease` objects.
This extra permission is needed by DataDog/integrations-core#8535.
Spawn a version of the agent that contains DataDog/integrations-core#8535 on a recent Kubernetes cluster that uses `Lease` objects and make the `kube_scheduler` and `kube_controller_manager` checks use the `Lease` object:
```yaml
confd:
kube_scheduler.yaml: |-
ad_identifiers:
- kube-scheduler
init_config:
instances:
- prometheus_url: http://%%host%%:10251/metrics
leader_election_kind: lease
kube_controller_manager.yaml: |-
ad_identifiers:
- kube-controller-manager
init_config:
instances:
- prometheus_url: …
```
> Grant access to the Lease objects

- api/v1alpha1/zz_generated.openapi.go
- controllers/datadogagent/agent_test.go
- controllers/datadogagent/utils.go
Should fix: https://github.com/DataDog/datadog-operator/issues/229
https://github.com/DataDog/datadog-operator/issues/229
We only propagate the clusterName to the core agent and the DCA. But other agent might benefit as well. The process-agent tagger and orchestrator explorer need the cluster name.
> move the clusterName to common for every agent instead, if set

- api/v1alpha1/datadogagent_default.go
Creating a DatadogAgent with ClusterChecksEnabled did not have an
equivalent effect of creating a DatadogAgent without
ClusterChecksEnabled and then updating it to have ClusterChecksEnabled
set to true. This happened because, in the latter, the object was
already considered defaulted, but did not have a ClusterChecksRunner
spec.
Now, when we check the ClusterAgent spec, we also check that
ClusterChecksRunner is also set when applicable.
Fixes #232.
See #232.
> Default ClusterChecksRunner if ClusterChecksEnabled == true

- api/v1alpha1/datadogagent_default.go
- api/v1alpha1/datadogagent_default_test.go
- api/v1alpha1/datadogagent_types.go
- api/v1alpha1/zz_generated.openapi.go
- config/crd/bases/v1/datadoghq.com_datadogagents.yaml
- config/crd/bases/v1beta1/datadoghq.com_datadogagents.yaml
- controllers/datadogagent/utils.go
Improve fix from #224 
Activate `agent.apm.unixDomainSocket.enabled` and `agent.config.dogstatsd.unixDomainSocket.enabled`, check that both sockets on host are stored in `/var/run/datadog` and in container at `/var/run/datadog/<statsd|apm>`
> Improve UDS sockets fix - keep backward compatibility

- Makefile
- api/v1alpha1/datadogagent_types.go
- api/v1alpha1/test/new.go
- api/v1alpha1/zz_generated.deepcopy.go
- api/v1alpha1/zz_generated.openapi.go
- config/crd/bases/v1/datadoghq.com_datadogagents.yaml
- config/crd/bases/v1beta1/datadoghq.com_datadogagents.yaml
- controllers/datadogagent/utils.go
- controllers/datadogagent/utils_test.go
- controllers/testutils/new.go
- docs/configuration.md
Previously, it was only possible for the main agent container to have
user-specified VolumeMounts. This commit adds the possibility for each
container (process, apm, security) to have their own, specified
separately.
Internally, we want to have the agent auth_token in a different path, and we want that token to be available to all agents.
Specify a VolumeMount for each of the agents, and check that those volumes get mounted as specified.
> Allow custom VolumeMounts for all agent containers

- config/manager/manager.yaml
- controllers/setup.go
- controllers/suite_test.go
- main.go
- pkg/config/creds.go
- pkg/config/creds_test.go
- pkg/controller/utils/datadog/metrics_forwarder_test.go
- pkg/datadogclient/client.go
- pkg/secrets/types.go
- Add an argument to disable the `DatadogMonitor` controller
- Centralise the credentials management in the operator, which will allow the `DatadogMonitor` controller to get creds via secret backend
- If one of the controllers couldn't start, we don't `os.Exit(1)` anymore (example: if you don't provide creds, `DatadogMonitor` won't start, but `DatadogAgent` will do. 
- `DatadogMonitor` supports SB now
- `DatadogMonitor` can be disabled
- A follow-up PR (or commit) to revamp the metrics forwarder will come up next
- Do not provide creds, this should prevent `DatadogMonitor` from starting but shouldn't affect `DatadogAgent`
- Try to provide creds via secret backend, `DatadogMonitor` should be able to get them and start (you can use a secret mount + `readsecret.sh`)
- Configure the …
> [DatadogMonitor] Refactor creds management and support SB

- controllers/datadogagent/agent_test.go
- controllers/datadogagent/utils.go
Add missing `NET_RAW` capability to the system-probe container.
This capability is now requiered with CRIO due to a patch remediation
for the CVE-2020-14386.
Allow the system-probe to start or recent openshift cluster.
N/A
Deploy the Agent with system-probe enabled on Openshift dedicated. 
The container should start.
> Add missing NET_RAW Cap for CVE-2020-14386 mitigation

- controllers/datadogagent/common_configmap.go
- controllers/datadogagent/common_networkpolicy.go
- controllers/datadogagent/common_rbac.go
- controllers/datadogagent/controller_test.go
- controllers/datadogagent/poddisruptionbudget.go
- controllers/datadogagent/secret.go
- controllers/datadogagent/service.go
- controllers/datadogagent/utils.go
This PR avoid resources deletion not owned by the DatadogAgent Resource instance.
Fix: #237
The Datadog-operator was deleting resources without checking if it was the Owner of these resources.
N/A
You can follow the test plan proposed in #237
> Fix unwanted Resources deletion

- controllers/datadogagent/clusterchecksrunner_rbac.go
- controllers/datadogagent/clusterchecksrunner_rbac_test.go
- controllers/datadogagent/kubestatemetrics.go
- controllers/datadogagent/testdata/ksm_clusterrole.yaml
- go.sum
* Fix missing RBAC for `Events` in the KSM core check `ClusterRole`
* Fix `ClusterRole` update when the permissions change.
* Add unit-test to validate the create of the `ClusterRole` and `ClusterRoleBinding` 
Fixes: #253 
N/A
Deploy the Agents with the Operator, and enable the `kubeStateMetricsCore` check.
```yaml
metadata:
name: datadog
spec:
credentials:
apiSecret:
secretName: datadog
appSecret:
keyName: app-key
secretName: datadog
features:
kubeStateMetricsCore:
enabled: true
agent:
image:
name: "gcr.io/datadoghq/agent:7.26.0"
config:
tolerations:
- operator: Exists
clusterAgent:
image:
name: "gcr.io/datadoghq/cluster-agent:1.11.0"
config:
clusterChecksEnabled: true
clusterChecksRunner:
image:
name: …
```
> Fix KSM core RBAC issue with Events

- Makefile
- config/manager/manager.yaml
The `DatadogAgent` CRD can be install with `kubectl apply` with the
classic client side merge mechanism because the `last-apply` annotation
used by the `kubectl apply` command is generating a too long annotation
value for the CRD.
Current solution is to use the `server-side` merge management for
the kubectl apply command. Or use the `kubectl create` command.
Fix `make deploy` command
N/A
On a kubernetes 1.18+ cluster, install the operator with the command
`make deploy`
> Fix make deploy due to last-applied annotation size

- LICENSE-3rdparty.csv
- controllers/datadogagent/controller.go
- controllers/datadogagent/event.go
- controllers/datadogagent_controller.go
- controllers/setup.go
- main.go
- pkg/config/creds.go
- pkg/config/creds_test.go
- pkg/controller/utils/datadog/metrics_forwarder.go
- pkg/controller/utils/datadog/metrics_forwarder_test.go
- pkg/secrets/secrets.go
- pkg/secrets/types.go
- Disable/Enable the metrics forwarder via `operatorMetricsEnabled`
- The metrics forwarder uses `pkg/config` to get creds from the operator config as a fallback
- Add a creds caching in `GetCredentials`
- Add an exp backoff in `GetCredentials`
- Disable Datadog Monitor by default
- Restart the operator if Datadog Monitor is enabled + no creds provided 
Follow-up on https://github.com/DataDog/datadog-operator/pull/245
- Set the `operatorMetricsEnabled` operator argument to `false`, make sure the metrics forwarder doesn't start
- Enable Datadog Monitor by default, make sure the operator starts only when creds are provided
> Rework the creds manager

- api/v1alpha1/const.go
- controllers/datadogagent/agent_test.go
- controllers/datadogagent/utils.go
- controllers/datadogagent/utils_test.go
Use an EmptyDir volume shared between all the agents for logs so that `agent flare` can gather the logs of all of them.
This is the port of DataDog/helm-charts#193.
Deploy the agent with the operator, run `agent flare` and check that the flare contains the logs of all the agents and not only those of the core agent.
> Use an EmptyDir volume shared between all the agents for logs so that `agent flare` can gather the logs of all of them.

- api/v1alpha1/datadogmonitor_types.go
- api/v1alpha1/zz_generated.deepcopy.go
- config/crd/bases/v1/datadoghq.com_datadogmonitors.yaml
- config/crd/bases/v1beta1/datadoghq.com_datadogmonitors.yaml
- controllers/datadogmonitor/controller.go
- controllers/datadogmonitor/controller_test.go
- controllers/datadogmonitor/finalizer.go
Improve output of `kubectl get datadogmonitor` from
```
$ k get datadogmonitor -n datadog
NAME                   ID         MONITOR STATE   MONITOR CREATED              LAST UPDATED
datadog-monitor-test   33025468   No Data         2021-03-29T17:00:10Z         2021-03-29T16:58:10Z
```
to
```
NAME                     ID         MONITOR STATE   LAST TRANSITION        LAST SYNC              SYNC STATUS                AGE
datadog-monitor-test     33025468   Alert           2021-03-29T17:32:47Z   2021-03-30T12:52:47Z   OK                         19h
datadog-monitor-test-2   33071874   Alert           2021-03-30T12:37:52Z   2021-03-30T12:40:53Z   error validating monitor   6m46s
```
Better user experience
Build operator, install CRDs, apply …
> [datadogmonitor] make improvements to kubectl get output

- controllers/datadogagent/clusteragent.go
Fix the DCA RBAC.
Since the migration of the DCA to the `go-client` 1.18, the DCA needs some additional permissions to register an external metrics provider.
Make the operator future proof for the next DCA release.
This is a port of DataDog/helm-charts#210.
Check that the external metrics provider works with the `master` branch of the DCA.
> Fix DCA RBAC for the external metrics provider

- .gitlab-ci.yml
Add new gitlab job to generate internal image build.
Simplify release process.
> Trigger internal image generation

- main.go
Fix Operator leader election on vintage cluster by defaulting, 
the leader election resource to `configmaps` which is supported
on any k8s clusters version.
Fix leader-electio on vintage clusters.
Deploy the operator on a kubernetes clustet v1.10.
Check that the Operator is able to instanciate the leader election object.
> Fix operator leader election on vintage k8s cluster

- controllers/datadogagent/agent_test.go
- controllers/datadogagent/utils.go
From version `7.28.0` the `system-probe` agent will not support the
argument `-config` but instead `-c` or `--config`.
After some test `--config` is also supported by version <= 7.27.0.
So to be compatible with any `system-probe` version, the operator
is using `--config` for configuring the `system-probe` container.
Even if the `process-agent` haven't yet migrated to `cobra` fwk. It
it is safer to also use `--config`.
Deploy the agent with the operator. Enable `system-probe` and `process-agent`
Test with image `7.27.0` and `7.28.0-rc.1`. Both install should work.
> Fix `system-probe` and `process-agent` config arg

- controllers/datadogagent/agent_test.go
- controllers/datadogagent/utils.go
* Add missing `--sysprobe-config` argument to the `process-agent`.
* Use `const value` for the configuration files in `container` spec creation.
Fix process-agent configuration.
Deploy the agent with `process-agent` and `system-probe` enable. Check that the `process-agent` have the `--sysprobe-config` argument.
> Add missing argument to process-agent

- docs/cluster_agent_setup.md
- docs/configuration.md
- docs/getting_started.md
- docs/installation.md
For the Getting Started and Installation part of the docs, we shouldn't be promoting putting plain text secrets in resource definitions, so people can embrace good practices like GitOps, keeping their K8s configuration in Git
> Discourage putting plain text secrets in the DatadogAgent CRDs

- examples/datadogagent/datadog-agent-all.yaml
As stated in the docs, the config option to enable process monitoring is `agent.process.processCollectionEnabled`, not `agent.process.processCollection`
The current example is broken. This PR fixes it.
> Fix process collection config option

- api/v1alpha1/const.go
- controllers/datadogagent/agent_test.go
- controllers/datadogagent/systemprobe.go
- controllers/datadogagent/utils.go
- controllers/datadogagent/utils_test.go
* Update `system-probe` seccomp profile.
* Add `remote_tagger` config in `system-probe.yaml`.
* share auth token between agent to allow communication with the core-agent.
Compatibility with the agent `7.28.0`
Deploy the agent 7.28.0 with the operator. Enable runtime security.
> Update system-probe integration for 7.28.0

- api/v1alpha1/datadogagent_types.go
- api/v1alpha1/zz_generated.openapi.go
- config/crd/bases/v1/datadoghq.com_datadogagents.yaml
- config/crd/bases/v1beta1/datadoghq.com_datadogagents.yaml
- controllers/datadogagent/agent.go
- controllers/datadogagent/agent_test.go
- controllers/datadogagent/clusteragent.go
- controllers/datadogagent/clusteragent_test.go
- controllers/datadogagent/clusterchecksrunner.go
- controllers/datadogagent/const.go
- controllers/datadogagent/utils.go
- docs/configuration.md
Remove automatic copy of all labels/annotations from DatadogAgent CRD as it triggered copying of unwanted labels (like last-applied) and overwriting others (like kubernetes.io labels)
Deploy Agent through Operator, set custom Labels/Annotations on DatadogAgent object, make sure these Labels/Annotations are not present on created DS/Deployment except Datadog tags labels.
> Remove automatic copy of all labels/annotations from DatadogAgent CRD - now only Datadog tags labels will be copied

- api/v1alpha1/const.go
- controllers/datadogagent/clusteragent.go
- controllers/datadogagent/clusteragent_test.go
- controllers/datadogagent/clusterchecksrunner.go
- controllers/datadogagent/clusterchecksrunner_test.go
- Deactivate DSD in CLC Runners 
- Udpate DCA to new liveness/readiness
- Deploy an Agent with CLC Runner activated, make sure nothing listens on port 8125 inside CLC container.
- Check Cluster Agent container has liveness/readiness targeting port 5555 `/live` and `/ready`.
> Deactivate DSD in CLC Runners - udpate DCA to new liveness/readiness

- Makefile
- config/rbac/role.yaml
- controllers/datadogagent/clusteragent.go
- controllers/datadogagent/clusteragent_test.go
- controllers/datadogagent_controller.go
* Fix Cluster-Agent heatlh port configuration: set `DD_HEALTH_PORT` env
var to 5555.
* Fix Operator RBAC with "make deploy".
Deploy the Cluster-Agent with the operator. The DCA pod should be ready.
> Fix DCA health port

- api/v1alpha1/datadogagent_types.go
- api/v1alpha1/zz_generated.openapi.go
- config/crd/bases/v1/datadoghq.com_datadogagents.yaml
- config/crd/bases/v1beta1/datadoghq.com_datadogagents.yaml
- controllers/datadogagent/secret.go
- controllers/datadogagent/secret_agent.go
- controllers/datadogagent/secret_test.go
Do not use (or look for) credentials set in the Operator for DatadogAgent. (Only depend on the DatadogAgent spec.)
The fallback wasn't working properly; removing for now to revisit whether to include this later.
Make sure credentials are required in the DatadogAgent spec and that when included, it works properly
> remove fallback logic for credentials

- config/rbac/leader_election_role.yaml
Add missing permissions in leader election role used in deploys with kustomize
```
{"level":"ERROR","ts":"2021-05-03T14:59:27Z","logger":"controller-runtime.manager.controller.datadogagent","msg":"Reconciler error","reconciler group":"datadoghq.com","reconciler kind":"DatadogAgent","name":"datadog","namespace":"datadog","error":"clusterroles.rbac.authorization.k8s.io \"datadog-agent\" is forbidden: user \"system:serviceaccount:datadog:datadog-operator-manager\" (groups=[\"system:serviceaccounts\" \"system:serviceaccounts:datadog\" \"system:authenticated\"]) is attempting to grant RBAC permissions not currently held:\n{APIGroups:[\"coordination.k8s.io\"], Resources:[\"leases\"], Verbs:[\"get\"]}"}
```
Write there any instructions and details you …
> add missing permissions

- config/rbac/role.yaml
- controllers/datadogagent_controller.go
Fix one more RBAC issue for kustomize deploys
> fix clusterrole for kustomize

- api/v1alpha1/datadogagent_default.go
- api/v1alpha1/datadogagent_default_test.go
`IsDefaultedOrchestratorExplorer` would return `false` for the following
config, since `Scrubbing` would be `nil`:
```
enabled: false
```
Unfortunately, this caused the CR to never be reconciled, since the
defaulting does not add `Scrubbing` if the orchestrator explorer is
disabled.
To work around this, now we only check that `Scrubbing` is defaulted
when the orchestrator explorer is enabled.
Create a `DatadogAgent` with `spec.features.orchestratorExplorer.enabled` set to `false`. Check that agent pods actually get deployed, meaning that the CR was reconciled successfully. Note that taking an existing `DatadogAgent` with the orchestrator explorer enabled, and then disabling it, is not enough to test this change, as the default was already applied.
> Check Scrubbing for default only if OrchestratorExplorer is enabled

- LICENSE-3rdparty.csv
- api/v1alpha1/datadogagent_default.go
- controllers/datadogagent/agent_test.go
- controllers/datadogagent/controller_test.go
- controllers/datadogagent/utils.go
- controllers/datadogagent/utils_test.go
- go.mod
- go.sum
- pkg/utils/utils.go
- pkg/utils/version.go
- pkg/utils/version_test.go
- Deploy Agent >= 7.27 with Operator, `DOCKER_HOST` should not be set and `/var/run` should be mounted to `/host/var/run`
- Deploy Agent < 7.27 with Operator, `DOCKER_HOST` should be set and `/var/run` should be mounted to `/host/var/run`
> Improve support for environment autodiscovery by removing explicit setting of DOCKER_HOST by default with Agent 7.27+

- controllers/datadogagent/clusteragent.go
Adds the daemonsets rbac rules. We already define them here: https://github.com/DataDog/datadog-operator/blob/6a0a7333b9c176651291c8bc6a521b38a39be650/controllers/datadogagent/clusteragent.go#L1270-L1272. But they are only support `GET` while for the orchestrator explorer we need `LIST` and `WATCH` as well.
Related agent PR: https://github.com/DataDog/datadog-agent/pull/8119 (collects daemonsets on the DCA)
> [dca] add daemonsets list/watch for the cluster-agent

- api/v1alpha1/const.go
- controllers/datadogagent/agent_test.go
- controllers/datadogagent/clusterchecksrunner_test.go
- controllers/datadogagent/controller_test.go
- controllers/datadogagent/systemprobe.go
- controllers/datadogagent/utils.go
- controllers/datadogagent/utils_test.go
Allow either adding a custom policy for runtime security or overriding the default one through a configmap.
Motivation
The default policy is part of the base image but was overridden by the configmap. Every time we bumped the
default policy we had to also bump the configmap. As the policy is tied to the runtime security agent, it
introduced hard to address compatibilities issues.
> Set runtime security custom policy using config map

- controllers/datadogagent/clusterchecksrunner.go
- controllers/datadogagent/clusterchecksrunner_test.go
Currently CLC are broken when Security Agent is activated and `policiesDir` option is used.
Create DatadogAgent with CLC and custom security policies:
```
runtime:
enabled: true
policiesDir:
configMapName: security-runtime-policies
```
> Fix CLC manifest when custom RuntimeDir is used

- controllers/datadogagent/utils.go
Currently, due to previous defaulting of `DockerSocketPath`, we're always mounting Docker set even if not existing.
On a `containerd` deployment, deploy Datadog Agent with both `CriSocket.DockerSocketPath` (to standard, non-existing, path) and `CriSocket.CriSocketPath` to `containerd` socket.
The resulting POD manifest should mount `/var/run` as `runtimesocketdir` and the `containerd` check should run properly.
> Fix CRI vs Docker socket path priority. Always try to mount default runtime dir if using standard path to maximize usage of Env AD

- controllers/datadogagent/utils.go
Fix from #320 is missing order change in VolumeMounts. Removing the substring check has it would require to change Env var path too.
Same as #320
> Fix CRI vs Docker socket path priority in VolumeMounts (fix changes from #320)

- api/v1alpha1/datadogagent_types.go
- api/v1alpha1/zz_generated.deepcopy.go
- api/v1alpha1/zz_generated.openapi.go
- config/crd/bases/v1/datadoghq.com_datadogagents.yaml
- config/crd/bases/v1beta1/datadoghq.com_datadogagents.yaml
- controllers/datadogagent/utils.go
- docs/configuration.md
Set `agent.systemProbe.volumeMounts`, the extra volumeMounts should be set in `system-probe` container.
> Add support for system-probe extra volumeMounts

- api/v1alpha1/const.go
- controllers/datadogagent/clusterchecksrunner.go
- controllers/datadogagent/clusterchecksrunner_test.go
- controllers/datadogagent/const.go
Use the pod name as cluster check runner ID to allow deploying multiple cluster check runners on the same node. (Requires agent 7.27.0+)
Related to https://github.com/DataDog/helm-charts/pull/275
`agent clusterchecks` should show how the cluster agent identifies the runners by their pod names
> Use pod name as cluster check runner ID

- controllers/datadogagent/agent_test.go
- controllers/datadogagent/utils.go
Only copy the runtime security policies when runtime security is enabled
When runtime security is not enabled, one init container fails:
```
$ k logs datadog-agent-kmr2q -c init-volume -n datadog
cp: cannot stat '/etc/datadog-agent-runtime-policies/*': No such file or directory
```
> Only copy runtime policies when enabled

- controllers/datadogagent/finalizer.go
Call `cleanupMetricsServerAPIService` function in datadogagent finalizer.
Starting in Kubernetes 1.20 version, when deleting the `datadogagent` resource, or delete the datadog namespace, the metrics service APIService is not removed, leading to a stuck namespace state at Terminating.
```
NAME                                   SERVICE                                        AVAILABLE                 AGE
v1beta1.external.metrics.k8s.io        datadog/datadog-cluster-agent-metrics-server   False (ServiceNotFound)   2m15s
```
I did not found this scenario in Kubernetes version <= 1.19.
I'm not sure if I'm calling the `cleanupMetricsServerAPIService` in the best spot. Open for feedback.
You can test this issue by creating a testing cluster (eg: using kind) with Kubernetes version >= 1.20 and …
> Remove Metrics Server APIService in finalizer

- api/v1alpha1/datadogagent_default.go
- controllers/datadogagent/finalizer.go
- pkg/utils/version_test.go
Defaulting was not behaving properly for prelease/release candidate images because of image tag comparison using `semver`. If `-0` is added to the `minVersion` image being compared then prelease image tags are compared.
Ref: https://github.com/Masterminds/semver#working-with-prerelease-versions
Unexpected behavior when testing an agent release candidate
Test a datadog agent release candidate image with `DatadogAgent` in a non-Docker environment. Make sure that the `DOCKER_HOST` env var is not automatically set in the agent containers and the `docker` check does not run.
> fix version check to work with release candidates

- api/v1alpha1/datadogagent_default_test.go
- controllers/datadogagent/agent_test.go
- controllers/datadogagent/utils.go
When APM enable, configure automaticaly the TCP port as a `HostPort`.
Fixes: #312
Allow the usage of APM in applicative pod with the TCP communication.
N/A
Deploy the the agent with 
```yaml
#...
spec:
#...
agent:
apm:
enabled: true
```
the port `8126` on the `trace-agent` container should be created with the hostPort option.
> Fix APM HostPort configuration

- .github/workflows/release.yaml
Automate `datadog` krew plugin releasing in [krew-index|https://github.com/kubernetes-sigs/krew-index] repo.
It will generate automatically a PR, that will be merge automatically if only version,sha,uri change in the PR, like: https://github.com/kubernetes-sigs/krew-index/pull/1433
Limit releasing actions 
Difficult to test, from the action documentation, it will only public official release but not RC.
> Automate `datadog` krew plugin releasing

- controllers/datadogagent/agent_test.go
- controllers/datadogagent/utils.go
- controllers/datadogagent/utils_test.go
Fix issue with "security-runtime" policyDir configuration. which was removing the default configuration. Now the configuration provided by `policyDir` are added to the `/etc/datadog-agent/runtime-security.d` folder.
give more flexibility to the runtime policies configuration.
N/A
try to deploy the datadogagent with runtime-security enable. with 2 different configs
1. no custom config => the `default.policy` configuration should be present in `/etc/datadog-agent/runtime-security.d`
```yaml  
security:
runtime:
enabled: true
```
2. provide a configMapName + items. => `default.policy` configuration and the `custom.policy` files should be present 
```yaml
security:
runtime:
enabled: true
policiesDir:
configMapName: "runtime-config"
```
you can use the following configmap:
```yaml
apiVersion: …
```
> Fix runtime security config mount

- controllers/datadogagent/agent_eds_test.go
- controllers/datadogagent/testutils/doc.go
- controllers/datadogagent/testutils/extendeddaemonset_utils.go
- controllers/datadogagent/testutils/metadata_utils.go
- controllers/datadogagent/testutils/podtemplate_utils.go
Create new unittest helper to verify specific part of a PodTemplate, DS, EDS
easy unit-tests maintenance
> Create unit-test helper functions

- controllers/datadogagent/controller.go
Compare the same golang struct to detect defaultOverride update.
Fix untimely status update.
N/A
By running the operator, you should see less update conflict.
> Fix defaultOverride status update

- api/v1alpha1/datadogagent_default.go
- api/v1alpha1/datadogagent_default_test.go
- api/v1alpha1/test/new.go
- config/manager/manager.yaml
- controllers/datadogagent/agent_test.go
- controllers/datadogagent/controller_test.go
- controllers/datadogagent/utils.go
- controllers/datadogagent_controller_test.go
- controllers/testutils/new.go
- examples/datadogagent/datadog-agent-with-credential-secret.yaml
Fix the default of the cluster-agent to all be defaulted to `enabled:true`.
In a specific when the section "spec.clusterAgent" is not provided
in the DatadogAgent instance, the cluster-agent is not defaulted to
`spec.clusterAgent.enabled:true`.
N/A
Deploy the example: `datadog-agent-with-credential-secret.yaml`
The cluster-agent should be deployed. Defaulting value can be also
verified by checking the value of `dataddog.status.defaultOverride.clusterAgent.enabled`
> Fix cluster-agent defaulting to enable it by default

- controllers/datadogagent/systemprobe.go
> fix nil pointer panic in system-probe config

- api/v1alpha1/datadogagent_default.go
- api/v1alpha1/datadogagent_default_test.go
- api/v1alpha1/test/new.go
- controllers/datadogagent/clusteragent.go
- controllers/datadogagent/controller.go
- controllers/datadogagent/controller_test.go
- controllers/datadogagent/secret_agent.go
- controllers/datadogagent/secret_test.go
- controllers/datadogagent_controller_test.go
- controllers/testutils/new.go
* Improve agent defaulting by enabling it if `spec.Agent` is empty.
* Improve ClusterAgent defaulting by enabling it if `spec.ClusterAgent`
is empty.
* Fix credentials verification function.
DatadogAgent should valide even if only "spec.Credentials" and `spec.Features` are
provided.
N/A
Deploy the example: `examples/datadogagent/datadog-agent-with-credential-secret.yaml`
Expected results:
* ClusterAgent should be deployed
* Agent should be deployed
> Improve defaulting when spec.Agent|ClusterAgent empty

- controllers/datadogagent/agent_rbac.go
- controllers/datadogagent/clusteragent.go
- controllers/datadogagent/clusterchecksrunner_rbac.go
- controllers/datadogagent/common_rbac.go
- controllers/datadogagent/kubestatemetrics.go
- controllers/datadogagent/orchestrator.go
ClusterRoleBinding can't be update if we change its RoleRef because this field
is immutable.
To fix the issue, we now do `Delete` and `Create`. 
This PR also refactor the code base to define only one function responsible of updating a ClusterRoleBinding.
In operator v0.7, the clusterchecksrunner has its owner clusterrole (not shared with the agent ds).
So to migrate from Operator v0.6, the ClusterRoleBinding need to be updated. but a simple `Update()`
doesn't work due to the `RoleRef` immutability 
N/A
1. Deploy the operator v0.6.0
1. Deploy the DatadogAgent with clusterchecksrunner enabled.
1. Chek the status of the DatadogAgent, it should be `Active=true` like here
```console
NAME            ACTIVE   AGENT                CLUSTER-AGENT     CLUSTER-CHECKS-RUNNER   AGE
datadog-agent   True …
```
> fix clusterrolebinding update

- api/v1alpha1/const.go
- api/v1alpha1/datadogagent_default.go
- api/v1alpha1/datadogagent_default_test.go
- api/v1alpha1/datadogagent_types.go
- api/v1alpha1/test/new.go
- api/v1alpha1/zz_generated.openapi.go
- cmd/kubectl-datadog/agent/upgrade/upgrade.go
- cmd/kubectl-datadog/agent/upgrade/upgrade_test.go
- cmd/kubectl-datadog/clusteragent/upgrade/upgrade.go
- cmd/kubectl-datadog/clusteragent/upgrade/upgrade_test.go
- config/crd/bases/v1/datadoghq.com_datadogagents.yaml
- config/crd/bases/v1beta1/datadoghq.com_datadogagents.yaml
- controllers/datadogagent/agent_test.go
- controllers/datadogagent/clusteragent.go
- controllers/datadogagent/clusteragent_test.go
- controllers/datadogagent/clusterchecksrunner.go
- controllers/datadogagent/clusterchecksrunner_rbac_test.go
- controllers/datadogagent/clusterchecksrunner_test.go
- controllers/datadogagent/utils.go
- controllers/datadogagent/utils_test.go
- docs/configuration.md
- pkg/defaulting/images.go
- pkg/defaulting/images_test.go
Update defaulting images logic and have a dedicated package for defaulting.
The idea here is to update the Agent and Cluster-Agent image version with 
the lastest stable version each time we release the Operator. 
Keep up-to-date the agent and cluster-agent when deploying a new Operator version.
N/A
Deploy the example `examples/datadogagent/datadog-agent-with-credential-secret.yaml` 
* Check that the Agent image tag is `7.30.0` 
* Check that the Cluster-Agent image tag is `1.14.0`
> Standardize image defaulting

- docs/getting_started.md
Fixes a kubectl apply command in the getting started docs.
> [docs/getting_started] Fix kubectl apply command

- docs/configuration.md
- hack/generate-docs/footer.markdown
Fixes links to examples configs in `docs/configuration.md`.
> [docs/configuration] Fix links to example configs

- hack/install-kubebuilder.sh
Fixes the download link in the install-kubebuilder script. The old link format does not work. You can see it's failing in other PR (#359)
> [hack/install-kubebuilder] Fix donwload link

- controllers/datadogagent/clusteragent.go
- controllers/datadogagent/common_rbac.go
- controllers/datadogagent/common_rbac_test.go
- controllers/datadogagent/controller_test.go
- controllers/datadogagent/finalizer.go
- controllers/datadogagent/finalizer_test.go
We set the DatadogAgent object as the owner of the ClusterRoles and the ClusterRoleBindings that it creates. The reason to do that is to make sure that a cascade delete of the DatadogAgent will also delete its associated ClusterRoles and ClusterRoleBindings. However, that does not happen because DatadogAgent is namespace-scoped, while ClusterRoles and ClusterRoleBindings are not. When assigning the owner reference, Kubernetes raises a warning, and at delete time, it simply ignores that reference. The result is that ClusterRoles and ClusterRoleBindings are never deleted. Also, when a DatadogAgent is created with the same name as a previous one, the owner reference is not updated and still points to the old one.
This PR solves the issue. Instead of using owner references, it uses …
> [controllers/datadogagent] Ensure ClusterRoles and ClusterRoleBindings are deleted

- api/v1alpha1/datadogagent_default.go
Fix panic in feature override when process or system probe configs are empty
Same as https://github.com/datadog/datadog-operator/pull/348
> Fix panic in feature override when process or system probe configs are empty

- api/v1alpha1/datadogagent_default.go
- controllers/datadogagent/utils.go
- controllers/testutils/new.go
Bug discovered during the QA of #342.
* Fix defaulting of system-probe if security.runtime is enabled.
* Mount the security-runtime empty dir even if `policydir` is not set.
Bug discovered with the following `DatadogAgent` configuration
```yaml
metadata:
name: datadog
namespace: datadog
spec:
credentials:
apiKey: REDACTED
appKey: REDACTED
agent:
clusterName: foo
config:
kubelet:
image:
name: "gcr.io/datadoghq/agent:latest"
apm:
enabled: true
process:
enabled: true
processCollectionEnabled: true
log:
enabled: true
systemProbe:
bpfDebugEnabled: true
security:
runtime:
enabled: true
```
> Fix runtime security volumes creation

- README.md
Fixes the github actions badge. The `action-badges.now.sh` that we were using only works for repos that use the `master` branch
> [README] Fix github actions badge

- pkg/defaulting/images.go
* default `agent` image is now `7.31.0`
* default `cluster-agent` image is now `1.15.0`
deploy the agent with the example `datadog-agent-with-credential-secret.yaml`
the cluster-agent and agent should be deploy with the new versions.
> Update agent and cluster-agent default images

- controllers/datadogagent/agent.go
- controllers/datadogagent/clusteragent.go
- controllers/datadogagent/clusterchecksrunner.go
- controllers/datadogagent/common_rbac.go
- controllers/datadogagent/labels.go
- controllers/datadogagent/labels_test.go
- controllers/datadogagent/utils.go
- controllers/datadogagent_controller.go
Fixes the DatadogAgent controller setup so it watches ClusterRoles and ClusterRoleBindings. Those were not watched because we were using `.Owns()`. However, DatadogAgent is namespaced whereas ClusterRole and ClusterRoleBinding are cluster-scoped. That means that DatadogAgent cannot be their owner, and `.Owns()` does not work.
Instead of using owner references, we use a couple of labels to track the ownership. This PR also introduces a new `labels.go` file that includes some helpers to work with those labels.
Deploy a DatadogAgent and edit or delete any of the ClusterRoles or ClusterRoleBindings it creates. Just after doing that, you should see that the operator will receive a reconcile event and will revert the changes you made.
> [controllers/datadogagent] Fix watch of ClusterRoles and ClusterRoleBindings

- config/rbac/role.yaml
- controllers/datadogagent_controller.go
Fix RBAC issue; this is required for the cluster agent/admission controller.
The issue was observed when the operator was installed with OLM; ensure the DatadogAgent controller can run without issue.
> fix permissions for extendeddaemonsetreplicasets

- hack/patch-bundle.sh
Remove status defaultOverride in bundled version due to the CRD being too long
> [DatadogAgent] patch bundle to rm status defaultOverride

- controllers/datadogagent/clusteragent.go
- controllers/datadogagent/common_rbac.go
- controllers/datadogagent/const.go
- controllers/datadogagent/kubestatemetrics.go
- controllers/datadogagent/orchestrator.go
We introduced the `namespace` as prefix of the clusterrole and
clusterrolebinding to allow multi DatadogAgent deployment in a cluster.
But if the DatadogAgent namespace/name is very long like:
datadog-agent/datadog-agent the final rbac name for `orchestrator-explorer`
RBAC was: `datadog-agent-datadog-agent-orchestrator-explorer-cluster-agent`
which is longer than the limit of 64 chars.
This PR reduce the size by renaming it to `datadog-agent-datadog-agent-orch-exp-dca`
This PR also update the value in `app.kubernetes.io/instances` for cluster scoped resources like:
* clusterrole
* clusterrolebinding
Fix agent deployment
try to deploy the datadogAgent named `datadog-agent` in the namespace: `datadog-agent`
the install should work.
> Fix RBAC resource name too long

- controllers/datadogmonitor/monitor.go
The TriggerWindow is not set when defining a DatadogMonitor with anomaly detection.
The Datadog Operator reconciles the Monitor with the error `error validating monitor: 400 Bad Request: {\"errors\": [\"alert window query arg must match trigger window monitor option\"]}"}` because the TriggerWindow is never set as the code sets 2x the RecoveryWindow.
Anomaly Monitor did not work with Datadog Operator - so digged into the code to understand the reason as the Datadog Operator logs are not so useful finding the issue (a trace of the request send to DD would be nice on debug level)
Nope
I am a complete Newbie in Go and i have no Idea how to test it, but this seems for me just like a bug. I validated the method name by looking into the sources for the Option …
> Set the TriggerWindow correctly when an anomaly monitor is set up

- apis/datadoghq/v1alpha1/const.go
- config/rbac/role.yaml
- controllers/datadogagent/kubestatemetrics.go
- controllers/datadogagent/testdata/ksm_clusterrole.yaml
- controllers/datadogagent_controller.go
Add vpa permissions to ksm core rbacs
KSM Core in agent 7.33 supports VPA metrics
Same as https://github.com/DataDog/helm-charts/pull/453
Deploy a CR with ksm core enabled, make sure the KSM clusterrole contains vpa list and watch RBACs
> fix: add vpa permissions to ksm core rbacs

- controllers/datadogagent/agent.go
Adds missing FQDN rules to the agent Cilium network policy.
This was reported as a bug in the helm chart, but it is also present in the operator: https://github.com/DataDog/helm-charts/issues/456
Same as https://github.com/DataDog/helm-charts/issues/456
> Add missing FQDNs to Cilium network policy

- apis/datadoghq/v1alpha1/datadogagent_default.go
Make the network monitoring feature enable the process agent.
```yaml
spec:
features:
networkMonitoring:
enabled: true
```
should be enough to make the network monitoring product work, which requires the `process-agent`.
The orchestrator explorer feature also enables the `process-agent` and is enabled by default.
Spawn an agent with:
```yaml
spec:
features:
enabled: false
networkMonitoring:
enabled: true
```
It should instantiate a `process-agent`.
> The Network Monitoring feature enables the process agent

- apis/datadoghq/v1alpha1/const.go
- controllers/datadogagent/agent_test.go
- controllers/datadogagent/utils.go
Instead of replacing the /etc/datadog-agent/compliance.d directory with the content
of a configmap, merge the benchmarks bundled with the agent and the one provided
with the configmap.
This behaviour is the same than the security policies and it allows to both add new benchmarks
and replace existing ones.
> Merge custom and bundled compliance benchmarks

- controllers/datadogmonitor/monitor.go
- controllers/datadogmonitor/monitor_test.go
- go.mod
- go.sum
Update datadog api go client to 1.7.0
Have the most up to date client that supports more recent DD features
Make sure the DatadogMonitor controller works as expected (create monitor, update, monitor, delete monitor)
> update datadog api go client to 1.7.0

- pkg/defaulting/images.go
Updates agent to 7.33.0 and DCA to 1.17.0.
> [defaulting/images] Update latest agent and DCA

- apis/datadoghq/v1alpha1/const.go
- controllers/datadogagent/clusteragent.go
Fixes this error `subjectaccessreviews.authorization.k8s.io is forbidden: User "system:serviceaccount:datadog:datadog-cluster-agent" cannot create resource "subjectaccessreviews" in API group "authorization.k8s.io" at the cluster scope` that appears in the cluster agent when setting:
```
clusterAgent:
config:
enabled: true
```
Deploy with external metrics enabled and check that the error mentioned above does not appear in the cluster agent.
> [controllers/datadogagent/clusteragent] Add "subjectaccessreviews" to RBAC

- apis/datadoghq/v1alpha1/datadogagent_default.go
- apis/datadoghq/v1alpha1/datadogagent_default_test.go
This PR defaults `agent.Process.ProcessCollectionEnabled` in the DDA spec to avoid a panic in the operator when using the minimal DDA config recommended here:
https://github.com/DataDog/datadog-operator/blob/main/docs/getting_started.md#deploy-the-agent-with-the-operator
```
metadata:
name: datadog
spec:
credentials:
apiSecret:
appSecret:
keyName: app-key
```
Here's the trace:
```
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x0 pc=0x16237aa]
goroutine 424 [running]:
github.com/DataDog/datadog-operator/controllers/datadogagent.getVolumeMountsForProcessAgent(0xc00005f800,
0xc0009021e0, …
```
> Fix panic that happens when using the minimal recommended DDA

- config/rbac/role.yaml
- controllers/datadogagent_controller.go
Adds datadogmetrics RBACs.
These are needed when `useDatadogMetrics` is set to true in the cluster agent config.
```
clusterAgent:
config:
enabled: true
useDatadogMetrics: true
```
The operator now shows errors like this one because of the missing RBACs:
```
{"level":"ERROR","ts":"2022-01-18T11:57:38Z","logger":"controller-runtime.manager.controller.datadogagent","msg":"Reconciler error","reconciler group":"datadoghq.com","reconciler kind":"DatadogAgent","name":"datadog","namespace":"datadog","error":"clusterroles.rbac.authorization.k8s.io \"datadog-cluster-agent\" is forbidden: user \"system:serviceaccount:datadog:datadog-operator-manager\" (groups=[\"system:serviceaccounts\" \"system:serviceaccounts:datadog\" \"system:authenticated\"]) is attempting to grant RBAC …
```
> [controllers/datadogagent] Add "datadogmetrics" RBACs

- controllers/datadogagent/clusteragent.go
Fixes an error that happens when the external metrics option is enabled in the DCA:
```
clusterAgent:
config:
enabled: true
```
When creating a datadog metric, and an HPA object that references it, the DCA shows an error like this one:
```
...events is forbidden: User "system:serviceaccount:datadog:datadog-cluster-agent" cannot create resource "events" in API group ""...
```
This PR fixes the issue by adding create perms for events in the cluster agent cluster role. We're already setting these perms in the helm chart: https://github.com/DataDog/helm-charts/blob/0316b0ec18de7eda72279c3b683770efa502ffc7/charts/datadog/templates/cluster-agent-rbac.yaml#L22
Also note that I haven't tested the external metrics extensively, in this PR I just wanted to solve the RBAC issue. …
> Fix error raised in the DCA when using external metrics

- Makefile
- hack/install-operator-sdk.sh
- hack/install-wwhrd.sh
- hack/install-yq.sh
- hack/license.sh
- hack/patch-crds.sh
- hack/verify-license.sh
* Put binaries in a platform specific directory so that sharing a work tree between MacOS and Linux isn’t an issue anymore.
* Add a dependency between tools and the Makefile so that, when the desired version of a tool is updated in the Makefile, the tool is properly upgraded accordingly automatically without needing to be deleted manually.
I frequently switch between compiling from MacOS and from a Linux environment (docker devenv) which is mounting the `datadog-operator` worktree from the Mac.
At each switch, we get a `cannot execute binary file: Exec format error` error.
Also, when the versions of the tools (`yq`, `wwhrd`, `operator-sdk`, `golangci-lint`, etc.) is updated in the `Makefile`, the old and deprecated versions were kept in `/bin` forever.
In both cases, the errors were …
> Remove the frequent need to do `rm -rf bin` to “fix stuff”

- controllers/datadogagent/clusteragent.go
- controllers/datadogagent/clusteragent_metricsserver.go
Fixes the cluster role binding that we create to give permissions to the HPA to read external metrics.
The problem was that when reconciling the cluster role binding we were providing a wrong "update if needed" function that was meant to be used to reconcile a different cluster role binding.
As a result, HPA objects reported errors related with not being able to read "external.metrics.k8s.io" objects. Like this one:
```
Warning  FailedGetExternalMetric       3m2s (x201 over 53m)  horizontal-pod-autoscaler  unable to get external metric ecommerce/datadogmetric@ecommerce:frontend-hits/nil: unable to fetch metrics from external metrics API: datadogmetric@ecommerce:frontend-hits.external.metrics.k8s.io is forbidden: User "system:serviceaccount:kube-system:horizontal-pod-autoscaler" cannot …
```
> [controllers/datadogagent/clusteragent] Fix "externalmetrics" cluster role binding

- pkg/defaulting/images.go
* Update default Datadog Agent image to `7.34.0`
* Update default Datadog Cluster Agent image to `1.18.0`
The Operator should deploy the latest Agent and Cluster-Agent version.
Deploy a DatadogAgent from the examples folder without setting the Agent
or the Cluster-Agent. 
Agent image `7.34.0` and Cluster-Agent `1.18.0` should be used.
> feat: update Agent to 7.34.0 and DCA to 1.18.0

- docs/install-openshift.md
The example config shown in `docs/install-openshift.md` has bad indentation and gives an error when deploying it. This PR fixes the issue.
Run `kubectl apply -f` with the new config and check that there are no errors.
> [docs/openshift] Fix example config

- controllers/datadogagent/clusteragent.go
- controllers/datadogagent/clusteragent_test.go
- controllers/datadogagent/clusterchecksrunner.go
- controllers/datadogagent/clusterchecksrunner_test.go
- controllers/datadogagent/utils.go
Mounts the log volume in the DCA and the CLC. This is the same that the operator already does for the daemonset agent.
Without this, from the latest changes that allow the DCA and CLC to run as non-root, there are permissions errors like this one:
`open /var/log/datadog/cluster-agent.log: read-only file system`
Deploy on Openshift with DCA and CLC running as non-root users (this is the default since https://github.com/DataDog/datadog-operator/pull/448). Check that the error mentioned above is not in the DCA or CLC logs.
> [controllers/datadogagent] Mount logs volume in DCA and CLC

- apis/datadoghq/v1alpha1/datadogagent_types.go
- apis/datadoghq/v1alpha1/zz_generated.openapi.go
- config/crd/bases/v1/datadoghq.com_datadogagents.yaml
- config/crd/bases/v1beta1/datadoghq.com_datadogagents.yaml
- controllers/datadogagent/agent.go
- controllers/datadogagent/clusteragent.go
- controllers/datadogagent/clusterchecksrunner.go
- controllers/datadogagent/secret.go
- controllers/datadogagent/secret_agent.go
- controllers/datadogagent/secret_clusteragent.go
- controllers/datadogagent/secret_common.go
- controllers/datadogagent/secret_test.go
- controllers/datadogagent/utils.go
- controllers/testutils/new.go
- docs/configuration.md
- docs/secret_management.md
- examples/datadogagent/datadog-agent-secret-backend.yaml
- pkg/controller/utils/shared_utils.go
- pkg/secrets/utils.go
The secret backend feature for DatadogAgent was not working properly. This fixes the feature so that any credentials can use it. In addition, the Operator no longer creates a secret if it's not needed (i.e. it will not create an empty secret).
Other changes:
- create secret_common.go to hold common functions
- add new examples/datadogagent/datadog-agent-secret-backend.yaml
- update secret backed documentation
Fix
Use the new `datadog-agent-secret-backend.yaml` example file to test the secret backend feature.
For completeness, can test the following cases (make sure the keys are read properly and the Agent can connect to the Cluster Agent):
(Create a secret containing credentials with `kubectl create secret generic test-secret …
> Fix DatadogAgent secret backend usage

- apis/datadoghq/v1alpha1/const.go
- controllers/datadogagent/clusteragent.go
- controllers/datadogagent/clusteragent_test.go
- controllers/datadogagent/clusterchecksrunner.go
- controllers/datadogagent/clusterchecksrunner_test.go
- controllers/datadogagent/utils.go
Mounts /tmp with write permissions as an "empty dir" volume.
This is needed because some versions of the DCA (at least until 1.19.0) write to /tmp.
In some code paths, the klog lib writes to /tmp instead of using the standard datadog logs path. This seems to be a bug in the code, because most of the calls to klog are wrapped and converted to the datadog log format, but not all of them.
In some envs like Openshift, when running as non-root, the pod will not have permissions to write on /tmp, that's why we need to mount it with write perms.
Run on Openshift with DCA v1.19.0. Check that the DCA doesn't crash with an error like this one:
```
log: exiting because of error: log: cannot create log: open /tmp/datadog-cluster-agent.datadog-cluster-agent-67889c8974-g5vfs.dd-agent.log.WARNING.2022040 …
```
> [controllers/datadogagent] Mount tmp volume in DCA and CLC

- apis/datadoghq/v1alpha1/const.go
- controllers/datadogagent/clusteragent.go
- controllers/datadogagent/clusteragent_metricsserver.go
- controllers/datadogagent/common_rbac.go
- controllers/datadogagent/common_rbac_test.go
- docs/secret_management.md
To support use of the secret backend multiple providers script in the agent when deployed with the Datadog Operator.
Feature parity 
- Create a secret called `test-secret` (in the example below, it is in the `system` namespace)
- Modify the examples/datadogagent/datadog-agent-secret-backend.yaml file to include the following:
```
spec:
credentials:
apiKey: ENC[k8s_secret@system/test-secret/api_key]
appKey: ENC[k8s_secret@system/test-secret/app_key]
useSecretBackend: true
agent:
env:
- name: DD_SECRET_BACKEND_COMMAND
value: "/readsecret_multiple_providers.sh"
clusterAgent:
enabled: true
config:
env:
- name: DD_SECRET_BACKEND_COMMAND
value: "/readsecret_multiple_providers.sh"
```
- make sure that the agents and cluster agent start properly, and …
> update rbac to support secret backend multiple providers script

- controllers/datadogagent/agent_test.go
- controllers/datadogagent/clusteragent.go
- controllers/datadogagent/clusteragent_test.go
- controllers/datadogagent/clusterchecksrunner.go
- controllers/datadogagent/clusterchecksrunner_test.go
- controllers/datadogagent/utils.go
Do not enforce a specific non-`root` user in the `SecurityContext` of the cluster agent and the cluster check runners.
Partial revert of #448.
The cluster agent and the cluster check runners don’t need to run as `root`.
But explicitly setting a user (`dd-agent` with UID `101`) breaks on OpenShift where the `restricted` SCC already forces those two components to run with a random OpenShift-chosen UID.
In order to not break on OpenShift and still not default to `root` user on non-OpenShift setups, here is what should be done instead:
* define a non-`root` default user in the agent and cluster-agent docker images.
* https://github.com/DataDog/datadog-agent/blob/71552876f9be5ad67d525589489e91d98cd7839b/Dockerfiles/agent/amd64/Dockerfile#L162-L166
* …
> Do not enforce `dd-agent` user (UID 101) for the CLC and DCA

- apis/datadoghq/v1alpha1/const.go
- controllers/datadogagent/clusteragent.go
- controllers/datadogagent/clusteragent_test.go
- controllers/datadogagent/utils.go
Mounts the certificates volume in the DCA.
This is needed when enabling external metrics and running on Openshift as non-root (which is the default now).
Run on Openshift with:
```
...
clusterAgent:
config:
enabled: true
useDatadogMetrics: true
...
```
Check that there are no errors in the DCA like this one:
`Error in the External Metrics API Server: error creating self-signed certificates: mkdir /etc/datadog-agent/certificates: read-only file system`.
> [controllers/datadogagent] Mount certificates volume in DCA

- Dockerfile
Update to golang 1.17 the  operator `Dockerfile`.
the PR #462 missed to update the `Dockerfile`
the next operator release, check the golang version in the binary
> fix: update golang version in dockerfile

- pkg/defaulting/images.go
Updates default agent image to latest 7.35.0.
7.35.0 should be deployed by default.
> [defaulting/images] Update agent to 7.35.0

- apis/datadoghq/v1alpha1/const.go
- controllers/datadogagent/service.go
Add port names to the agent service.
When enabling both dogstatsd and APM, the agent service tries to expose 2 unnamed ports, which is [not allowed by Kubernetes](https://kubernetes.io/docs/concepts/services-networking/service/#multi-port-services) as it is considered ambiguous. The operator logs give the following error:
```json
{"level":"ERROR","ts":"2022-04-11T02:23:42Z","logger":"controller-runtime.manager.controller.datadogagent","msg":"Reconciler error","reconciler group":"datadoghq.com","reconciler kind":"DatadogAgent","name":"datadog","namespace":"default","error":"Service \"datadog-agent\" is invalid: [spec.ports[0].name: Required value, spec.ports[1].name: Required value]"}
```
Spin up a DatadogAgent with APM enabled in the agent spec (`agent.apm.enabled=true`) so that both …
> Add port names to agent service

- pkg/defaulting/images.go
Update default cluster agent image to `1.19.0`.
Deploy the cluster agent without specifying an image tag. It should spin up cluster agent version `1.19.0`.
> Update default DCA image to 1.19.0

- controllers/datadogagent/service.go
- pkg/utils/version_test.go
Fix how we detect the Kubernetes version.
the information was already present in the reconciler.
the `manageAgentService()` function now use the information
from the `Reconcile` struct. 
Fix how we detect the Kubernetes version to automaticaly
create the local agent service if it is supported by the
kubernetes version.
deploy the operator and create the `DatadogAgent` with this manifest
```yaml
metadata:
name: datadog
spec:
agent:
apm:
enabled: true
clusterName: foo
credentials:
apiSecret:
appSecret:
keyName: app-key
```
the service `datadog-agent` should be created in the same namespace.
> fix: k8s version detection for agent service

- controllers/datadogagent/service.go
- pkg/utils/version_test.go
backport #472: fix k8s version detection for agent service
> [backport] fix: k8s version detection for agent service (#472)

- pkg/defaulting/images.go
Update default agent image to 7.35.2.
Deploy the agent without specifying an image tag. It should spin up agent version 7.35.2.
> Default Agent version to 7.35.2

- apis/datadoghq/common/envvar.go
- controllers/datadogagent/feature/kubernetesstatecore/feature.go
Fix how we configure the `kubernetes_state_core` check feature:
* It should run in cluster-check-runner only if they are enabled.
Create an DatadogAgent with ksm-core enable, but without CLC runner enabled:
* the check should run in the DCA
Then update the DatadogAgent with CLC runner enabled:
* the check should now run in the clc-runner.
> fix(ksm-core): set CLC Runner enabled properly

- apis/datadoghq/v1alpha1/datadogagent_default.go
- apis/datadoghq/v1alpha1/datadogagent_default_test.go
- apis/datadoghq/v2alpha1/const.go
- controllers/datadogagent/clusteragent.go
- controllers/datadogagent/clusterchecksrunner_rbac.go
- controllers/datadogagent/common/const.go
- controllers/datadogagent/common_rbac.go
- controllers/datadogagent/component/clusterchecksrunner/default.go
- controllers/datadogagent/component/utils.go
- controllers/datadogagent/controller.go
- controllers/datadogagent/controller_reconcile_agent.go
- controllers/datadogagent/controller_reconcile_ccr.go
- controllers/datadogagent/controller_reconcile_v2.go
- controllers/datadogagent/controller_test.go
- controllers/datadogagent/feature/dummy/feature.go
- controllers/datadogagent/feature/enabledefault/feature.go
- controllers/datadogagent/feature/kubernetesstatecore/feature.go
- controllers/datadogagent/feature/logcollection/feature.go
- controllers/datadogagent/feature/test/testsuite.go
- controllers/datadogagent/feature/types.go
- docs/data_collected.md
- pkg/controller/utils/datadog/metrics_forwarder.go
- pkg/controller/utils/datadog/metrics_forwarder_test.go
This is a cosmetic PR to unify the naming of ClusterChecksRunner (i.e. not ClusterCheckRunner) to match our docs.
Note, this will also rename the metric `datadog.operator.clustercheckrunner.deployment.success` -> `datadog.operator.clusterchecksrunner.deployment.success`
> uniformly name clusterchecksrunner

- .gitlab-ci.yml
- Makefile
- check-operator.Dockerfile
- cmd/check-operator/README.md
- cmd/check-operator/main.go
- cmd/check-operator/root/root.go
- cmd/check-operator/upgrade/upgrade.go
Add a small check to be run as a helm test job for both operator and agent with operator deploys. It checks the rolling-updates status of the agent via the operator status.
Improve CI reliability
This will be tested closely in the internal infra
> feat: add a status-check to be used for helm test

- pkg/defaulting/images.go
Updates the agent image to 7.36.1 and DCA to 1.20.0.
Check that the operator deploys those versions by default.
> [defaulting/images] Update agent to 7.36.1 and DCA to 1.20.0

- controllers/datadogagent/component/agent/default.go
- controllers/datadogagent/component/utils.go
Implements the default agent component. Similar to what #506 did for cluster check runners.
I think it should be tested together with [#506](https://github.com/DataDog/datadog-operator/pull/506) and https://github.com/DataDog/datadog-operator/pull/491
> [controllers/datadogagent/component] Implement default agent

- apis/datadoghq/common/const.go
- apis/datadoghq/v1alpha1/const.go
- controllers/datadogagent/agent_test.go
- controllers/datadogagent/component/agent/default.go
- controllers/datadogagent/component/utils.go
- controllers/datadogagent/controller_reconcile_agent.go
- controllers/datadogagent/controller_reconcile_v2.go
- controllers/datadogagent/utils.go
Continues the work started in #507 
This PR implements the default agent containers returned in the `NewDefaultAgentPodTemplateSpec` function
Same as #507.
> [controllers/datadogagent/component] Implement default agent containers

- controllers/datadogagent/feature/kubernetesstatecore/configmap.go
Enable the ingress collector in the default ksm core configuration
Related to https://github.com/DataDog/datadog-agent/pull/12344
Enable the KSM core check and make sure it sends ingress metrics (assuming there are ingress objects in the cluster + agent 7.38)
> feat(ksmcore): enable ingress metrics

- controllers/datadogagent/feature/eventcollection/feature.go
This PR adds a missing nil check in the event collection feature.
This fixes a panic in the operator when `v2alpha1` is enabled and using the example `datadogagent` in `examples/v2alpha1/min.yaml`. There are more errors, but they're unrelated to this one, so I'll address them on a different PR.
Try with `v2alpha1` enabled (`KUSTOMIZE_CONFIG=config/test-v2 make deploy`) and check that the operator doesn't panic when configuring the event collection feature.
> [feature/eventcollection] Add missing nil check

- controllers/datadogagent/component/agent/default.go
- controllers/datadogagent/component/clusteragent/utils.go
- controllers/datadogagent/component/clusterchecksrunner/default.go
- controllers/datadogagent/feature/enabledefault/feature.go
- controllers/datadogagent/feature/enabledefault/rbac.go
- controllers/datadogagent/feature/eventcollection/feature.go
- controllers/datadogagent/feature/eventcollection/feature_test.go
- controllers/datadogagent/override/global.go
- controllers/datadogagent/service.go
Fixes the issues that were preventing the agent and the DCA to boot when using v2 (`KUSTOMIZE_CONFIG=config/test-v2`).
Notice that there might be other issues when enabling certain features. The goal of this PR is just to make the agent and the DCA start correctly when using the default config.
Deploy with v2 (`KUSTOMIZE_CONFIG=config/test-v2 make deploy`) and check that the daemonset agent and the DCA start correctly.
> [v2alpha1] Fix issues so agent and DCA boot without errors

- Dockerfile
Fix the CVEs blocking publishing in the google marketplace. Bumping to the new UBI seems to be sufficient.
```
➜  datadog-operator git:(char/fix-cve-080) ✗ docker scan charlyyfon/operator:v0.8.1
Testing charlyyfon/operator:v0.8.1...
Package manager:   linux
Project name:      docker-image|charlyyfon/operator
Docker image:      charlyyfon/operator:v0.8.1
Platform:          linux/amd64
✔ Tested charlyyfon/operator:v0.8.1 for known vulnerabilities, no vulnerable paths found.
```
Publish the latest version in the google marketplace.
> Update base image to fix CVEs

- controllers/datadogagent/utils.go
When loading the agent through the operator with a default config like:
```yaml
metadata:
name: datadog
spec:
credentials:
apiKey: XX
appKey: YY
agent:
security:
runtime:
enabled: true
```
The CWS policies directory is empty. The reason explaining this issue is that the policies dir is always mounted, even when no override is defined by the user. This means that in the default case we are overriding the default rules with a mount to a non-existant/empty folder
> CWS: fix runtime policies loading, when no config map is defined

- controllers/datadogagent/utils.go
* Only mount CWS policies volume if policies dir is defined
* Do not create system-probe/security-agent volumes is not needed
Cherry-pick #522 onto v0.8 branch
> CWS: fix runtime policies loading, when no config map is defined (#522)

- controllers/datadogagent/feature/cspm/feature.go
- controllers/datadogagent/feature/eventcollection/feature.go
- controllers/datadogagent/feature/kubernetesstatecore/feature.go
Fixes an issue in the reconciler v2. The role bindings are not properly set for these 3 features:
```
spec:
features:
eventCollection:
collectKubernetesEvents: true
kubeStateMetricsCore:
enabled: true
cspm:
enabled: true
```
The operator was trying to create the role bindings for the event collection and the CSPM features without a namespace. For KSM it was trying to create it without a name too.
This causes errors like this one:
```
{"level":"ERROR","ts":"2022-07-05T16:52:40Z","logger":"controller.datadogagent","msg":"Reconciler error","reconciler group":"datadoghq.com","reconciler kind":"DatadogAgent","name":"datadog","namespace":"system","error":"ClusterRoleBinding.rbac.authorization.k8s.io \"system-datadog-cspm-cluster-agent\" is invalid: subjects[0].namespace: Required …
```
> [features] Fix RBACs

- controllers/datadogagent/controller_reconcile_v2_common.go
Fixes a bug in the reconciler V2. The agent status was not updated always.
The agent status should be updated according to the status of the daemonset.
> [reconciler_v2] Keep agent status updated according to DaemonSet

- apis/datadoghq/v1alpha1/datadogagent_conversion.go
Silences an error that spams the logs every second and seems to be harmless. Not sure where those requests to convert v1 to v2 are coming from.
I've added a TODO comment so we don't forget to check this.
> [v1alpha1/conversion] Silence error

- controllers/datadogagent/component/clusterchecksrunner/default.go
- controllers/datadogagent/component/clusterchecksrunner/default_test.go
Fixes the default service account name used by the cluster checks runner.
The KSM core was not working when running on the runners because they were using the wrong service account.
KSM core check should work properly when running on a cluster check runner.
> [component/ccr] Fix default service account name

- controllers/datadogagent/controller.go
Registers the dogstatsd feature.
We probably forgot to register it when it was implemented.
> [controllers/datadogagent] Register dogstatsd feature

- controllers/datadogagent/merger/security_context.go
- controllers/datadogagent/merger/security_context_test.go
Fixes the function responsible for adding capabilities to a container in the reconciler v2 (`AddCapabilitiesToContainer` in the merger package).
I added some tests to verify that the fix works. These tests don't pass on main.
The problem was that the function was adding the capabilities to a copy instead of the wanted object.
The reconciler v2 was not adding capabilities to containers, now it should when needed. For example, when enabling the NPM feature, it should add some capabilities to the system-probe container.
> [merger/security_context] Fix AddCapabilitiesToContainer

- controllers/datadogagent/feature/npm/feature.go
- controllers/datadogagent/feature/npm/feature_test.go
- controllers/datadogagent/feature/usm/feature.go
- controllers/datadogagent/feature/usm/feature_test.go
- controllers/datadogagent/object/volume/volumes.go
Fixes the volume mount permissions for system-probe when the NPM or the USM features are enabled.
Enable the features and verify that the system-probe container is not in `CrashLoopBackOff` state because some volume is read-only.
> [feature/{npm,usm}] Fix system-probe volume mount perms

- controllers/datadogagent/agent_test.go
- controllers/datadogagent/component/agent/default.go
- controllers/datadogagent/feature/cws/feature.go
- controllers/datadogagent/feature/cws/feature_test.go
- controllers/datadogagent/feature/npm/feature.go
- controllers/datadogagent/feature/npm/feature_test.go
- controllers/datadogagent/feature/oomkill/feature.go
- controllers/datadogagent/feature/oomkill/feature_test.go
- controllers/datadogagent/feature/tcpqueuelength/feature.go
- controllers/datadogagent/feature/tcpqueuelength/feature_test.go
- controllers/datadogagent/feature/usm/feature.go
- controllers/datadogagent/feature/usm/feature_test.go
- controllers/datadogagent/utils.go
Fixes the OOM Kill and TCP Queue Length features when reconciler V2 is enabled.
Both of them were failing for the same reasons:
- The required security context capabilities were not being added to the system-probe container.
- The debugfs volume was missing.
The first commit is a refactor to define the capabilities needed for system-probe in a single place.
Check that both features work correctly. Keep in mind that they don't work in all hosts. On my GKE cluster, they work on the ubuntu nodes, but not the COS ones. It's the same when I deploy with the Helm chart, so the problem is not in the operator.
> [features] Fix OOM Kill and TCP Queue Length

- controllers/datadogagent/clusteragent_test.go
- controllers/datadogagent/controller.go
- controllers/datadogagent/controller_reconcile_v2.go
- controllers/datadogagent/feature/factory.go
Deletes an unnecessary error return parameter from a couple of functions in `controllers/datadogagent/feature/factory.go`: `BuildFeatures` and `BuildFeaturesV1`.
Skip.
> [features/factory] Delete unnecessary err return in BuildFeatures funcs

- controllers/datadogagent/feature/orchestratorexplorer/feature.go
- controllers/datadogagent/feature/orchestratorexplorer/feature_test.go
Fixes the Orchestrator Explorer feature when it runs on a Cluster Check Runner. We were missing some envs in that case. `agent status` was showing this error:
```
Core Check Loader:
Could not configure check orchestrator: orchestrator check is configured but the feature is disabled
```
Deploy with the orchestrator explorer feature enabled. Check that it works.
> [feature/orchestratorexplorer] Set ENVs when running on Cluster Checks Runner

- pkg/defaulting/images.go
Updates the default agent image to 7.38.0
Check that 7.38.0 is the version deployed by default.
> [defaulting/images] Update agent to 7.38.0

- cmd/check-operator/upgrade/upgrade.go
On new cluster deploy, the upgrade check should expect that the `DatadogAgent` cannot be found.
> fix(check-operator): pass the upgrade check when DatadogAgent is not found

- pkg/defaulting/images.go
Updates the DCA image to 1.22.0.
DCA 1.22.0 should be deployed by default.
> [defaulting/images] Update DCA to 1.22.0

- controllers/datadogagent/feature/kubernetesstatecore/configmap.go
- controllers/datadogagent/feature/kubernetesstatecore/configmap_test.go
- controllers/datadogagent/feature/kubernetesstatecore/feature.go
Changes the KSM feature so that it runs on the DCA instead of a daemonset agent when cluster checks are enabled but with no runners deployed.
This is because the KSM check is not designed to run on the daemonset agents.
Configure the cluster checks feature with:
```
clusterChecks:
enabled: true
useClusterChecksRunners: false
```
and verify that the check runs on the DCA.
> [feature/ksm] Don't schedule on the DaemonSet Agent

- controllers/datadogagent/component/agent/default.go
- controllers/datadogagent/feature/cws/feature.go
- controllers/datadogagent/feature/cws/feature_test.go
Fixes a bug in the CWS. There was an error in the system-probe container because it couldn't fetch the token for the remote tagger connection.
I did these changes based on what we're already doing in the helm charts.
Enable the CWS feature and check that there are no errors in the system-probe container.
> [feature/cws] Fix tagger auth error

- controllers/datadogagent/clusteragent_test.go
- controllers/datadogagent/component/clusteragent/default.go
Changes the DCA anti-affinity from "required" to "preferred".
This is because when using "required" agent updates can't work on clusters with 1 node.
We're already using "preferred" in the cluster check runners.
Deploy in a cluster with one node. Make an update that affects the DCA, for example, enable/disable the orchestrator explorer feature. Check that the new DCA pod is deployed correctly.
> [component/clusteragent] Change anti-affinity to "preferred"

- controllers/datadogagent_controller_v2_test.go
- controllers/testutils/agent.go
Adds an integration tests with an agent with some global settings set.
Skip.
> [controller_v2_test] Test agent with global settings

- controllers/datadogagent/override/global.go
The registry in global settings wasn't properly setting the image registry in the containers.
Change the image registry and ensure it's reflected in the resulting pods.
```yaml
spec:
global:
registry: public.ecr.aws/datadog
```
```
> kubectl get po -l app.kubernetes.io/managed-by=datadog-operator -o jsonpath='{range .items[*]}{"pod: "}{.metadata.name}{"\n"}{range .spec.initContainers[*]}{"     initcontainer: "}{.name}{"\n     image: "}{.image}{"\n"}{end}{range .spec.containers[*]}{"     container: "}{.name}{"\n     image: "}{.image}{"\n"}{end}{end}'
pod: datadog-agent-xxxxx
initcontainer: init-volume
image: public.ecr.aws/datadog/agent:7.38.0
initcontainer: init-config
image: …
```
> Fix image registry setting

- pkg/defaulting/images.go
Updates the agent image to 7.38.1.
agent 7.38.1 should be deployed by default.
> [defaulting/images] Update agent to 7.38.1

- controllers/datadogagent/utils_test.go
Deletes the unused `generateSpec` func from `controllers/datadogagent/utils_test.go`.
Skip.
> [utils/test] Delete unused generateSpec func

- apis/datadoghq/v2alpha1/condition.go
- controllers/datadogagent/component/new.go
- controllers/datadogagent/controller_reconcile_agent.go
- controllers/datadogagent/controller_reconcile_v2_common.go
Adds EDS support to v2 reconciler
* Deploy EDS controller: https://github.com/DataDog/extendeddaemonset#deployment
* Start operator with `supportExtendedDaemonset`: [example in helm templates](https://github.com/DataDog/helm-charts/blob/1432627093df17f009d95de8695c6b8ee85c630c/charts/datadog-operator/templates/deployment.yaml#L91)
* Spin up a DatadogAgent using v2alpha1
* Label any nodes you want pods from the EDS to go on due to [this EDS bug](https://github.com/DataDog/extendeddaemonset/issues/100): `kubectl label node <node> agent.datadoghq.com/component=agent agent.datadoghq.com/name=datadog`
* Check that an EDS, ERS, and agent pods are spun up
```bash
> kubectl get pods
NAME …
```
> Add EDS Support

- controllers/datadogagent/controller.go
- controllers/datadogagent/controller_test.go
- pkg/controller/utils/datadog/forwarders_manager.go
- pkg/controller/utils/datadog/metrics_forwarder.go
Update metrics forwarder manager to use an interface in lieu of the custom status condition. This is an intermediary step to support a metrics forwarder v2 that uses the metav1.Condition rather than the custom v1alpha1.DatadogAgentCondition.
Deploy the operator with `operatorMetricsEnabled=true` and test a v1 DatadogAgent custom resource. Make sure metrics report as expected.
> update metrics forwarder manager to use an interface for the status condition

- README.md
- docs/configuration.v1alpha1.md
- docs/configuration.v2alpha1.md
- docs/getting_started.md
#435 renamed `docs/configuration.md` to `docs.configuration.v1alpha1.md`, but that broke links to that page. This fixes the links.
I also noticed that the example manifest in `configuration.v2alpha1.md` still referred to `v1alpha1`, which I assume is a copy-paste typo.
I clicked on the "Configuration" link in the README and it took me to a 404 page.
n/a, doc change only
> fix config links and apiVersion of example

- docs/configuration.v1alpha1.md
- docs/configuration.v2alpha1.md
- hack/generate-docs.go
- hack/generate-docs/header.markdown
- hack/generate-docs/v1alpha1_example.markdown
- hack/generate-docs/v2alpha1_example.markdown
Adapts the `generate-docs` script to generate docs both for v1 and v2.
> [hack] Adapt generate-docs script to output 2 versions

- controllers/datadogagent/finalizer.go
Fixes a compilation error in `main`. The error appeared after merging https://github.com/DataDog/datadog-operator/pull/576 . The tests were passing in the PR but broke `main`.
> [datadogagent/finalizer] Add missing arg in Dependencies()

- apis/datadoghq/v2alpha1/datadogagent_types.go
- config/crd/bases/v1/datadoghq.com_datadogagents.yaml
- config/crd/bases/v1beta1/datadoghq.com_datadogagents.yaml
- controllers/datadogagent/controller_reconcile_v2_common.go
Small updates to v2alpha1 DatadogAgent status
> update v2 status

- pkg/defaulting/images.go
* Default Agent image to `7.39.0`.
* Default Cluster-Agent image to `7.39.0`. Cluster-Agent versioning is now aligned with the Agent.
Keep agent version up-to-date
N/A
It has been already tested during the Datadog-Agent 7.39.0 QA with the last Operator release 0.8.1.
steps:
* create a DatadogAgent without specifying the Agent, ClusterAgent and ClusterCheckRunner image tag.
* check if the Daemonset and Deployments are using the 7.39.0 version
> Default Agent and Cluster-Agent image to 7.39.0

- .gitlab-ci.yml
- Dockerfile
- check-operator.Dockerfile
- go.mod
Address https://github.com/advisories/GHSA-69cg-p879-7622
Make sure this log line is observed on startup:
`{"level":"INFO","ts":"2022-09-14T02:21:11Z","logger":"setup","msg":"Go Version: go1.18.6"}`
> update golang version to 1.18.6

- pkg/controller/utils/datadog/metrics_forwarder.go
Adds a missing nil check in the metrics forwarder.
Enabling metrics forwarder with V2 without providing a cluster name resulted in a panic.
Shouldn't panic.
> [metrics_forwarder] Add missing nil check in setupV2

- apis/datadoghq/v1alpha1/utils.go
- apis/datadoghq/v2alpha1/utils.go
- controllers/datadogagent/agent.go
- controllers/datadogagent/feature/apm/feature.go
- controllers/datadogagent/feature/clusterchecks/feature.go
Add a couple of the missing feature-specific kubernetes and cilium network policies from operator v1. The external metrics provider policies are still TODO since that feature hasn't been implemented yet.
Enable APM (with hostport) and/or cluster checks with a network policy. Example spec section:
```yaml
spec:
global:
networkPolicy:
create: true
flavor: kubernetes
features:
apm:
enabled: true
hostPortConfig:
enabled: true
clusterChecks:
enabled: true
useClusterChecksRunners: true
```
> Add feature-specific network policies

- apis/datadoghq/v1alpha1/datadogagent_conversion.go
Without this, the conversion of v1alpha1 to v2alpha1 is not fully working, the apiserver will return:
```
0920 22:10:47.131288       1 watcher.go:327] failed to prepare current and previous objects: conversion webhook for datadoghq.com/v2alpha1, Kind=DatadogAgent returned invalid object: must have the same name: datadog !=
```
Support converting v1 to v2.
> Fix conversion from v1 to v2

- controllers/datadogagent/systemprobe.go
Updates system-probe seccomp profile with latest changes.
> Update system-probe seccomp profile

- apis/datadoghq/v1alpha1/datadogagent_conversion.go
- apis/datadoghq/v1alpha1/testdata/all.expected.yaml
- controllers/datadogagent/clusteragent.go
Without this fix, converting a v1 to v2 when using a custom conf file will block the deployment of the cluster agent with the following message:
```
Warning  Failed     25m (x4 over 26m)    kubelet            Error: failed to create containerd task: failed to create shim task: OCI runtime create failed: runc create failed: unable to start container process: error during container init: error mounting "/var/lib/kubelet/pods/ed3b360b-8f77-40bf-90b5-88aff9460358/volumes/kubernetes.io~configmap/custom-datadog-yaml" to rootfs at "/etc/datadog-agent/datadog.yaml": mount /var/lib/kubelet/pods/ed3b360b-8f77-40bf-90b5-88aff9460358/volumes/kubernetes.io~configmap/custom-datadog-yaml:/etc/datadog-agent/datadog.yaml (via /proc/self/fd/6), flags: 0x5001: not a directory: unknown
```
This is because …
> Fixing subpath custom conf

- controllers/datadogagent/controller.go
- controllers/datadogagent_controller_v2_test.go
- controllers/testutils/agent.go
* Register OTLP feature
* Add integration tests for OTLP
N/A
> [feature] Register OTLP feature and add integration tests

- pkg/defaulting/images.go
> [defaulting/images] Update agents to 7.39.2

- .gitlab-ci.yml
Attempt to fix this CI error for the `build_operator_check_image_amd64` job:
```
$ if [ -n "$CI_COMMIT_TAG" ]; then docker tag $TARGET_IMAGE $RELEASE_IMAGE && docker push $RELEASE_IMAGE; fi
Error parsing reference: "DOCKER_REGISTRY/datadog-operator-check:v1.0.0-rc.1-amd64" is not a valid repository/tag: invalid reference format: repository name must be lowercase
```
> Fix ci failure for build_operator_check_image_amd64

- controllers/datadogagent/component/agent/default.go
- controllers/datadogagent/component/utils.go
the init config container does not have access to the auth volume to communicate with the agent.
The correct config is to have the agent and the init config have RW access and the other containers have RO.
Otherwise you see:
```
Error: Error while starting api server, exiting: error writing authentication token file on fs: open /etc/datadog-agent/auth/token: read-only file system
```
Make sure the containers are not restarted.
> Fix volume mount to have auth token for agent

- controllers/datadogagent/feature/logcollection/feature.go
- controllers/datadogagent/feature/logcollection/feature_test.go
When using a custom host path for some of the log collection options, the volumemount paths were also being changed when they should consistently be in the same locations inside the agent container.
Match the helm chart implementation: 
* https://github.com/DataDog/helm-charts/blob/54ea81fbbc88562a2258303ada98b8fde69be5f2/charts/datadog/templates/_daemonset-volumes-linux.yaml#L156-L171
* https://github.com/DataDog/helm-charts/blob/54ea81fbbc88562a2258303ada98b8fde69be5f2/charts/datadog/templates/_container-agent.yaml#L188-L204
> [feature] Fix log volumemounts

- pkg/defaulting/images.go
> [defaulting/images] Update agents to 7.40.0

- apis/datadoghq/v1alpha1/datadogagent_conversion_agent.go
- apis/datadoghq/v1alpha1/testdata/all.yaml
v1alpha1 expects a `secCompProfileName` of something like `localhost/system-probe` whereas v2alpha1 would expect that to be split out in the securitycontext into `Type: Localhost` and `LocalhostProfile: system-probe`. The conversion wasn't splitting the v1alpha1 name properly
> Fix seccomp conversion

- pkg/defaulting/images.go
> [defaulting/images] Update agents to 7.40.1

- apis/datadoghq/v2alpha1/datadogagent_default.go
- apis/datadoghq/v2alpha1/datadogagent_default_test.go
Fixes a panic when using a configuration that sets a field for the clusterChecks feature without setting the "enabled" one:
```
features:
clusterChecks:
useClusterChecksRunners: false
```
This is the panic:
```
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x0 pc=0xe6e844]
goroutine 401 [running]:
github.com/DataDog/datadog-operator/apis/datadoghq/v2alpha1.defaultFeaturesConfig(0x400044bb38)
/workspace/apis/datadoghq/v2alpha1/datadogagent_default.go:271 +0xec4
github.com/DataDog/datadog-operator/apis/datadoghq/v2alpha1.DefaultDatadogAgent(0x400044b340?)
/workspace/apis/datadoghq/v2alpha1/datadogagent_default.go:90 +0x34
github.com/DataDog/datadog-operator/controllers/datadogagent.(*Reconciler).internalReconcile …
```
> [v2alpha1/default] Default Features.ClusterChecks.Enabled if unset

- apis/datadoghq/common/v1/types.go
- controllers/datadogagent/feature/oomkill/feature.go
- controllers/datadogagent/feature/tcpqueuelength/feature.go
- controllers/datadogagent/merger/envvars.go
- controllers/datadogagent/merger/fake/envvar_manager.go
Make the `DD_SYSTEM_PROBE_CONFIG_ENABLE_OOM_KILL` and `DD_SYSTEM_PROBE_CONFIG_ENABLE_TCP_QUEUE_LENGTH` environment variable available in the `init-config` init container.
The [`Dockerfiles/agent/cont-init.d/60-sysprobe-check.sh`](https://github.com/DataDog/datadog-agent/blob/main/Dockerfiles/agent/cont-init.d/60-sysprobe-check.sh) script needs to access the system-probe configuration in order to enable the core agent part of the `oom_kill` and `tcp_queue_length` checks.
This change also requires an agent that has DataDog/datadog-agent#14332.
Start a datadog agent with a manifest like:
```yaml
metadata:
name: datadog
spec:
global:
credentials:
apiSecret:
appSecret: …
```
> Expose the `…ENABLE_OOM_KILL` and `…TCP_QUEUE_LENGTH` env vars to the `init-config` container

- .github/workflows/main.yml
- Makefile
Fixes the codecov reporting by using a different report file for each kind of test.
Codecov reporting was broken because both the v1 integration tests and the unit tests were exporting their results to `cover.out`. When running `make test`, which is what we use in the Github CI, the v1 integration tests run after the unit ones, so their results are overridden.
> [github/workflows/main] Fix codecov reporting

- Makefile
Updates the k8s version used by `envtest` to 1.24.
`envtest` with 1.20 doesn't work on M1s:
```
unable to find a version that was supported for platform darwin/arm64
```
1.24 instead of 1.25 because the known issue about the Operator not working properly on 1.25.
`make integration-tests-v2` should work on M1s.
> [Makefile] Update envtest k8s version to 1.24

- controllers/datadogagent/feature/oomkill/feature.go
- controllers/datadogagent/feature/oomkill/feature_test.go
- controllers/datadogagent/feature/tcpqueuelength/feature.go
- controllers/datadogagent/feature/tcpqueuelength/feature_test.go
Share the system-probe socket with the core agent when the `oom_kill` or `tcp_queue_length` checks are enabled.
This is a followup of #642 to fix the activation of `oom_kill` and `tcp_queue_length` checks.
Start a datadog agent with a manifest like:
```yaml
metadata:
name: datadog
spec:
global:
credentials:
apiSecret:
appSecret:
keyName: app-key
features:
oomKill:
enabled: true
tcpQueueLength:
enabled: true
```
and an agent version that contains DataDog/datadog-agent#14332 and check that the `oom_kill` and `tcp_queue_length` checks are correctly scheduled in the core agent.
> Share the system-probe socket when `oom_kill` or `tcp_queue_length` checks are enabled

- apis/datadoghq/v1alpha1/datadogmonitor_types.go
- apis/datadoghq/v1alpha1/zz_generated.deepcopy.go
- bundle/manifests/datadoghq.com_datadogmonitors.yaml
- config/crd/bases/v1/datadoghq.com_datadogmonitors.yaml
- config/crd/bases/v1beta1/datadoghq.com_datadogmonitors.yaml
- controllers/datadogmonitor/monitor.go
- controllers/datadogmonitor/monitor_test.go
- examples/datadogmonitor/audit-alert-monitor-test.yaml
- examples/datadogmonitor/event-alert-monitor-test.yaml
- examples/datadogmonitor/event-v2-alert-monitor-test.yaml
- examples/datadogmonitor/log-alert-monitor-test.yaml
- examples/datadogmonitor/metric-monitor-test.yaml
- examples/datadogmonitor/process-alert-monitor-test.yaml
- examples/datadogmonitor/rum-alert-monitor-test.yaml
- examples/datadogmonitor/service-check-monitor-test.yaml
- examples/datadogmonitor/slo-alert-monitor-test.yaml
- examples/datadogmonitor/trace-analytics-alert-monitor-test.yaml
Updates the use of the now [deprecated](https://github.com/DataDog/datadog-api-client-go/blob/ac14372d2bc7820a099fecb2e29d78ec92d47575/api/v1/datadog/model_monitor_options.go#L57-L58) `newHostDelay` to the new `newGroupDelay` 
fixes #525 
newHostDelay is deprecated and ignored by the api, so alerts are currently triggered on new hosts even with this set
N/A
> fix: replace deprecated newHostDelay with newGroupDelay

- controllers/datadogagent/feature/otlp/feature.go
Disables the OTLP feature when not explicitly enabled. Previously, the operator logs showed the feature as enabled when `features.otlp.*` wasn't set in the manifest:
```
{"level":"INFO","ts":"2022-11-22T15:58:56Z","logger":"controllers.DatadogAgent","msg":"Reconciling DatadogAgent","datadogagent":"default/datadog"}
...
{"level":"INFO","ts":"2022-11-22T15:58:56Z","logger":"controllers.DatadogAgent","msg":"Dependency ManageDependencies","datadogagent":"default/datadog","featureID":"otlp"}
```
> Disable otlp feature by default

- apis/datadoghq/common/common.go
- apis/datadoghq/common/common_test.go
- controllers/datadogagent/override/podtemplatespec.go
- controllers/datadogagent/override/podtemplatespec_test.go
Proposes a fix for an issue report in this Slack message - summarizing below.
When `override.nodeAgent.image` isn't fully provided the image URI in agent pod/deployment is corrupt. 
For
```
override:
nodeAgent:
image:
tag: 7.41.0-rc.5
```
Generated image URI is
```
image: gcr.io/datadoghq/:7.41.0-rc.5
```
Same happens with DCA and CCR as well.
Fix will allow users to provide only partial overrides and use previuos defaults.
n/a
* Added unit test for missing scenarios.
* Tested locally with default operator setup and combinations of overrides, making sure final image URI is as expected.
> Fix to handle partial image overrides input correctly

- apis/datadoghq/v2alpha1/datadogagent_default.go
- controllers/datadogagent/feature/orchestratorexplorer/configmap.go
- controllers/datadogagent/feature/orchestratorexplorer/configmap_test.go
- controllers/datadogagent/feature/orchestratorexplorer/feature.go
- Clear up the internal struct for the Orchestrator Explorer. 
- Fix the default so that the feature runs on the Cluster Agent by default and not on the Cluster Check Runners.
- Cluster Check Runners are not enabled by default anymore.
Fix the feature to be aligned with the helm default.
> Disabling OE running on CLCR by default

- controllers/datadogagent/feature/dogstatsd/feature.go
- controllers/datadogagent/feature/dogstatsd/feature_test.go
In the core agent the UDS needs to be mounted as RW.
```
2022-11-15 23:38:00 UTC | CORE | ERROR | (pkg/dogstatsd/server.go:269 in NewServer) | can't listen: listen unixgram /var/run/datadog/statsd/dsd.socket: bind: read-only file system
```
As is the case for v1 https://github.com/DataDog/datadog-operator/blob/main/controllers/datadogagent/utils.go#L1440
(note that for other containers we have RO, e.g. [process-agent](https://github.com/DataDog/datadog-operator/blob/main/controllers/datadogagent/utils.go#L1570)).
Fix DSD feature with UDS.
> Fixing ReadWrite access on UDS in core agent

- controllers/datadogagent/component/agent/default.go
Sister change in the helm chart https://github.com/DataDog/helm-charts/pull/803
```
Mounts:
/etc/datadog-agent from config (rw)
/etc/datadog-agent/auth from datadog-agent-auth (ro)
/host/var/run from runtimesocketdir (ro)
/var/log/datadog from logdatadog (rw)
/var/run/datadog/apm from apmsocket (rw)
/var/run/datadog/statsd from dsdsocket (ro)
/var/run/secrets/kubernetes.io/serviceaccount from kube-api-access-gp868 (ro)
```
After
```
Mounts:
/etc/datadog-agent from config (rw)
/etc/datadog-agent/auth from datadog-agent-auth (ro)
/host/proc from procdir (ro)
/host/sys/fs/cgroup from cgroups (ro)
/host/var/run from runtimesocketdir (ro)
/var/log/datadog from logdatadog (rw)
/var/run/datadog/apm from apmsocket (rw)
/var/run/datadog/statsd from dsdsocket (ro) …
```
> Adding volumeMounts for APM tagging

- pkg/controller/utils/datadog/metrics_forwarder.go
Without corresponding changes in the backend, using the datadog_operator source results in the events to be considered as custom.
The Event team recommended we switch to the `datadog` source type. 
Recommendation from the Event Pipeline team.
> Change event type to be datadog instead of datadog_operator

- controllers/datadogagent/override/podtemplatespec.go
- controllers/datadogagent/override/podtemplatespec_test.go
Env vars with a format of `{name: NAME, valueFrom: ...}` weren't being set correctly in the pod overrides.
> Fix valuefrom envvar pod overrides

- controllers/datadogagent/dependencies/store.go
- controllers/datadogagent/feature/externalmetrics/feature.go
- controllers/datadogagent/merger/rbac.go
When enabling the external metrics provider feature, a rolebinding is placed in the wrong namespace if the DDA is created in a namespace other than `kube-system` because the `extension-apiserver-authentication-reader` role referenced in the rolebinding is in the `kube-system` namespace. Operator error:
```json
{"level":"ERROR","ts":"2022-12-05T19:07:56Z","logger":"controllers.DatadogAgent","msg":"dependencies.store Create","datadogagent":"default/datadog-agent","obj.namespace":"default","obj.name":"datadog-agent-cluster-agent-apiserver","error":"roles.rbac.authorization.k8s.io \"extension-apiserver-authentication-reader\" not found"}
```
The owner-reference also needs to be removed because cross-namespace ownership isn't allowed: …
> Move external metrics rolebinding to kube-system namespace

- pkg/defaulting/images.go
* Default Agent image to `7.41.1`.
* Default Cluster-Agent image to `7.41.1`. Cluster-Agent versioning is now aligned with the Agent.
Keep agent version up-to-date
This PR can be cherry-pick on the `v0.8` branch.
testing has been done during the Datadog-Agent QA
> Default Agent|Cluster-Agent to 7.41.1

- controllers/datadogagent/feature/npm/feature.go
- controllers/datadogagent/feature/npm/feature_test.go
NPM options collectDNSStats  and enableConntrackare not taken into account (converted as env vars), so we rely on the sys probe behavior, which will enable both if they are not configured. Unfortunately:
```
features:
npm:
collectDNSStats: false
enableConntrack: false
enabled: true 
```
will result in both of them turned on.
> Ensure all fields are taken into account with NPM

- apis/datadoghq/common/const.go
- apis/datadoghq/common/v1/types.go
- apis/datadoghq/v2alpha1/datadogagent_default.go
- apis/datadoghq/v2alpha1/datadogagent_default_test.go
- controllers/datadogagent/component/utils.go
- controllers/datadogagent/feature/apm/feature.go
- controllers/datadogagent/feature/apm/feature_test.go
- controllers/datadogagent/feature/dogstatsd/feature.go
- controllers/datadogagent/feature/dogstatsd/feature_test.go
- controllers/datadogagent/utils.go
```
spec:
features:
admissionController:
enabled: true
apm:
enabled: true
dogstatsd:
originDetectionEnabled: true
unixDomainSocketConfig:
enabled: true
path: /var/run/datadog-agent/statsd.sock
```
yields:
```
Containers:
agent:
[...]
DD_DOGSTATSD_SOCKET:                       /var/run/datadog/statsd/statsd.sock
[...]
/var/run/datadog/statsd from dsdsocket (rw)
[...]
trace-agent:
[...]
DD_APM_RECEIVER_SOCKET:                    /var/run/datadog/apm/apm.socket
DD_DOGSTATSD_SOCKET:                       /var/run/datadog/statsd/statsd.sock
[...]
/var/run/datadog/apm from apmsocket (rw)
/var/run/datadog/statsd from dsdsocket (ro)
[...]
dsdsocket:
Type:          HostPath (bare host directory volume)
Path:          /var/run/datadog-agent
HostPathType:  DirectoryOrCreate
apmsocket:
Type: …
```
> Fixing the defaulting and support of the udsHostFilePath

- apis/datadoghq/v2alpha1/datadogagent_default.go
- apis/datadoghq/v2alpha1/datadogagent_default_test.go
Fix `panic: runtime error: invalid memory address or nil pointer dereference` with the following configuration:
```yaml
features:
admissionController:
mutateUnlabelled: true
agentCommunicationMode: socket
```
> Fix admission controller default settings panic

- Makefile
To release the bundle on an ARM machine, operator SDK needs to be updated, otherwise we get:
```
bin/Darwin-arm64/operator-sdk generate kustomize manifests -q
bin/Darwin-arm64/operator-sdk: line 1: Not: command not found
```
with this update:
```
[...]
INFO[0000] Creating bundle.Dockerfile
INFO[0000] Creating bundle/metadata/annotations.yaml
INFO[0000] Bundle metadata generated suceessfully
hack/patch-bundle.sh
bin/Darwin-arm64/operator-sdk bundle validate ./bundle
[...]
INFO[0000] All validation tests have completed successfully
```
Smoother release process.
> Operator SDK only supports arm starting on 1.23

- controllers/datadogagent/orchestrator.go
- controllers/datadogagent/testdata/orchestrator_clusterrole.yaml
Merging #685 broke v1 controller when orchestrator explorer is enabled, removing redundant verb.
> Remove Get verb from Orchestrator Explorer RBAC

- controllers/datadogagent/dependencies/store.go
- pkg/kubernetes/const.go
- pkg/kubernetes/platforminfo.go
- pkg/kubernetes/platforminfo_test.go
This change addresses the Kubernetes 1.25 compatibility issue caused by Operator attempting to handle `PodDisruptionPolicy` resource not available in aforementioned version. 
Operator 1.0.0 deployed on v1.25 would log following error on every reconcile
```
{"level":"ERROR","ts":"2023-01-17T21:19:23Z","logger":"controller.datadogagent","msg":"Reconciler error","reconciler group":"datadoghq.com","reconciler kind":"DatadogAgent","name":"datadog","namespace":"system","error":"no matches for kind \"PodSecurityPolicy\" in version \"policy/v1beta1\"","errorCauses":[{"error":"no matches for kind \"PodSecurityPolicy\" in version \"policy/v1beta1\""}]}
```
Make Operator 1.0.0 run on v1.25.
This change ***does not*** solve PSP usage across Operator. 
PSP resource isn't utilized/implemented (see …
> Avoid PodSecurityPolicy cleanup if the resource is not supported by Kubernetes API

- controllers/datadogagent/dependencies/store.go
- controllers/datadogagent/feature/kubernetesstatecore/configmap.go
- controllers/datadogagent/feature/kubernetesstatecore/configmap_test.go
- controllers/datadogagent/feature/kubernetesstatecore/feature.go
- pkg/kubernetes/platforminfo.go
Adds vpa collector to ksm core if vpas are a supported resource:
```
$ kubectl exec -it datadog-cluster-agent-xxxxxxxxxx-xxxxx -- cat /etc/datadog-agent/conf.d/kubernetes_state_core.d/kubernetes_state_core.yaml.default
---
cluster_check: false
init_config:
instances:
- telemetry: true
skip_leader_election: false
collectors:
- pods
...
- ingresses
- verticalpodautoscalers
```
> Add vpa config to ksm core

- .devcontainer/devcontainer.json
- Dockerfile
* Add vscode devcontainer configuration
* Update golang version to 1.19 (no issue detected during my test)
It ease development environment setup, and enforce that every developer use
the same environment.
I have tested most of the `makefile` commands in the container. Everything worked well.
To test, just use it :)
if you are already using vscode. a pop-up should appear on the bottom right, to reopen the envirnement
in a container. Just clik `yes`.
> Add devcontainer vscode config

- apis/datadoghq/v1alpha1/datadogagent_conversion_dca.go
- apis/datadoghq/v1alpha1/testdata/all.expected.yaml
- apis/datadoghq/v1alpha1/testdata/all.yaml
- apis/datadoghq/v2alpha1/datadogagent_types.go
Upon converting v1alpha1 with a customConfig for the cluster agent, the file should be `datadog-cluster.yaml` so that it's properly processed by the binary.
currently we have:
```
volumes:
- configMap:
defaultMode: 420
items:
- key: datadog-cluster.yaml
path: datadog-cluster.yaml
name: datadog-cluster-agent-custom-cm
name: volume-custom-cluster-agent
...
volumeMounts:
- mountPath: /etc/datadog-agent/datadog.yaml
name: volume-custom-cluster-agent
readOnly: true
subPath: datadog.yaml
```
with the wrong subPath.
leading to the /etc/datadog-agent/datadog.yaml being a directory since it's empty.
```
root@datadog-cluster-agent-56885cc567-bhmgm:/# cat /etc/datadog-agent/datadog.yaml
cat: /etc/datadog-agent/datadog.yaml/: Is a directory
```
Fix edge case of migration.
Anything else we should know …
> Fixing name of custom conf file mounted in DCA during migration

- controllers/datadogagent/controller_test.go
- controllers/datadogagent_controller.go
- pkg/controller/utils/datadog/forwarders_manager.go
- pkg/controller/utils/datadog/metrics_forwarder.go
- pkg/controller/utils/datadog/metrics_forwarder_test.go
- pkg/kubernetes/platforminfo.go
- pkg/kubernetes/platforminfo_test.go
Adds `DatadogAgent` custom resource version tags to reconcile metrics (in the `metrics_forwarder.go`. As a result `datadog.operator.reconcile.success` (among others) will have two new tags eg. `cr_other_version:datadoghq.com/v1alpha1` and `cr_preferred_version:datadoghq.com/v2alpha1` for v1.0 with `v2alpha1`.  If there is no 'other' (single version stored and served) version it will have a value `null`.
Visibility in the `v2alpha1` adoption.
Tested using locally running cluster, confirmed tags appear in the app.
> Add DatadogAgent CR version tags to reconcile metrics

- pkg/defaulting/images.go
> [defaulting/images] Update agents to 7.43.0

- controllers/datadogagent/override/podtemplatespec.go
Annotation key is missing the Component name, leading to:
```
{"level":"ERROR","ts":"2023-03-01T22:23:05Z","logger":"controller.datadogagent","msg":"Reconciler error","reconciler group":"datadoghq.com","reconciler kind":"DatadogAgent","name":"datadog-agent","namespace":"datadog-agent","error":"Deployment.apps \"datadog-cluster-agent\" is invalid: spec.template.annotations: Invalid value: \"checksum/%s-extra-confd-custom-config\": name part must consist of alphanumeric characters, '-', '_' or '.', and must start and end with an alphanumeric character (e.g. 'MyName',  or 'my.name',  or '123-abc', regex used for validation is '([A-Za-z0-9][-A-Za-z0-9_.]*)?[A-Za-z0-9]')"}
```
bugfix
Write there any instructions and details you may have to test your …
> Fix annotation key form MD5 annotation

- .gitlab-ci.yml
Update the docker image used in the CI (gitlab) to use a more recent image that still exist in the registry. The new image should also be a multi-arch image
the current docker image was removed from the registry.
The CI (gitlab) should be green
> fix: docker image in gitlab-ci

- controllers/datadogagent/clusteragent_test.go
- controllers/datadogagent/clusterchecksrunner_test.go
- controllers/datadogagent/merger/security_context.go
- controllers/datadogagent/merger/security_context_test.go
This PR introduce the function ` SortAndUnique(in []corev1.Capability) []corev1.Capability` and use it in `AddCapabilitiesToContainer(...)` to create a valid `SecurityContext`
Before this pull request, if several features needed the same capabilities, they were duplicated in the `securityContext.capabilities.add` section.
example of previous behaviour
```yaml
securityContext:
capabilities:
add:
- SYS_ADMIN
- SYS_RESOURCE
- SYS_PTRACE
- NET_ADMIN
- NET_BROADCAST
- NET_RAW
- IPC_LOCK
- CHOWN
- DAC_READ_SEARCH
- SYS_ADMIN
- SYS_RESOURCE
- SYS_PTRACE
- NET_ADMIN
- NET_BROADCAST
- NET_RAW
- IPC_LOCK
- CHOWN
- DAC_READ_SEARCH
- SYS_ADMIN
- SYS_RESOURCE
- SYS_PTRACE
- NET_ADMIN
- NET_BROADCAST
- NET_RAW
- IPC_LOCK
- CHOWN
- DAC_READ_SEARCH
- SYS_ADMIN
- SYS_RESOURCE
- SYS_PTRACE
- NET_ADMIN
- …
```
> fix: make capability unique in securityContext

- pkg/defaulting/images.go
Update datadog `agent` and `cluster-agent` default version to `7.43.1`.
https://github.com/DataDog/datadog-agent/releases/tag/7.43.1
Check which version of the agent is deployed by default.
> [defaulting/images] Update agents to 7.43.1

- controllers/datadogagent/utils.go
mount the `datadog.yaml` file in system-probe container if the user set a custom datadog.yaml config file.
ease migration Operator v1.0.0
create a DatadogAgent with a custom datadog.yaml configuration
> feat: mount custom datadog.yaml in system-probe

- main.go
#731 left a changed `datadogMonitorEnabled` flag, this PR resets it to the old value.
> Change datadogMonitorEnabled to false, incorrectly set in #731

- apis/datadoghq/v1alpha1/datadogagent_conversion.go
- apis/datadoghq/v1alpha1/testdata/all.expected.yaml
- apis/datadoghq/v1alpha1/testdata/all.yaml
- controllers/datadogagent/feature/enabledefault/feature.go
- controllers/datadogagent/feature/externalmetrics/feature.go
- controllers/datadogagent/merger/secret.go
- controllers/datadogagent/merger/secret_test.go
At the moment, if a token is specified to authenticate the communication between the Datadog Agents and the Datadog Cluster Agent resources will not be rotated if it is changed. This can result in communication errors following up on the upadte of the token.
Secondly, this also adds supports for the conversion of the token when migrating from v1alpha1 to v2alpha1.
This uses the MD5 hashing pattern introduced for Lifecycle improvement.
Ensuring smooth migration.
Deploying:
```
metadata:
name: datadog
namespace: default
spec:
global:
clusterAgentToken: abc123 # Make sure it's 32 characters
```
should result in the creation of the secret with the config hash for the token:
```
apiVersion: v1 …
```
> Cluster Agent Auth Lifecycle Improvment

- docs/custom_check.md
In `v2alpha1` version of the `DatadogAgent` resource the volume mounts are per container, not per pod.
This PR fixes the example
I was trying out the Operator GA and this example failed.
> Fix volume mounts example

- main.go
Fixes missing int pointer dereference when formatting error.
Customer reporting log line with `“too much goroutines: 466 > limit: 824634953576"` 
> Fix goroutines error formatting

- controllers/datadogagent/controller_reconcile_v2.go
- controllers/testutils/agent.go
- pkg/controller/utils/datadog/metrics_forwarder.go
- pkg/controller/utils/datadog/metrics_forwarder_test.go
Adds a check to avoid segmentation violation when looking up credentials during `metrics_forwarder` registration. 
Also skips reconciling `DatadogAgent` if credentials are missing.
From the current behavior of CLB and nothing happening, we will get:
* Operator retrying to get the credentials from `DatadogAgent` and register `metrics_forwarder` once credentials are present. 
* ~~Operator will create agent deployments but since they need same credentials, they will not function properly.~~
* Operator will run and log info from `metrics_forwarder` errors from the reconciler.
https://github.com/DataDog/datadog-operator/issues/662, and few other Github mentions of the issue. 
* Added unit test when credentials are missing.
* Locally tested scenario …
> Fix segfault to prevent Operator crash when credentials are missing in DDA

- apis/datadoghq/v1alpha1/datadogagent_conversion_agent.go
- apis/datadoghq/v1alpha1/testdata/all.expected.yaml
This PR updates the conversion logic for DatadogAgent to account for `.Config.hostPort` being set, and if set to set `.Features.Dogstatsd.HostPortConfig.HostPort` accordingly.
I created this PR after converting my manifests and noticing that there was no hostPort configuration being converted. This led to my agents no longer being able to receive any metrics.
My original v1alpha1/datadogagent manifest looked like this:
<details><summary>Details</summary>
<p>
```yaml
metadata:
name: datadog
namespace: datadog
spec:
site: datadoghq.eu
credentials:
apiKey: asdf
appKey: asdf
features:
logCollection:
enabled: true
logsConfigContainerCollectAll: true
networkMonitoring:
enabled: true
enabled: true
agent:
image:
name: …
```
> Address Dogstatsd HostPort configuration not being converted by the webhook

- controllers/datadogagent/feature/externalmetrics/feature.go
- controllers/datadogagent/feature/externalmetrics/feature_test.go
The external metrics provider secret for credentials wasn't being created when an API/APP key was provided that wasn't part of an existing secret. The following example would previously cause the DCA to CLBO with `Error: secret "datadog-metrics-server" not found`:
```yaml
externalMetricsServer:
enabled: true
endpoint:
credentials:
apiKey: "test"
```
---
The same config should now create a secret containing the api key:
```
> kubectl describe secret datadog-metrics-server
Name:         datadog-metrics-server
Namespace:    default
Labels:       app.kubernetes.io/instance=datadog
app.kubernetes.io/managed-by=datadog-operator
app.kubernetes.io/name=datadog-agent-deployment
app.kubernetes.io/part-of=default-datadog
app.kubernetes.io/version=
operator.datadoghq.com/managed-by-store=true …
```
> [feature] Create secret for external metrics creds when not using existing secret

- .golangci.toml
- Makefile
- controllers/datadogagent/clusteragent.go
- controllers/datadogagent/clusterchecksrunner.go
- controllers/datadogagent/common_configmap.go
- controllers/datadogagent/feature/types.go
- controllers/datadogagent/poddisruptionbudget.go
- controllers/datadogagent/secret.go
- controllers/datadogagent/testutils/metadata_utils.go
- controllers/datadogagent/testutils/podtemplate_utils.go
- pkg/controller/utils/datadog/forwarders_manager.go
- pkg/plugin/common/client.go
- pkg/secrets/types.go
Update golangci-lint to 1.51.0 because it is incompatible with go1.20 
Remove related warnings and fix lint issues from new linter in version update
Unblock folks on golang1.20
> Update golangci-lint version to 1.51.0 and fix related issues

- LICENSE-3rdparty.csv
- controllers/suite_test.go
- controllers/suite_v2_test.go
`envtest/printer` is removed in `sigs.k8s.io/controller-runtime v0.14.0`, we are on `v0.11.2` but dependency on this package impacts some shared package builds. 
Replaced the `printer` with a default `Reporter` from Ginkgo. I didn't see noticeable difference in test output so not certain if I was looking at the right place.
> Remove envtest/printer package dependency

- controllers/datadogagent/component/agent/default.go
Add `memfd_create` to system-probe seccomp policy
Needed for runtime compilation sealed memfd feature from https://github.com/DataDog/datadog-agent/pull/15726
> Add memfd_create to system-probe seccomp policy

- main.go
Configure a controller manager name, `datadog-operator` for the `manager` managedField. 
Previously, the `DatadogAgent` resource created by the datadog-operator had the managed field, `Manager: manager`, which was ambiguous and confusing. 
```
Name: datadog
[...]
API Version:  datadoghq.com/v2alpha1
Kind:         DatadogAgent
Metadata:
[...]
Managed Fields:
[...]
Manager:      manager
[...]
Manager:      manager
```
This change customizes the `Manager` name to a more meaningful name, `datadog-operator`. 
```
[...]
Name: datadog
API Version:  datadoghq.com/v2alpha1
Kind:         DatadogAgent
Metadata:
[...]
Managed Fields:
[...]
Manager:      datadog-operator
[...]
Manager:      datadog-operator
```
This change also updates the `manager` field for the `DatadogMonitor` resource to …
> Update manager managed field

- pkg/defaulting/images.go
Default `Agent` and `Cluster-Agent` image tag to `7.44.0`
Deploy the operator and create a DatadogAgent without specifying the Agent and Cluster Agent image tag. 
The operator should deploy the Agent and Cluster-Agent with the image tag 7.44.0
> feat: default agent/dca to 7.44.0

- config/rbac/leader_election_role.yaml
This PR adds `get`, `update` and `patch` permission for `leases/status` to `leaderelection` since we now use leases to store the leader election token.
`leaderelection` now uses leases for the leader election.
https://github.com/DataDog/datadog-agent/pull/16652
N/A
N/A
> [leaderelection][rbac] Add permissions to `leaderelection` for `leases/status`

- controllers/datadogagent/component/clusteragent/default.go
This PR updates RBAC permissions of the leader election to match https://github.com/DataDog/helm-charts/blob/8841bd813540d2acb44eb775b82dab28acd369ab/charts/datadog/templates/cluster-agent-rbac.yaml#L69-L83.
Leader election is broken.
N/A
N/A
> Update `leaderelection` permissions to use `leases`

- controllers/datadogagent/agent.go
- controllers/datadogagent/component/agent/default.go
- controllers/datadogagent/component/agent/new.go
- controllers/datadogagent/component/new.go
- controllers/datadogagent/controller.go
- controllers/datadogagent/controller_reconcile_agent.go
- controllers/datadogagent/controller_test.go
- controllers/datadogagent_controller.go
- controllers/setup.go
- controllers/suite_test.go
- controllers/suite_v2_test.go
- main.go
With v2alpha1.DatadogAgent CRD, ExtendedDaemonset configuration is
not present on purpose, to allow sunseting EDS support maybe later.
This PR allow to configure EDS.spec.stragy thanks to Operator global
settings.
With v2alpha1.DatadogAgent CRD, ExtendedDaemonset configuration is
not present on purpose, to allow sunseting EDS support maybe later.
test the Operator new command line options when `-supportExtendedDaemonset true`.
The options value should be visible in the created `ExtendedDaemonset.spec.strategy`
```
-eds-canary-auto-fail-restart-count int
ExtendedDaemonset canary auto fail restart count
-eds-canary-auto-pause-restart-count int
ExtendedDaemonset canary auto pause restart count
-eds-canary-duration duration
ExtendedDaemonset canary …
```
> feat(v2): support EDS.spec.strategy configuration

- Makefile
Update channel to `stable` for bundle images
Should be `stable` following 1.x release
Run `make bundle` and ensure that the clusterserviceversion shows the channel as `stable`
> update channel to stable for bundle images

- main.go
Attempting to set a flag twice was causing the operator to panic:
```
/manager flag redefined: logEncoder
panic: /manager flag redefined: logEncoder
```
Removed duplicates
> Remove duplicate flags

- pkg/defaulting/images.go
Default `Agent` and `Cluster-Agent` image tag to `7.45.0`
Deploy the operator and create a DatadogAgent without specifying the Agent and Cluster Agent image tag. 
The operator should deploy the Agent and Cluster-Agent with the image tag 7.45.0
> feat: default agent/dca to 7.45.0

- controllers/datadogagent/feature/externalmetrics/feature.go
This PR makes sure the clusterrolebinding for external metrics is correctly created using `kube-system` as the namespace for the `horizontal-pod-autoscaler` ServiceAccount
My colleagues reported today that HPAs based on External Metrics were no longer working since the upgrade to Datadog Operator 1.0.2.
After some investigation I found that the ClusterRoleBinding for `datadog-cluster-agent-metrics-reader` looked like this: 
<details><summary>datadog-cluster-agent-metrics-reader</summary>
<p>
```yaml
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
creationTimestamp: "2023-04-24T15:55:32Z"
labels:
app.kubernetes.io/instance: datadog
app.kubernetes.io/managed-by: datadog-operator
app.kubernetes.io/name: datadog-agent-deployment
app.kubernetes.io/part-of: …
```
> Use kube-system namespace for clusterrolebinding reference to horizontal-pod-autoscaler service account

- apis/datadoghq/v1alpha1/datadogmonitor_types.go
- apis/datadoghq/v1alpha1/zz_generated.deepcopy.go
- config/crd/bases/v1/datadoghq.com_datadogmonitors.yaml
- config/crd/bases/v1beta1/datadoghq.com_datadogmonitors.yaml
- controllers/datadogmonitor/controller.go
Add periodic sync (currently defaulted to 1h) of monitor to ensure that definition of API monitor does not drift from DatadogMonitor resource, which is considered the source of truth for Operator-managed monitors.
Refactor code so that if a monitor is deleted, the operator will recreate it.
Rename `SyncStatus*` to `MonitorSyncStatus*` for clarity.
Better user experience
> [datadogmonitor] add periodic forced sync of API monitor

- controllers/datadogagent/override/podtemplatespec.go
- controllers/datadogagent/override/podtemplatespec_test.go
- Fix usage of PullPolicy and PullSecrets options in the v2 component overrides
- Add a struct for use in tests
Bugfix
Test manifests for kind cluster:
```
metadata:
name: datadog
namespace: system
spec:
global:
credentials:
apiKey: redacted
appKey: redacted
kubelet:
override:
nodeAgent:
image:
tag: 7.46.0-rc.3
pullPolicy: Never
pullSecrets:
- name: regcred
```
To create secret:
```
$ kubectl create secret generic regcred \
--from-file=.dockerconfigjson=path/to/docker/config.json \
--type=kubernetes.io/dockerconfigjson
```
`kubectl describe` agent daemonset to see overrides have taken place.
> fix image pullpolicy and pullsecrets overrides

- pkg/defaulting/images.go
Default Agent and Cluster-Agent image tag to 7.46.0
New release is there 🚀 
N/A
Deploy the agent with the default settings. The operator should deploy 7.46.0.
> feat: default agent/dca to 7.46.0

- controllers/datadogagent/controller_reconcile_agent.go
- controllers/datadogagent/controller_reconcile_ccr.go
- controllers/datadogagent/controller_reconcile_dca.go
- controllers/datadogagent/feature/factory.go
- controllers/datadogagent/feature/types.go
- controllers/datadogagent/feature/types_test.go
Add `IsConfigured` to FeatureFactory
Update naming of a few bool variables
Use `IsConfigured` when collating list of features to manage in each component reconciler
An issue arose regarding a feature that needs to be explicitly disabled when it's not enabled, but we didn't fully form the ability to do this with the FeatureFactory. This PR finishes what was started several months ago
Deploy the operator and add a section to one of the features such as this, where an envvar is set when a feature is **disabled** (this example was tested in remote config):
```
} else {
reqComp = feature.RequiredComponents{
Agent: feature.RequiredComponent{
IsRequired: apiutils.NewBoolPointer(false),
Containers: []apicommonv1.AgentContainerName{ …
```
> update feature factory to process feature if disabled but configured

- main.go
Update the conversion webhook to be disabled by default: `webhookEnabled: false`. 
Note: datadog-operator helm chart users using the conversion webhook must upgrade to the latest helm chart. See https://github.com/DataDog/helm-charts/pull/1102.
Migration to DatadogAgent CRD v2alpha1
> Disable conversion webhook by default

- controllers/setup.go
- pkg/config/config.go
- pkg/controller/utils/datadog/metrics_forwarder.go
- pkg/datadogclient/client.go
Add support for site envvar (`DD_SITE`) in the operator controller which can be used to configure client endpoint for DatadogMonitor.
Request/bugfix
Set DD_SITE (something other than datadoghq.com), and corresponding keys DD_API_KEY, and DD_APP_KEY in the Operator deployment. Try creating a DatadogMonitor and check it is created successfully in the corresponding account.
> [datadogmonitor] add support for site envvar

- examples/datadogmonitor/log-alert-monitor-test.yaml
Applying the monitor as is results in the following error:
```
error validating monitor: 400 Bad Request: {"errors":["The new_group_delay option can only be used for multi-alert monitors"]}
```
> fix log monitor example

- controllers/datadogagent/feature/otlp/feature.go
Bug Fix
In the DatadogAgent config there is an option to enable otlp ingestion:
```
otlp:
receiver:
protocols:
grpc:
enabled: true
http:
enabled: true
```
This adds the following two containerPorts to the pod spec:
```
- containerPort: 4317
hostPort: 4317
name: otlpgrpcport
protocol: TCP
- containerPort: 4318
hostPort: 4318
name: otlphttpport
protocol: TCP
```
The problem is that these two ports are only added to the pod spec and not to the service object.
This PR adds the http and grpc ports to the service object if enabled.
> Add grpc port and http port to service when otlp is enabled

- apis/datadoghq/v2alpha1/datadogagent_default.go
- apis/datadoghq/v2alpha1/datadogagent_default_test.go
The orchestrator explorer defaulting panicked with this config:
```yaml
extraTags: ["key1:value1", "key2:value2"]
```
Set a config the orchestrator explorer feature without setting `enabled: true` like in the above example. The operator pod shouldn't panic and the orchestrator explorer check should run without issue
> Fix orchestrator explorer default panic

- controllers/datadogagent/component/agent/new.go
Fixes the operator crashing when using the EDS and not adding canary settings. The EDS defaulting code doesn't create a default `ExtendedDaemonSetSpecStrategyCanary` struct if there are no canary settings set in the EDS spec, so attempting to access `spec.Strategy.Canary.xxx` causes a nil pointer error:
```
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x0 pc=0xf7ed18]
goroutine 515 [running]:
github.com/DataDog/datadog-operator/controllers/datadogagent/component/agent.defaultEDSSpec(_)
/workspace/controllers/datadogagent/component/agent/new.go:88 +0x158
github.com/DataDog/datadog-operator/controllers/datadogagent/component/agent.NewExtendedDaemonset({0x1a9f540, 0x4000656420}, 0x400053f8c0?, {0x17d8d95?, …
```
> Fix EDS canary panic

- apis/datadoghq/common/const.go
- apis/datadoghq/v2alpha1/datadogagent_default.go
- controllers/datadogagent/agent_test.go
- controllers/datadogagent/component/agent/default.go
- controllers/datadogagent/feature/apm/feature.go
- controllers/datadogagent/feature/apm/feature_test.go
- controllers/datadogagent/feature/dogstatsd/feature.go
- controllers/datadogagent/feature/dogstatsd/feature_test.go
- controllers/datadogagent/merger/volume_mount.go
- controllers/datadogagent/utils_test.go
Updates the Dogstatsd and APM socket paths when mounted in containers.
Gracefully handle expected conflict of volume mounts using merge functions in the volume mount manager
A bug was surfaced that occurs when the Admission Controller is enabled (with `muteUnlabelled: true`) and when Dogstatsd UDS is enabled (which it is by default) that caused CLB during container initiation.
Test a DatadogAgent with the following:
```
metadata:
name: datadog
namespace: system
spec:
global:
credentials:
apiKey: <redacted>
appKey: <redacted>
kubelet:
features:
admissionController:
enabled: true
mutateUnlabelled: true
```
Also test:
``` …
```
> update dsd and apm socket paths

- apis/datadoghq/common/envvar.go
- controllers/datadogagent/clusteragent.go
- controllers/datadogagent/clusteragent_test.go
- controllers/datadogagent/component/clusteragent/default.go
Pass its pod name to the cluster agent.
It’s used by DataDog/datadog-agent#17305 to improve the leader election when the cluster-agent runs with `hostNetwork: true`.
The corresponding `helm-charts` PR is DataDog/helm-charts#1065.
It’s the same test plan as for DataDog/datadog-agent#17305, but with the agent being deployed by the operator :
Start the cluster agent with `hostNetwork: true`.
Without this change, the cluster agents were logging errors like:
```
2023-05-25 15:48:35 UTC | CLUSTER | WARN | (pkg/clusteragent/clusterchecks/handler.go:192 in leaderWatch) | Could not refresh leadership status: "target named gke-gke-lenaic-ubuntu-containerd-2a3618a5-lzg5" not found, will only log every 100 errors
```
These errors should go away with this change.
In the output of `agent status`, the …
> [CONT-4042] Pass its pod name to the cluster-agent

- controllers/datadogagent/feature/cspm/feature.go
- controllers/datadogagent/feature/cws/feature.go
The core agent communicates through the inventories if CWS is enabled. To do that correctly it needs to know if CWS is enabled, which is doesn't if the env vars are only set on other containers.
This PR fixes this issue for CWS and for CSPM as well.
> instruct the core agent that CWS/CSPM is enabled

- controllers/datadogagent/feature/kubernetesstatecore/feature.go
Service Account was being overridden to always use the cluster agent SA even when the check is running on cluster checks runners.
Run the KSM Core feature and ensure that the cluster role binding is pointing to the Cluster Checks Worker service account
> [ksmfeature] fix bug where service account was being overwritten

- controllers/datadogagent/component/clusterchecksrunner/default.go
Add a few additional permissions to cluster checks runner including missing `leases` RBAC for kube controller manager leader election
Also formatted existing RBACs for ease of reading
Make sure kube controller manager WARN log lines are not present on Cluster Checks Runner.
> add additional permissions to CCR clusterrole

- .gitlab-ci.yml
Add the possibility to push manually  on internal staging registry `operator` and `operator-check` images, without the need of a tag.
Ease testing custom operator build
> Allow manual push to staging

- cmd/check-operator/patchcrd/patchcrd.go
- cmd/check-operator/root/root.go
- cmd/check-operator/upgrade/upgrade.go
- pkg/plugin/common/options.go
The new `patch-crd` check-operator's sub-command allows to update
CRD `status.storedVersions` field to remove deprecated version.
For the Operator, it will allow to remove the `v1Alpha1` version
of the `datadogagents.datadoghq.com` CRD.
To be able to remove a deprecated version in a CRD `spec`, it can be needed to patch the `crd.status.storedVersions` to removes reference to the deprecated version before trying to remove the version from the `spec`. (see [public Kubernetes doc](https://kubernetes.io/docs/tasks/extend-kubernetes/custom-resources/custom-resource-definition-versioning/#upgrade-existing-objects-to-a-new-stored-version)
The idea is to use this command in a `pre-upgrade` helm hook.
Maybe we can also add this sub-command into the `kubectl datadog` plugin.
Write there any …
> Add(check-operator): patch-crd sub command

- .gitlab-ci.yml
Add a `commit sha` in the internal image tag, if the build is triggered manually
simply internal testing. Adding the commit sha in the image tag allow to push several image from the same branch without overriding the previous version. It can be usefull if the image was already replicated in some registry. Or to compare two versions
> Improve internal image tagging

- .github/workflows/pr-linter.yml
Adds a more descriptive error message to the github workflow.
Before:
```
Run exit 1
Error: Process completed with exit code 1.
```
After:
```
Run echo "::error::Missing milestone or \`qa/skip-qa\` label" && exit 1
Error: Missing milestone or `qa/skip-qa` label
Error: Process completed with exit code 1.
```
> [tooling] Add more descriptive error message

- controllers/datadogagent/component/agent/new.go
- controllers/datadogagent/component/agent/new_test.go
Fix parsing of flags that should be treated as IntOrString values (and not just strings).
N/A
Test the operator with different inputs for `--edsCanaryReplicas`, for instance:
```
args:
- --enable-leader-election
- --pprof
- --supportExtendedDaemonset=true
- --edsMaxPodUnavailable=5%
- --edsCanaryReplicas=15
```
```
args:
- --enable-leader-election
- --pprof
- --supportExtendedDaemonset=true
- --edsMaxPodUnavailable=5%
- --edsCanaryReplicas=15%
```
and make sure that the resulting ExtendedDaemonset resource has the spec value types set as expected. (`kubectl get eds -oyaml`).
> fix parsing of EDS flag options

- .gitlab-ci.yml
Update Redhat registry and `publish_redhat_public_tag` job to not depend on internal PaaS service.
More automation; the image push job has been broken for some time now
> [ci] update publish_redhat_public_tag job

- docs/install-openshift.md
- examples/datadogagent/v2alpha1/datadog-agent-openshift.yaml
* Updates the OpenShift documentation to include the SC override for the DCA so it can run `agent ...` commands (thanks to the `auth_token` in `/etc/datadog-agent/`) and use cluster checks from files
* Detailed context is available in the Github original PR : https://github.com/DataDog/datadog-operator/pull/897
* This is a "band-aid" while the DCA is not able to properly run for now with `readOnlyRootFilesystem: true` (not specifically in OpenShift, but this is where notably we can see the consequences)
> Update OpenShift install docs and example for proper DCA behaviour

- controllers/datadogagent/feature/remoteconfig/feature.go
- controllers/datadogagent/feature/remoteconfig/feature_test.go
Remote Config needs access to `/opt/datadog-agent/run` in order to create its local database where configurations & their metadata are stored. By default, the cluster agent has the `readOnlyRootFilesystem` parameter set to true for security reasons. To circumvent this, we create an EmptyDir volume on the required path so that the agent can create the Remote Config database.
Current workaround is to create the volume at agent creation or disable the `readOnlyRootFilesystem` parameter. This doesn't impact many users currently as no product using Remote Config on the cluster agent is GA.
Fixing bugs
N/A
No
Create a cluster agent and check in the logs it is able to start Remote Config properly
Error: `Failed to start remote-configuration: unable to create remote-config service: failed to …
> upgrade(remote-config): Create cluster agent volume when Remote Config is enabled

- config/rbac/role.yaml
- controllers/datadogagent/component/agent/rbac.go
- pkg/kubernetes/rbac/const.go
This change updates the cluster role that the operator defines for the agent. This change corresponds to https://github.com/DataDog/helm-charts/pull/1155.
Kubernetes v1.26 exposed a new `/metrics/slis` endpoint (reference [here](https://kubernetes.io/docs/reference/instrumentation/slis/#sli-metrics)). This change is necessary to support the corresponding changes in https://github.com/DataDog/integrations-core/pull/15731
Is the milestone `1.2.0` set correctly?
I followed the following steps (thanks @khewonc for the guidance!)
1. `make build`
2. `make docker-build`
3. `make deploy`
4. I then verified that the pod cluster role changes were applied appropriately
> Add rule to allow agent role to curl `/metrics/slis`

- apis/datadoghq/v1alpha1/datadogmonitor_types.go
- apis/datadoghq/v1alpha1/zz_generated.openapi.go
- config/crd/bases/v1/datadoghq.com_datadogmonitors.yaml
- config/crd/bases/v1beta1/datadoghq.com_datadogmonitors.yaml
- controllers/datadogmonitor/controller.go
- controllers/datadogmonitor/controller_test.go
- controllers/datadogmonitor/monitor.go
- controllers/datadogmonitor/monitor_test.go
- Utilize updated client and retrieve monitor downtimes
- Show downtime status and the first matching downtime ID
While working on this PR there were a few improvements made:
- Use proper tags for openapi gen; this has resulted in a large diff in the generated file (apis/datadoghq/v1alpha1/zz_generated.openapi.go)
- Fix kubebuilder tags
- Handle errors better for MonitorStateSyncStatus
Better experience to make downtime information visible for datadogmonitor users
N/A
- Create a DatadogMonitor resource (such as in examples/)
- Mute the monitor from the UI
- run `kubectl get datadogmonitor` and `kubectl describe datadogmonitor` to see the DowntimeStatus showing the …
> [datadogmonitor] Return matching downtimes and show downtime status

- controllers/datadogagent/component/utils.go
- controllers/datadogagent/feature/apm/feature.go
- controllers/datadogagent/feature/dogstatsd/feature.go
- controllers/datadogagent/feature/otlp/feature.go
Adds back in the local agent service selector.
Agent service:
```
$ kubectl describe svc datadog-agent
Name:              datadog-agent
[...]
Selector:          agent.datadoghq.com/component=agent,agent.datadoghq.com/name=datadog
```
Logs from node tracer showing traces were sent to the local agent service:
```
Request to the agent: {"path":"/v0.4/traces","method":"PUT","headers":{"Content-Type":"application/msgpack","Datadog-Meta-Tracer-Version":"2.11.0","X-Datadog-Trace-Count":"1","Datadog-Meta-Lang":"nodejs","Datadog-Meta-Lang-Version":"v12.22.12","Datadog-Meta-Lang-Interpreter":"v8"},"protocol":"http:","hostname":"datadog-agent.system.svc.cluster.local","port":"8126"}
Response from the agent: {"rate_by_service":{"service:,env:":1}}
```
Logs from trace-agent showing the trace was …
> Add local agent service selector

- main.go
Log `V2APIEnabled` deprecation notice. Output when flag is set to `false`:
`{"level":"INFO","ts":"2023-09-08T17:29:10Z","logger":"setup","msg":"V2APIEnabled flag is deprecated in v1.2.0+ and will be removed in the future releases. Once removed Operator can't be configured to reconcile DatadogAgent CRD v1alpha1. You will still be able to apply v1alpha1 with conversion webhook enabled."}`
Cleaning up v1 controller in later versions.
> Add a startup log for V2APIEnabled flag deprecation

- controllers/datadogmonitor/controller.go
Recreate a monitor if it is deleted in the UI
* Agent: n/a
> [datadogmonitor] Recreate monitor if deleted in the UI

- apis/datadoghq/v2alpha1/datadogagent_types.go
- config/crd/bases/v1/datadoghq.com_datadogagents.yaml
- config/crd/bases/v1beta1/datadoghq.com_datadogagents.yaml
- docs/configuration.v2alpha1.md
Admission controller is [enabled by default](https://github.com/DataDog/datadog-operator/blob/main/apis/datadoghq/v2alpha1/datadogagent_default.go#L66) but CRD doc/comment says otherwise.
fix doc
> Fix Admission Controller default value doc/comment

- main.go
Follow up go #915 ; small fixes including spaces after the periods and a small update to wording.
```
{"level":"INFO","ts":"2023-09-18T17:23:11Z","logger":"setup","msg":"The 'v2APIEnabled' flag is deprecated in v1.2.0+ and will be removed in a future release. Once removed, the Datadog Operator cannot be configured to reconcile the v1alpha1 DatadogAgent CRD. However, you will still be able to apply a v1alpha1 manifest with the conversion webhook enabled (using the flag 'webhookEnabled')."}
```
Fix formatting and make message clearer
> fix spaces after periods and small wording tweak

- apis/datadoghq/v1alpha1/datadogmonitor_types.go
- apis/datadoghq/v1alpha1/zz_generated.openapi.go
- config/crd/bases/v1/datadoghq.com_datadogmonitors.yaml
- config/crd/bases/v1beta1/datadoghq.com_datadogmonitors.yaml
- controllers/datadogmonitor/controller.go
- controllers/datadogmonitor/controller_test.go
- controllers/datadogmonitor/monitor.go
- controllers/datadogmonitor/monitor_test.go
* Revert "[datadogmonitor] Return matching downtimes and show downtime status (#894)"
This reverts commit b044ce7135e0dbe682f8dca0f4b1af9009c0c75d.
* re-add openapi-gen tags
> Revert "[datadogmonitor] Return matching downtimes and show downtime status (#894)" (#932)

- pkg/defaulting/images.go
> [defaulting/images] Update agents to 7.47.1

- controllers/datadogagent/feature/kubernetesstatecore/configmap.go
- docs/kubernetes_state_metrics.md
This PR removes the ksm telemetry parameter which should be disabled by default.
This parameter was initially added for internal QA. Moreover, it can cause tag corruption, adding `resource_name` tag to every ksm metric.
N/A
N/A
> Remove ksm `telemetry` parameter

- apis/datadoghq/v2alpha1/datadogagent_types.go
- config/crd/bases/v1/datadoghq.com_datadogagents.yaml
- config/crd/bases/v1beta1/datadoghq.com_datadogagents.yaml
- docs/configuration.v2alpha1.md
Fixes Remote Config doc on RC being enabled by default
Clean docs
Just docs
> fix(remoteConfig): Fix documentation on default behaviour

- controllers/datadogagent/clusterchecksrunner.go
- controllers/datadogagent/clusterchecksrunner_test.go
Disables Remote Config on the cluster checks runner
Error logs during QA
N/A
This bug only triggers after agent 7.47.0
Run the cluster checks runner, see there is no error log for Remote Config
> fix(clusterchecksrunner): Disable Remote Config

- .gitlab-ci.yml
Update runner image to use golang 1.19 due to issue following update of [setup-envtest](https://github.com/kubernetes-sigs/controller-runtime/issues/2537)
Fix CI failure
> update gitlab runner image to golang 1.19-bullseye

- apis/datadoghq/v2alpha1/datadogagent_default.go
- controllers/datadogagent/override/global.go
* Moves logic checking for user-defined settings (from `spec.global`) to `controllers/datadogagent/override/global.go/ApplyGlobalSettings` function regarding the Kubelet client CA used by the Agent when a user-provided host location is mounted.
* Simplifies the logic by : 
* setting `DD_KUBELET_CLIENT_CA` if and only if the user provides the host location instead of setting it to `/var/run/secrets/kubernetes.io/serviceaccount/ca.crt` since this is already the Agent default : https://github.com/DataDog/datadog-agent/blob/2fa6b7b721c8605d67d85d3d6b1cc867eee1a1d0/pkg/util/kubernetes/kubelet/kubelet_client.go#L64-L66
* When there is no user-provided host, avoid re-setting the kubelet host "default" `status.hostIP` as it is already defined in the default daemonset template spec thanks to …
> Use Agent default for kubelet client CA and move CA logic to override/global.go

- apis/datadoghq/common/common.go
- apis/datadoghq/v1alpha1/datadogagent_default.go
- apis/datadoghq/v1alpha1/datadogagent_default_test.go
- controllers/datadogagent/component/agent/default.go
- Remove the default liveness and readiness probes from all agent containers besides the core agent
- Add a different default probe (same for liveness and readiness) for the trace agent container
> update default liveness and readiness probes

- controllers/datadogagent/override/global.go
* Mounts kubelet CA certificates in `security-agent` container when provided by the user in `spec.global.kubelet`
* Self-testing, my `security-agent` container would CLBO since it wasn't able to get a hostname from `kubelet` despite providing the certificates to ensure TLS connection
~~Are there minimum versions of the Datadog Agent and/or Cluster Agent required?~~
* Start a basic `kind` cluster (kubelet CA certificate is stored in `/var/lib/kubelet/pki/kubelet.crt`)
* Use a CRD that enables the security agent such as below, while using a kubelet CA host configuration using the node name as the kubelet host (since `kind` does not set the node IP as SAN) : 
```
spec:
global:
kubelet:
hostCAPath: "/var/lib/kubelet/pki/kubelet.crt"
host:
fieldRef: …
```
> [kubelet] Add kubelet CA volume mount to security Agent container

- pkg/defaulting/images.go
> update agents images to 7.48.0

- pkg/controller/utils/datadog/metrics_forwarder.go
- pkg/controller/utils/datadog/metrics_forwarder_test.go
* This PR removes the requirement of setting an application key in order for the metrics forwarder of the operator (responsible to send metrics such as `datadog.operator.<feature>.enabled` and events) to be initialized
* [CECO-721] : Datadog intake solely requires API key for data submission. Dropping the application key is beneficial as it reduces the privileges of the API client and the number of secrets the operator needs
* Create a secret with your api key : `k create secret generic datadog-secret --from-literal api-key=$DD_API_KEY`
* Install the custom operator build without setting any credentials : `helm install my-datadog-operator datadog/datadog-operator --set …
> [CECO-721] Operator metrics forwarder : drop application key dependency

- cmd/check-operator/upgrade/upgrade.go
- pkg/plugin/common/statuswrapper.go
Check for agent reconciliation errors in the upgrade hook, and report an error status as appropriate.
There are instances where a reconciliation error occurs in the agent/cluster agent, but the upgrade hook hangs until it times out as it does not detect these errors earlier.
Questions: 
1. Should more information be provided in the error that is returned?
2. When testing there was a case where `AgentReconcile` was `false` but `DatadogAgentReconcileError` was `false` as well. To ensure all conditions are covered, the hook currently checks the value of `DatadogAgentReconcileError`, `AgentReconcile` and `ClusterAgentReconcile`, and errors out if any indicate an error state. Is this case valid, or should this be investigated further?
Are there minimum versions of the Datadog Agent and/or …
> Check CRD status for reconcile errors in upgrade hook

- pkg/defaulting/images.go
Set the default version of agent and cluster agent to `7.49.0`.
`7.49.0` was just released!
Deploy and check that the agent/cluster agent version is `7.49.0`.
> [defaulting/images] Set default version of agent and cluster agent to `7.49.0`

- apis/datadoghq/common/const.go
- apis/datadoghq/v2alpha1/datadogagent_default.go
- apis/datadoghq/v2alpha1/datadogagent_default_test.go
- apis/datadoghq/v2alpha1/datadogagent_types.go
- config/crd/bases/v1/datadoghq.com_datadogagents.yaml
- config/crd/bases/v1beta1/datadoghq.com_datadogagents.yaml
- docs/configuration.v2alpha1.md
Add GCR EU and Asia registries with auto defaulting based on site.
Create a `DatadogAgent` with europe or asia site, the registry should be defaulted to `eu.gcr.io` or `asia.gcr.io`.
> Add GCR EU and Asia registries with auto defaulting

- config/rbac/role.yaml
- controllers/datadogagent/controller_reconcile_agent.go
- controllers/datadogagent/controller_reconcile_v2.go
- controllers/datadogagent/override/container.go
- controllers/datadogagent/override/container_test.go
- controllers/datadogagent/override/daemonset.go
- controllers/datadogagent_controller.go
- pkg/agentprofile/agent_profile.go
- pkg/agentprofile/agent_profile_test.go
First version to support Agent profiles.
Only the basic scenarios are supported for now. I've left many TODO comments in the code with all the things that should be addressed.
Current limitations (most of them should be mentioned in the TODO comments):
- Profiles with more than one rule might not work properly (we probably need to change the approach used to generate the "default" profile".
- Conflicts between profiles are not handled.
- We need to watch nodes in the controller (and only generate events when there are changes in the labels).
- Only DaemonSets are supported for now. We should do the same for EDS.
- We need integration tests.
- We should add something in the profile status field.
- I don't think `lt` and `gt` operators work well because they're not exact opposites.
- Only …
> First version to support Agent profiles

- pkg/defaulting/images.go
7.49.1 has just been released. it would be great to have it in Operator 1.3.0
deployed by default the latest stable agent version
Create a DatadogAgent CR without specifying the agent or cluster agent version. The image tag should be set to 7.49.1
> Update default Agent/DCA version to 7.49.1

- apis/datadoghq/common/envvar.go
- controllers/datadogagent/component/agent/default.go
This commit set the envvar DD_CONTAINER_IMAGE_ENABLED=true by default
in the NodeAgent's "agent" container.
This PR is needed for the other PR https://github.com/DataDog/datadog-operator/pull/836 to work with agent 7.49.0
We want to enabled container-image collection by default. it will
be the case from agent 7.50.0. But in Operator 1.3.0, the Agent is
defaulted to 7.49.0 since 7.50.0 is not yet released.
* Agent: v7.48.0
Deploy the agent with the operator. The container images should appears in the new beta [container image page](https://app.datadoghq.com/containers/images)
Another way to validate that the PR works, is to exec in a running …
> Enable by default container-image collection

- hack/patch-bundle.sh
Updates script that updates bundle/ClusterServiceVersion file following notice from Redhat that, if using `olm.skipRange`, we also need to include `spec.replaces`.
Note that this will require setting `LATEST_VERSION` when running the make bundle command.
Redhat notice
> update patch-bundle script to include spec.replaces field in bundle

- pkg/defaulting/images.go
Cherry pick #984: 7.49.1 has just been released. it would be great to have it in Operator 1.3.0
Create a DatadogAgent CR without specifying the agent or cluster agent version. The image tag should be set to 7.49.1
> cherry-pick: Update default Agent/DCA version to 7.49.1 (#984)

- apis/datadoghq/common/envvar.go
- controllers/datadogagent/component/agent/default.go
cherry-pick: Enable by default container-image collection (#983)
We want to enabled container-image collection by default. it will
be the case from agent 7.50.0. But in Operator 1.3.0, the Agent is
defaulted to 7.49.0 since 7.50.0 is not yet released.
This commit set the envvar DD_CONTAINER_IMAGE_ENABLED=true by default
in the NodeAgent's "agent" container.
Deploy the agent with the operator. The container images should appears in the new beta [container image page](https://app.datadoghq.com/containers/images)
Another way to validate that the PR works, is to exec in a running NodeAgent pod and run the `agent config` command to …
> cherry-pick: Enable by default container-image collection (#983)

- docs/integrations_autodiscovery.md
* Update integrations_autodiscovery.md
Noticed a mismatched https://a.cl.ly/qGuYnRqn
* Update integrations_autodiscovery.md
Updated the configuration to match the graph title "Use the spec.override.nodeAgent.extraConfd.configDataMap" -> "Use the spec.override.clusterAgent.extraConfd.configDataMap" apiVersion: datadoghq.com/v2alpha1
metadata:
name: datadog
spec:
global:
credentials:
apiKey: "<DATADOG_API_KEY>"
appKey: "<DATADOG_APP_KEY>"
override:
nodeAgent:
extraConfd:
configDataMap:
http_check.yaml: |-
init_config:
instances:
- url: "http://%%host%%" name: "My service"
Are there minimum versions of the Datadog …
> [cherry-pick] Update integrations_autodiscovery.md (#985)

- controllers/datadogagent/controller_reconcile_agent.go
- pkg/agentprofile/agent_profile.go
- pkg/agentprofile/agent_profile_test.go
Adds the `agent.datadoghq.com/profile` label to the daemonsets associated with a profile.
> [profiles] Add label to DaemonSets

- controllers/datadogagent_controller_v2_profiles_test.go
- controllers/datadogagent_controller_v2_test.go
Adds integration tests for the DatadogAgent profiles.
There are a couple of them marked as "pending". They test things that we know that don't work yet.
> [profiles] Add integration tests

- apis/datadoghq/v1alpha1/datadogagentprofile_validation.go
- apis/datadoghq/v1alpha1/datadogagentprofile_validation_test.go
Adds a function to validate that a DatadogAgentProfile manifest contains the required fields
* Agent: n/a
> Profile manifest validation

- apis/datadoghq/v2alpha1/datadogagent_default.go
- apis/datadoghq/v2alpha1/datadogagent_default_test.go
- apis/datadoghq/v2alpha1/datadogagent_types.go
- config/crd/bases/v1/datadoghq.com_datadogagents.yaml
- config/crd/bases/v1beta1/datadoghq.com_datadogagents.yaml
- docs/configuration.v2alpha1.md
Breaking up https://github.com/DataDog/datadog-operator/pull/981 into 2 parts.
Unblock Release of 1.3.0.
> Enabling APM by default

- apis/datadoghq/v2alpha1/datadogagent_default.go
- apis/datadoghq/v2alpha1/datadogagent_default_test.go
- apis/datadoghq/v2alpha1/datadogagent_types.go
- config/crd/bases/v1/datadoghq.com_datadogagents.yaml
- config/crd/bases/v1beta1/datadoghq.com_datadogagents.yaml
- docs/configuration.v2alpha1.md
Breaking up https://github.com/DataDog/datadog-operator/pull/981 into 2 parts.
Unblock Release of 1.3.0.
> Enabling APM by default (#1006) 

- config/rbac/role.yaml
- controllers/datadogagent/controller_reconcile_agent.go
- controllers/datadogagent/controller_reconcile_v2.go
- controllers/datadogagent/finalizer.go
- controllers/datadogagent/finalizer_test.go
- controllers/datadogagent/testutils/client_utils.go
- controllers/datadogagent_controller.go
- controllers/datadogagent_controller_v2_profiles_test.go
- pkg/agentprofile/agent_profile.go
- pkg/agentprofile/agent_profile_test.go
Changes the strategy used to create the default profile (the one that applies to nodes where none of the profiles defined apply).
We were creating the default profile by generating the opposite selector requirements of all the others. The downside of this approach is that it redeploys everything when the profile changes. Also, we did not implement support for profiles with multiple selector requirements which is not so easy to do with this approach.
The new approach tags adds a specific label whenever a profile is applied to them and defines the default profile's node affinity so that it excludes nodes with this label. This change fixes the issues mentioned above.
> [profiles] Create default profile with a node anti affinity

- controllers/datadogagent/override/podtemplatespec.go
- controllers/datadogagent/override/podtemplatespec_test.go
When there's an affinity override defined in the DDA it simply replaces the one defined by default. This PR changes that so that both affinities are merged instead.
We need this for the profile features because in order to make the feature work we define node affinities and anti pod affinities. We need to combine those with the ones defined in the override of the DDA instead of just replacing.
> [override/podtemplatespec] Merge affinities

- controllers/datadogagent_controller_v2_profiles_test.go
- pkg/agentprofile/agent_profile.go
- pkg/agentprofile/agent_profile_test.go
Adds pod anti-affinity to agent pods to avoid scheduling multiple agent pods of different profiles on the same node during rollouts.
I've marked this as draft because this PR contains the commits from #1002. It needs to be merged before this one.
> [profiles] Add pod anti-affinity to agent pods

- controllers/datadogagent/clusteragent.go
- controllers/datadogagent/component/clusteragent/default.go
DCA namespace resources env var added for V2
CECO-836
* Agent: N/A
> [CECO-836] DCA namespace resources env var added for V2

- apis/datadoghq/common/envvar.go
- controllers/datadogagent/agent_test.go
- controllers/datadogagent/clusteragent.go
- controllers/datadogagent/clusteragent_test.go
- pkg/controller/utils/shared_utils.go
Sets an environment variable DD_KUBE_RESOURCES_NAMESPACE on Cluster Agent, indicating the Kubernetes namespace where Datadog is running at. This env variable is already set by Helm Charts and is used in Cluster Agent.
To move APM Instrumentation namespaces exclusion logic to Cluster Agent, Cluster Agent needs to know the namespace where it's running.
Updated Cluster Agent unit-tests in the Operator
> [APMON-406] Set Datadog namespace env variable on Cluster Agent

- hack/patch-bundle.sh
Fixes test failures in [community-operators-prod](https://github.com/redhat-openshift-ecosystem/community-operators-prod) publishing process, sample PR https://github.com/redhat-openshift-ecosystem/community-operators-prod/pull/3760.
Output after change
```diff
repository: https://github.com/DataDog/datadog-operator
-    containerImage: gcr.io/datadoghq/operator:1.2.1
-    olm.skipRange: <1.2.1
-  name: datadog-operator.v1.2.1
+    containerImage: gcr.io/datadoghq/operator:1.3.0
+    createAt: "2023-12-19 17:44:43"
+    support: Datadog Inc.
+    olm.skipRange: <1.3.0
+  name: datadog-operator.v1.3.0
``` …
> Add `createdAd`, `support` fields to bundle CSV file

- apis/datadoghq/v2alpha1/datadogagent_default.go
- apis/datadoghq/v2alpha1/datadogagent_default_test.go
- Set explicit default `Enabled` values for all features
- Add default value for EBPFCheck
- Update tests accordingly
The effect of this PR should be noop. 
Build Operator and apply a minimal DatadogAgent. Check that LogCollection, LiveProcessCollection, OOMKill, TCPQueueLength, CSPM, CWS, NPM, USM, ExternalMetricsServer, and PrometheusScraped are all disabled by default.
> update feature default values and tests

- controllers/datadogagent/controller.go
- controllers/datadogagent/controller_reconcile_agent.go
- controllers/datadogagent/controller_reconcile_agent_test.go
- controllers/datadogagent/controller_reconcile_v2.go
- controllers/datadogagent_controller.go
- controllers/setup.go
- pkg/kubernetes/provider.go
- pkg/kubernetes/provider_test.go
Cleans up unused DS/EDSs. In a cluster with cos and ubuntu node pools, we start with 2 DS:
```
$ kubectl get pods
NAME                                         READY   STATUS    RESTARTS   AGE
datadog-agent-gcp-cos-bp9hj                  3/3     Running   0          5m46s
datadog-agent-gcp-cos-rp5jl                  3/3     Running   0          5m46s
datadog-agent-gcp-ubuntu-h8d95               3/3     Running   0          2m
datadog-agent-gcp-ubuntu-mkfbq               3/3     Running   0          2m
datadog-cluster-agent-54cbb867bc-jhvw5       1/1     Running   0          5m46s
operator-datadog-operator-5c965d787d-2zxh8   1/1     Running   0          10m
$ kubectl get ds
NAME                       DESIRED   CURRENT   READY   UP-TO-DATE   AVAILABLE   NODE SELECTOR   AGE …
```
> [CECO-754][introspection] Clean up unused ds/eds

- pkg/kubernetes/provider.go
- pkg/kubernetes/provider_test.go
Adds an allowlist for provider values. Currently, we only check for a valid label key so any label value will become a provider even if the operator code doesn't fully support the provider. For example, `cloud.google.com/gke-os-distribution:foo` would create a provider `foo` whether or not we had the necessary changes in agent configuration to support provider `foo`. With this PR, a provider must be allowlisted or it will automatically fall under the `default` provider.
Current behavior when adding an ubuntu nodepool:
```
$ kubectl get ds
NAME                       DESIRED   CURRENT   READY   UP-TO-DATE   AVAILABLE   NODE SELECTOR   AGE
datadog-agent-gcp-cos      2         2         2       2            2           <none>          5m52s
datadog-agent-gcp-ubuntu   2         2         2 …
```
> [CECO-755][introspection] Limit provider values using allowlist

- hack/patch-bundle.sh
Update how `spec.replaces` is formatted in the bundle CSV file. Correct formatting was suggested [here](https://github.com/redhat-openshift-ecosystem/certified-operators/pull/3288#discussion_r1433705281)
Result sample
```diff
@@ -1016,4 +1018,4 @@ spec:
provider:
name: Datadog
version: 1.3.0
-  replaces: 1.2.1
+  replaces: datadog-operator.v1.2.1
diff --git a/hack/patch-bundle.sh b/hack/patch-bundle.sh
```
> Fix patch_bundle.sh `spec.replaces` formatting

- controllers/datadogagent/controller_reconcile_agent.go
- controllers/datadogagent/controller_reconcile_agent_test.go
- controllers/datadogagent/controller_reconcile_v2.go
Remove deleted DS/EDS status from DDA status.
Current `kubectl describe dd datadog`:
```
Status:
Agent:
Available:       2
Current:         2
Current Hash:    1c5c7b21c84b6a4462eda5060f919f0a
Daemonset Name:  datadog-agent-gcp-cos
Desired:         2
Last Update:     2023-12-21T21:59:49Z
Ready:           2
State:           Running
Status:          Running (2/2/2)
Up To Date:      2
Available:       0
Current:         0
Current Hash:    4e4dfa99925563393b45a2dec1e8ac3b
Daemonset Name:  datadog-agent-default
Desired:         0
Last Update:     2023-12-21T21:59:18Z
Ready:           0
State:           Running
Status:          Running (0/0/0)
Up To Date:      0
```
New behavior `kubectl describe dd datadog`:
```
Status:
Agent:
Available:       2
Current:         2
Current Hash: …
```
> [CECO-849][introspection] Remove unused ds status

- controllers/datadogagent/controller_reconcile_v2.go
- pkg/agentprofile/agent_profile.go
- pkg/agentprofile/agent_profile_test.go
Adds validation of DAP to ensure they are not missing any required configs like `ProfileAffinity` or a resource override
* Agent: n/a
> [CECO-841] Add DAP validation before applying profiles

- pkg/defaulting/images.go
> [defaulting/images] Update agents to 7.50.1

- pkg/defaulting/images.go
> [defaulting/images] Update agents to 7.50.2

- pkg/defaulting/images.go
> [defaulting/images] Update agents to 7.50.3

- controllers/datadogagent/controller_reconcile_agent.go
- controllers/datadogagent/testutils/client_utils.go
Adds support for EDS when using profiles.
When EDS is enabled and there are profiles defined, we only create an EDS for the default profile, for the other profiles we create DaemonSets. This is to make deployments simpler. With multiple EDS there would be multiple canaries, etc.
> [profiles] Add support for EDS

- .gitlab-ci.yml
Adds nightly image build jobs. This will trigger a downstream job in the internal images tool.
Requires manual trigger for now.
Set up nightly Operator deploys
> [gitlab] Add nightly operator and operator_check jobs

- controllers/datadogagent/controller_reconcile_agent_test.go
- controllers/datadogagent/feature/oomkill/feature.go
- controllers/datadogagent/feature/tcpqueuelength/feature.go
- pkg/kubernetes/provider.go
- pkg/kubernetes/provider_test.go
Change introspection cloud provider from `gcp` to `gke` to match what we have in helm: https://github.com/DataDog/helm-charts/blob/716fc5c56344d64ddf9a1841e9d70d96a7a8fd94/charts/datadog/values.yaml#L2017
* Agent: n/a
> [introspection] Change gcp to gke

- controllers/datadogagent/controller_reconcile_agent_test.go
- controllers/datadogagent/feature/oomkill/feature.go
- controllers/datadogagent/feature/tcpqueuelength/feature.go
- pkg/kubernetes/provider.go
- pkg/kubernetes/provider_test.go
Cherry pick of https://github.com/DataDog/datadog-operator/pull/1046
> Change introspection cloud provider from gcp to gke to match what we have in helm: https://github.com/DataDog/helm-charts/blob/716fc5c56344d64ddf9a1841e9d70d96a7a8fd94/charts/datadog/values.yaml#L2017
* Agent: n/a
> [cherry-pick][introspection] Change gcp to gke

- apis/datadoghq/common/const.go
- controllers/datadogagent/feature/sbom/feature.go
- controllers/datadogagent/feature/sbom/feature_test.go
This PR mounts the host files required for the agent to be able
to properly detection the host operating system.
Without this change, the SBOM generated is the one from the
agent container and not the one from the host.
> Mount host files for proper os detection in SBOMs

- apis/datadoghq/v2alpha1/test/builder.go
- controllers/datadogagent/controller_reconcile_agent.go
- controllers/datadogagent/controller_v2_test.go
When overrides were set with multiple providers, the node agent names were being combined:
```
datadog-agent-agent-default
datadog-agent-agent-default-gcp-cos
datadog-agent-agent-gcp-cos
datadog-agent-agent-gcp-cos-default
```
This PR should prevent that from happening:
```
NAME                    DESIRED   CURRENT   READY   UP-TO-DATE   AVAILABLE   NODE SELECTOR   AGE
datadog-agent-default   5         5         3       5            3           <none>          6m36s
datadog-agent-gke-cos   5         5         0       5            0           <none>          6m36s
```
* Agent: n/a
Add an override with …
> [introspection] Fix override name combining

- apis/datadoghq/v2alpha1/test/builder.go
- controllers/datadogagent/controller_reconcile_agent.go
- controllers/datadogagent/controller_v2_test.go
Cherry pick of https://github.com/DataDog/datadog-operator/pull/1049
> When overrides were set with multiple providers, the node agent names were being combined:
```
datadog-agent-agent-default
datadog-agent-agent-default-gcp-cos
datadog-agent-agent-gcp-cos
datadog-agent-agent-gcp-cos-default
```
> This PR should prevent that from happening:
```
NAME                    DESIRED   CURRENT   READY   UP-TO-DATE   AVAILABLE   NODE SELECTOR   AGE
datadog-agent-default   5         5         3       5            3           <none>          6m36s
datadog-agent-gke-cos   5         5         0       5            0           <none>          6m36s
```
Are there minimum versions of the Datadog Agent and/or …
> [cherry-pick][introspection] Fix override name combining (#1049)

- controllers/datadogagent/override/podtemplatespec.go
- controllers/datadogagent/override/podtemplatespec_test.go
Cherry picks https://github.com/DataDog/datadog-operator/pull/1004
Introspection changes are overridden by node affinity overrides in the node component. Instead of replacing affinities when set in the overrides, merge them
* Agent: n/a
> [cherry-pick][override/podtemplatespec] Merge affinities (#1004)

- controllers/datadogagent/override/podtemplatespec.go
- controllers/datadogagent/override/podtemplatespec_test.go
Adds ability to merge affinities in overrides section. Porting over https://github.com/DataDog/datadog-operator/pull/1004
Introspection changes are overridden by node affinity overrides in the node component. Instead of replacing affinities when set in the overrides, merge them
* Agent: n/a
> [override/podtemplatespec] Merge affinities (#1004)

- controllers/datadogagent/override/container.go
- controllers/datadogagent/override/container_test.go
Fixes a bug in the function that overrides container resources. It was not overriding when the value was 0, but that's incorrect.
> [override/container] Fix container resources override with 0

- docs/installation.md
One of the `kubectl` commands in this installation guide passed a non-path parameter to `kubectl apply -f`. I'm not sure what the `agent_spec=` prefix is supposed to do, but `kubectl` rejects it on my cluster.
> Correct a malformed example command in installation.md

- controllers/datadogagent/controller_reconcile_agent.go
- controllers/datadogagent/controller_reconcile_v2.go
- controllers/datadogagent_controller.go
- main.go
Reduces the memory usage of the `cleanupPodsForProfilesThatNoLongerApply`.
This PR configures the cache so that only node agent pods are stored and only the information that we need (labels and nodeName).
This PR depends on my previous one: #1064 (only the last commit is new)
> [profiles] Reduce mem usage in pods cleanup

- controllers/datadogagent/controller_reconcile_agent.go
- controllers/datadogagent/controller_test.go
Use `<profile-namespace>-<profile-name>` as the node label value instead of `true` for better tracking. 
Example: When adding a profile `dap-test` in the `default` ns targeting node `xx-worker2`, the node is labeled with `agent.datadoghq.com/profile=default-dap-test`:
```console
$ kubectl get node --show-labels
NAME               STATUS   ROLES           AGE    VERSION   LABELS
xx-control-plane   Ready    control-plane   7d3h   v1.28.0   beta.kubernetes.io/arch=arm64,beta.kubernetes.io/os=linux,kubernetes.io/arch=arm64,kubernetes.io/hostname=xx-control-plane,kubernetes.io/os=linux,node-role.kubernetes.io/control-plane=,node.kubernetes.io/exclude-from-external-load-balancers=
xx-worker          Ready    <none>          7d3h   v1.28.0 …
```
> [profiles] Change node labels to use dap ns-name format

- .golangci.toml
- Makefile
Bump `golangci-lint` version from v1.51.0 to v1.56.0
The current version of `golangci-lint` has memory issues with some Go versions.
```
➜  datadog-operator git:(wassim.dhif/bump-golangci-lint) ✗ make lint
hack/golangci-lint.sh -b "bin/darwin-arm64" v1.56.0
golangci/golangci-lint info checking GitHub for tag 'v1.56.0'
golangci/golangci-lint info found version: 1.56.0 for v1.56.0/darwin/arm64
golangci/golangci-lint info installed bin/darwin-arm64/golangci-lint
go fmt ./...
go vet ./...
bin/darwin-arm64/golangci-lint run ./...
pkg/config/config.go:12:2: import 'github.com/go-logr/logr' is not allowed from list 'Main' (depguard)
"github.com/go-logr/logr"
^
[...]
controllers/datadogagent/clusteragent.go:1459:18: fmt.Sprintf can be replaced with string addition (perfsprint)
MatchPattern: …
```
> chore(golangci-lint): bump from v1.51.0 to v1.56.0

- apis/datadoghq/v2alpha1/test/builder.go
- controllers/datadogagent/feature/apm/feature.go
- controllers/datadogagent/feature/apm/feature_test.go
- controllers/datadogagent/feature/dogstatsd/feature.go
- controllers/datadogagent/feature/dogstatsd/feature_test.go
- controllers/datadogagent/feature/dogstatsd/feature_v1alpha1_test.go
Fix custom host port settings for APM and DSD. The current behavior changes the env vars for APM and DSD that tell the agent which ports to listen on so the agent could be listening on port #### when even though the custom host port is mapped to 8125 or 8126 in the container. Now, we only change the host port mapping so that custom host port #### will map to 8125 or 8126 in the container.
DatadogAgent manifest:
```yaml
dogstatsd:
hostPortConfig:
enabled: true
hostPort: 8128
apm:
hostPortConfig:
enabled: true
hostPort: 8129
```
Agent:
```yaml
name: agent
env:
- name: DD_DOGSTATSD_PORT
value: "8125"
ports:
- containerPort: 8125
hostPort: 8128
name: dogstatsdport
protocol: UDP
name: trace-agent
env:
- name: DD_APM_RECEIVER_PORT
value: "8129"
ports:
- containerPort: 8126
hostPort: 8129
name: …
```
> Fix hostport custom port settings

- controllers/datadogagent/controller_reconcile_agent_test.go
- controllers/datadogagent/feature/oomkill/feature.go
- controllers/datadogagent/feature/tcpqueuelength/feature.go
- pkg/kubernetes/provider.go
- pkg/kubernetes/provider_test.go
> Clean up cos_containerd provider name (#1077)

- apis/datadoghq/v2alpha1/datadogagent_types.go
- apis/datadoghq/v2alpha1/zz_generated.deepcopy.go
- config/crd/bases/v1/datadoghq.com_datadogagents.yaml
- config/crd/bases/v1beta1/datadoghq.com_datadogagents.yaml
- controllers/datadogagent/clusteragent.go
- controllers/datadogagent/component/agent/rbac.go
- controllers/datadogagent/component/clusterchecksrunner/default.go
- controllers/datadogagent/feature/enabledefault/feature.go
- docs/configuration.v2alpha1.md
> [cherry-pick] add option in DatadogAgent CRD to disable nonResourceRules (#1074)

- apis/datadoghq/common/const.go
- apis/datadoghq/common/envvar.go
- controllers/datadogagent/agent_test.go
- controllers/datadogagent/feature/dogstatsd/feature.go
- controllers/datadogagent/feature/dogstatsd/feature_test.go
- controllers/datadogagent/feature/dogstatsd/feature_v1alpha1_test.go
- controllers/datadogagent/utils.go
Adds the setting needed to activate Origin Detection with DogStatsD and UDP.
We would like for our customer to use Origin Detection more easily without having to set custom environment variables manually.
Build and deploy the operator to a Kubernetes cluster
```
make build
make IMG=test/operator:test IMG_CHECK=test/operator-check:test docker-build
make IMG=test/operator:test IMG_CHECK=test/operator-check:test docker-push
make IMG=test/operator:test IMG_CHECK=test/operator-check:test deploy
```
Create a `datadog-secret`
```
kubectl create secret generic datadog-secret --from-literal api-key=$DD_API_KEY --from-literal app-key=$DD_APP_KEY --namespace system
```
Apply a manifest with the following (you need an agent running version `7.51.0`)
``` …
```
> feat(dogstatsd): activate Origin Detection with UDP

- controllers/datadogagent/component/clusterchecksrunner/default.go
As a follow-up to https://github.com/DataDog/datadog-operator/pull/910, we want to be able to query the SLI metrics URL from cluster check runners as well.
This change is necessary to support the corresponding changes to the control plane checks to support SLI metrics.
1. `make build`
2. `make docker-build`
3. `make deploy`
4. I then applied a manifest with cluster check workers enabled, and verified that the datadog-cluster-checks-runner cluster role changes were applied appropriately
> Add SLI metrics URL to clc rbac

- controllers/datadogagent/controller.go
- controllers/datadogagent/controller_reconcile_agent.go
- controllers/datadogagent/controller_reconcile_v2.go
- controllers/datadogagent_controller.go
- controllers/setup.go
- controllers/suite_v2_test.go
- main.go
- pkg/agentprofile/agent_profile.go
- pkg/agentprofile/agent_profile_test.go
Adds a flag `datadogAgentProfileEnabled` to enable DAP. It is disabled by default
With no DAP CRD, introspection disabled, and DAP disabled
```shell
$ kubectl get pod
NAME                                       READY   STATUS    RESTARTS   AGE
datadog-agent-n5wrx                        3/3     Running   0          31s
datadog-agent-ztrwf                        3/3     Running   0          31s
datadog-cluster-agent-77654c4599-z7bz9     1/1     Running   0          31s
operator-datadog-operator-9f9986b9-zr6gg   1/1     Running   0          4m52s
$ kubectl get ds
NAME            DESIRED   CURRENT   READY   UP-TO-DATE   AVAILABLE   NODE SELECTOR   AGE
datadog-agent   2         2         2       2            2           <none>          46s
```
Enable introspection
```shell
$ kubectl get pod …
```
> [profiles][CECO-925] Add flag to enable DAP

- apis/datadoghq/v1alpha1/datadogmonitor_types.go
- apis/datadoghq/v1alpha1/zz_generated.openapi.go
- config/crd/bases/v1/datadoghq.com_datadogmonitors.yaml
- config/crd/bases/v1beta1/datadoghq.com_datadogmonitors.yaml
- controllers/datadogmonitor/monitor.go
- controllers/datadogmonitor/monitor_test.go
* Provides the `on_missing_data` monitor option https://registry.terraform.io/providers/DataDog/datadog/latest/docs/resources/monitor#on_missing_data
* Closes https://github.com/DataDog/datadog-operator/issues/1045
The `on_missing_data` option is only available in certain monitors and while some options are not configured (e.g. can't combine `no_data_timeframe` and `on_missing_data`. The unit test in `monitor_test.go` only tests the monitor can be built and passed to the API go client, ultimately the validation is handled by the API go client, returning a `4xx` if invalid.
N/A
1. Apply new CRD `k apply -f config/crd/bases/v1/datadoghq.com_datadogmonitors.yaml`
2. Install custom image with Helm, enabling monitors controller :
```yaml
apiKeyExistingSecret: datadog-secret …
```
> feat: add OnMissingData to monitor options

- .gitlab-ci.yml
- hack/publish-community-bundles.sh
Fix/simplify `hack/publish-community-bundles.sh` script to properly invoke make target from gitlab job. 
Broken make syntax in ci
> Fix publish-community-bundles script

- .gitlab-ci.yml
The migration from docker runners to k8s runners in https://github.com/DataDog/datadog-operator/pull/1056 was incomplete, this fixes the remaining `docker tag` calls.
> [gitlab] replace docker tag calls for k8s runners

- .gitlab-ci.yml
- Makefile
Load bundle image after building
> [gitlab] load bundle image

- controllers/datadogagent/component/agent/default.go
- controllers/datadogagent/component/agent/new.go
- controllers/datadogagent/controller_reconcile_agent.go
Propagate the `edsMaxPodUnavailable` value to DSs if the arg is set in the operator. When using profiles, only the default profile uses an EDS; the others use DSs. Since we use default k8s DS values, the rollingUpdate strategy for maxUnavailable pods is `1`, which causes rollouts to be very slow
Internal request
* Agent: n/a
When `edsMaxPodUnavailable` is not set, the default value for `maxUnavailable` should be used in a DS:
```
updateStrategy:
rollingUpdate:
maxSurge: 0
maxUnavailable: 1
type: RollingUpdate
```
After enabling EDSs, profiles, and setting `edsMaxPodUnavailable=3%`, the EDS should have:
```
rollingUpdate:
maxParallelPodCreation: …
```
> [CECO-1015] Propagate edsMaxPodUnavailable value to DS

- controllers/datadogagent/controller_reconcile_agent.go
- controllers/datadogagent_controller.go
Deletes the pod index used for the profiles feature. It seems that it causes an initial memory spike and it's not really needed anymore. This PR rewrites the `cleanupPodsForProfilesThatNoLongerApply` so that it doesn't rely on the index and to my knowledge the behavior and performance should be roughly the same except for that initial memory spike that no longer happens.
Try with profiles enabled. Check that the memory spike at startup that we observed no longer happens.
> [profiles] Stop using pod indexer

- config/default/kustomization.yaml
Follow up to #1107 . This fixes an unresolved annotation on the DatadogAgent CRD
> [tooling] small fix for bundle generation (certs)

- pkg/agentprofile/agent_profile.go
Log line formatting was not correct.
Before: `{"level":"INFO","ts":"2024-03-07T19:44:50Z","logger":"controllers.DatadogAgent","msg":"profile %s conflicts with existing profile %s, skipping","datadogagent":"default/datadog","default/dap-conflict":"default/dap-test"}`
After: `{"level":"INFO","ts":"2024-03-07T19:55:56Z","logger":"controllers.DatadogAgent","msg":"conflict with existing profile, skipping","datadogagent":"default/datadog","conflicting profile":"default/dap-conflict","existing profile":"default/dap-test"}`
* Agent: n/a
Enable profiles, and add 2 profiles that target the same node. The …
> Fix log line formatting for conflicting profiles

- controllers/datadogagent/feature/helmcheck/feature.go
- controllers/datadogagent/feature/helmcheck/feature_test.go
Add md5 hash annotation to helm check configMap and cluster agent pod template spec for helm check config changes.
QA https://github.com/datadog/datadog-operator/pull/1060
Helm check config changes were not being taken into account by the cluster agent/CCR and the cluster agent and CCR pods were not restarting after config changes. 
QA steps for https://github.com/datadog/datadog-operator/pull/1060 + 
* `datadog-helm-check-config` configmap should have the annotation `checksum/helm_check-custom-config: <md5_hash>`
* Change any helmCheck config other than `helmCheck.enabled`: e.g 
* `helmCheck.collectEvents: true` to …
> Add md5 hash config annotation to helm check

- controllers/datadogagent/feature/sbom/feature.go
- controllers/datadogagent/feature/sbom/feature_test.go
This change make sure that we inject SBOM related env vars only to core agent container.
Since https://github.com/DataDog/datadog-operator/pull/1044 the `HOST_ROOT` injected for `security-agent` was wrongly set to `/host` instead of `/host/root`. By limiting the env vars to the core agent container, we should avoid such regressions.
See incident-26035.
> SBOM: limit env injection for SBOM feature to core agent

- controllers/datadogagent/override/container.go
- controllers/datadogagent/override/container_test.go
- controllers/datadogagent/override/utils.go
Fix readinessprobe and livenessprobe for non-nil probehandler overrides. 
Customer case
Fix for bug introduced in #998 
* Configure a DDA `readinessProbe` and/or `livenessProbe` container overrides with non-httpGet probeHandlers:
```
override:
nodeAgent:
containers:
agent:  # should have expected probes
readinessProbe:
exec:
command: ["echo", "ok"]
livenessProbe:
httpGet:
path: /ready
port: 5555
process-agent: # should have expected probes
readinessProbe:
exec:
command: ["echo", "ok"]
livenessProbe:  # should have a default httpGet probeHandler
timeoutSeconds: 30
periodSeconds: 40
```
* Agent pods should not error
* Check the …
> Fix readinessprobe and livenessprobe for non-nil probehandler overrides

- controllers/datadogagent/override/container.go
- controllers/datadogagent/override/container_test.go
- controllers/datadogagent/override/utils.go
> Fix readinessprobe and livenessprobe for non-nil probehandler overrides (#1119)

- Makefile
Pin `setup-envtest` version to prevent test errors:
```
go: sigs.k8s.io/controller-runtime/tools/setup-envtest@latest (in sigs.k8s.io/controller-runtime/tools/setup-envtest@v0.0.0-20240323114127-e08b286e313e): go.mod:3: invalid go version '1.22.0': must match format 1.23
```
> Pin setup-envtest version

- apis/datadoghq/v1alpha1/datadogmonitor_types.go
- apis/datadoghq/v1alpha1/zz_generated.deepcopy.go
- apis/datadoghq/v1alpha1/zz_generated.openapi.go
- config/crd/bases/v1/datadoghq.com_datadogmonitors.yaml
- config/crd/bases/v1beta1/datadoghq.com_datadogmonitors.yaml
- controllers/datadogmonitor/monitor.go
- controllers/datadogmonitor/monitor_test.go
Provides the [notify_by](https://registry.terraform.io/providers/DataDog/datadog/latest/docs/resources/monitor#notify_by), [groupby_simple_monitor](https://registry.terraform.io/providers/DataDog/datadog/latest/docs/resources/monitor#groupby_simple_monitor) & [renotify_occurrences](https://registry.terraform.io/providers/DataDog/datadog/latest/docs/resources/monitor#renotify_occurrences) monitor options
**Closes:**
https://github.com/DataDog/datadog-operator/issues/833
https://github.com/DataDog/datadog-operator/issues/814
`groupby_simple_monitor` only updates Log Monitors. `renotifyOccurrences` requires `renotifyInterval` to be configured. The unit test in monitor_test.go only tests the monitor can be built and passed to the API go client, ultimately the validation is handled by the API …
> Add notify_by, groupby_simple_monitor, & renotify_occurrences config options to monitors crd

- docs/introspection.md
Add updated migration instructions for introspection
> [docs] Add migration instructions for introspection docs

- controllers/datadogagent/controller_reconcile_agent.go
- controllers/datadogagent/controller_reconcile_agent_test.go
- controllers/datadogagent/controller_reconcile_v2.go
Combines DS/EDS cleanup methods for profiles, introspection, and the `cleanupV2DaemonSet/ExtendedDaemonSet` methods
* https://datadoghq.atlassian.net/browse/CECO-848
* Fix bug where old DS/EDSs aren't deleted automatically
This is what was tested locally on a kind cluster. Each shows the output of `kubectl get pods` and then `kubectl get ds`:
No introspection, no profiles
```
NAME                                       READY   STATUS    RESTARTS   AGE
datadog-agent-9fq4t                        3/3     Running   0          77s
datadog-agent-vk8vm                        3/3     Running   0          77s
datadog-cluster-agent-5684d697-mj7d2       1/1     Running   0          77s
operator-datadog-operator-9f9986b9-4k78b   1/1     Running   0          2m51s
NAME            DESIRED   CURRENT …
```
> [CECO-848] Combine DS cleanup methods

- Makefile
Previous:
```
$ docker manifest inspect xxx
{
"schemaVersion": 2,
"mediaType": "application/vnd.oci.image.index.v1+json",
"manifests": [
{
"mediaType": "application/vnd.oci.image.manifest.v1+json",
"size": 1810,
"digest": "sha256:xxx",
"platform": {
"architecture": "arm64",
"os": "linux"
}
},
{
"mediaType": "application/vnd.oci.image.manifest.v1+json",
"size": 566,
"digest": "sha256:xxx",
"platform": {
"architecture": "unknown",
"os": "unknown"
}
}
]
}
```
Now:
```
$ docker manifest inspect xxx
{
"schemaVersion": 2,
"mediaType": "application/vnd.docker.distribution.manifest.v2+json",
"config": {
"mediaType": "application/vnd.docker.container.image.v1+json",
"digest": "sha256:xxx",
"size": 8927
},
"layers": [
{
"mediaType": "application/vnd.docker.image.rootfs.diff.tar.gzip",
"digest": …
```
> Disable provenance in gitlab

- apis/datadoghq/v2alpha1/condition.go
- apis/datadoghq/v2alpha1/condition_test.go
- cmd/check-operator/upgrade/upgrade.go
- controllers/datadogagent/controller_reconcile_agent.go
- controllers/datadogagent/controller_reconcile_ccr.go
- controllers/datadogagent/controller_reconcile_dca.go
- controllers/datadogagent/controller_reconcile_v2.go
* Always update the `DatadogAgent` call the function that might update the status in the controller functions.
* Cleanup status when a component is disabled
* Make the logs more informative in the `check-operator` binary.
the `DatadogAgent.Status` was not always updated to reflect the fact an error was remove
During a deployment the `check-operator` process that is use to validate the agent deployment/upgrade was always failing with the following logs error
```
[2024-04-27T06:52:05.998Z] DatadogAgent 'datadog-agent/datadog-agent': Start checking rolling-update status
[2024-04-27T06:52:36.016Z] DatadogAgent 'datadog-agent/datadog-agent': v2alpha1 is available
Error: got reconcile error
```
Which means that a condition is in an error state in `DatadogAgent.status.conditions`. In the …
> fix(controller): always try to update status

- apis/datadoghq/v2alpha1/condition.go
- apis/datadoghq/v2alpha1/condition_test.go
- cmd/check-operator/upgrade/upgrade.go
- controllers/datadogagent/controller_reconcile_agent.go
- controllers/datadogagent/controller_reconcile_ccr.go
- controllers/datadogagent/controller_reconcile_dca.go
- controllers/datadogagent/controller_reconcile_v2.go
* fix(controller): always try to update status
* improve check-operator resiliency
* improve how the status conditions are updated
* Apply suggestions from code review
* Update upgrade.go
* nit
---------
> [cherry-pick] fix(controller): always try to update status (#1154)

- apis/datadoghq/v1alpha1/test/new.go
- controllers/datadogagent/agent_test.go
- controllers/datadogagent/clusteragent_test.go
- controllers/datadogagent/component/agent/default.go
- controllers/datadogagent/component/clusteragent/default.go
- controllers/datadogagent/component/utils.go
- pkg/controller/utils/shared_utils.go
Move generation of DD_INSTALLATION_ID and DD_INSTALLATION_TIME from Datadog Operator to using values generated during DatadogAgent creation.
https://datadoghq.atlassian.net/browse/CECO-1087
1. Created Datadog Operator image with the PR change. Deployed it to the test cluster together with DatadogAgent CRD.
2. Ran kubectl apply -f datadog-agent.yaml to. create CR, DA and DCA.
On CR:
```
metadata:
annotations:
kubectl.kubernetes.io/last-applied-configuration: |
{"apiVersion":"datadoghq.com/v2alpha1","kind":"DatadogAgent","metadata":{"annotations":{},"name":"datadog","namespace" …
```
> [APM Onboarding] Use creation timestamp and UID of DatadogAgent as env vars for APM Telemetry KPIs

- apis/datadoghq/v1alpha1/test/new.go
- controllers/datadogagent/agent_test.go
- controllers/datadogagent/clusteragent_test.go
- controllers/datadogagent/component/agent/default.go
- controllers/datadogagent/component/clusteragent/default.go
- controllers/datadogagent/component/utils.go
- pkg/controller/utils/shared_utils.go
> [APM Onboarding] Use creation timestamp and UID of DatadogAgent as env vars for APM Telemetry KPIs (#1157)

- controllers/datadogagent/feature/cspm/feature.go
- controllers/datadogagent/feature/cws/feature.go
- controllers/datadogagent/feature/ebpfcheck/feature.go
- controllers/datadogagent/feature/npm/feature.go
- controllers/datadogagent/feature/oomkill/feature.go
- controllers/datadogagent/feature/tcpqueuelength/feature.go
- controllers/datadogagent/feature/usm/feature.go
- controllers/datadogagent/merger/envvars.go
- controllers/datadogagent/merger/fake/envvar_manager.go
Add system probe envvars needed in core agent container, such as `DD_SYSPROBE_SOCKET` and `DD_SYSTEM_PROBE_ENABLED`
Add socket mount to core agent container where it is missing
Add new function to envvar manager `AddEnvVarToContainers` so that envvars can be added to multiple containers with a single function
> [remote-config] add envvars missing from core agent for system probe features

- bundle/manifests/datadog-operator.clusterserviceversion.yaml
- config/manager/manager.yaml
Add annotation to configure Openmetrics check on Datadog Operator pod when deployed with OLM.
Deploy Datadog Operator with OLM
Deploy a minimal DatadogAgent manifest
Check the `agent status` output that datadog.operator.* metrics are being collected
Check the web app to confirm metrics are reporting
> [bundle] add openmetrics check annotation

- controllers/datadogagent/controller_reconcile_v2_common.go
- controllers/datadogagent/controller_reconcile_v2_common_test.go
Allows node label overrides for daemonsets when updating DDAs. After creating a DDA, subsequent changes to the node agent label overrides weren't being propagated to the agent pods.
CECO-1109
Fixes https://github.com/DataDog/datadog-operator/issues/1156
* Agent: n/a
1. Testing label overrides with 1.7.0+:
* Create a DDA with or without node agent label overrides
* Add a label to modify the value of one of the label selectors on the daemonset
```yaml
override:
nodeAgent:
labels:
"agent.datadoghq.com/name": "bar"
```
* Check that the label on the agent pod remains the same as the label selector (`agent.datadoghq.com/name=datadog` instead of `agent.datadoghq.com/name=bar`) and that this log is …
> [CECO-1109] Allow label overrides for ds for DDA updates

- examples/datadogagent/v2alpha1/datadog-agent-all.yaml
- examples/datadogagent/v2alpha1/datadog-agent-minimum.yaml
- examples/datadogagent/v2alpha1/datadog-agent-on-openshift.yaml
- examples/datadogagent/v2alpha1/datadog-agent-with-apm-hostport.yaml
- examples/datadogagent/v2alpha1/datadog-agent-with-clusteragent.yaml
- examples/datadogagent/v2alpha1/datadog-agent-with-dca-clusterchecksrunner.yaml
- examples/datadogagent/v2alpha1/datadog-agent-with-dca-with-orchestrator-explorer.yaml
- examples/datadogagent/v2alpha1/datadog-agent-with-extraconfd.yaml
- examples/datadogagent/v2alpha1/datadog-agent-with-logs-apm.yaml
- examples/datadogagent/v2alpha1/datadog-agent-with-otlp.yaml
- examples/datadogagent/v2alpha1/datadog-agent-with-remote-configuration.yaml
- examples/datadogagent/v2alpha1/datadog-agent-with-secret-backend.yaml
- examples/datadogagent/v2alpha1/datadog-agent-with-secret-keys.yaml
- examples/datadogagent/v2alpha1/datadog-agent-with-tolerations.yaml
- examples/datadogagent/v2alpha1/datadog-agent-with-unix-socket.yaml
Add clusterName to all v2alpha examples.
While implementing on Azure Redhat OpenShift, we used the example and had to add clusterName to properly view the data in our Kubernetes Overview page. 
It is a known issue that without the clusterName, the Kubernetes explorer will not be useful as nothing will show besides the container view.  
> Add cluster name to all v2alpha examples

- PROJECT
Add Datadog SLO api to PROJECT file
The Datadog SLO crd tile is not displaying the expected metadata in operatorhub: https://operatorhub.io/operator/datadog-operator/stable/datadog-operator.v1.5.0
Pre 1.7.0 RC (skip this if testing with the 1.7.0 RC and proceed to checking the CSV files):
* Cherry-pick commit onto the v1.6 branch
* Run `make VERSION=1.6.0-rc.1 LATEST_VERSION=1.6.0 bundle`
Check that Datadog SLO is present in `config/manifests/bases/datadog-operator.clusterserviceversion.yaml` and in `bundle` and `bundle-community-operators` CSV files
```
+    - description: DatadogSLO allows a user to define and manage datadog …
```
> Add Datadog SLO to PROJECT

- main.go
Remove deprecated flag.
In a subsequent PR, references to `V2Enabled` will be removed.
Ensure v2alpha1 DatadogAgent CR reconciles as expected.
> remove deprecated v2alpha1 flag

- apis/datadoghq/common/envvar.go
- controllers/datadogagent/feature/enabledefault/feature.go
- controllers/datadogagent/feature/enabledefault/feature_test.go
Add an env var that can override the node agent's install info tool version
CECO-1183
* In a cluster, check that the `tool_version` in the created install info configmap defaults to `datadog-operator`
* Set the env var `DD_TOOL_VERSION` with a non-empty string value in the operator pod
* After the new operator becomes leader, check that the install info config map `tool_version` value changed
* Restart the agent pod so it reads from the updated configmap
* Check that the tool version changed to whatever the value of `DD_TOOL_VERSION` is (`install_method_tool_version` when running `agent status`)
> [CECO-1183] Override install info tool version

- repository.datadog.yml
This PR adds the same Merge Queue configuration as the [Helm Chart](https://github.com/DataDog/helm-charts) repository.
This is needed to be able to merge using Merge Queue.
> chore(mergequeue): add configuration

- pkg/remoteconfig/updater.go
This PR adds the right `ID` field to the agentConfigData Struct
> Fix agentConfig struct

- controllers/datadogagent/controller_reconcile_v2_common.go
https://github.com/DataDog/datadog-operator/pull/1173 was merged to fix label overrides for pod templates in daemonsets. It caused unnecessary update requests each reconcile since it recalculated the pod template spec from the existing daemonset to compare to the operator-generated daemonset. Kubernetes would fill in values in the existing daemonset, which meant the hashes would always be different and the operator would attempt to update the daemonset even when there were no functional changes.
An example of one of the differences in the existing daemonset where kubernetes added a default value and the operator-generated daemonset:
Existing daemonset:
```
{Name:DD_KUBERNETES_KUBELET_HOST Value: ValueFrom:&EnvVarSource{FieldRef:&ObjectFieldSelector{APIVersion: ,FieldPath:status.hostIP,} …
```
> Compare label hashes instead of recalculating spec hash for daemonsets

- config/crd/kustomization.yaml
- config/default/kustomization.yaml
- config/manager/manager.yaml
- hack/patch-bundle.sh
Comment out lines pertaining to webhook conversion that are no longer needed 
See team doc about testing in Openshift
Test that upgrades from bundle 1.6.0 -> 1.7.0 succeed with a DatadogAgent deployed
Test that upgrades from bundle 1.6.0 -> 1.8.0 (a dummy bundle) have an intermediary upgrade to 1.7.0 first
> remove webhook conversion and certmanager references from bundle

- controllers/datadogslo/controller.go
- controllers/datadogslo/controller_test.go
- controllers/datadogslo_controller.go
- controllers/utils/tag.go
Update reconcile code to 1) not continue reconciling if tags have been updated; 2) set `LastForceSyncTime` on create and update, so that the status update does not trigger a reconcile; and 3) for good measure, add the GenerationChanged predicate filter so that any status-only updates do not trigger a reconcile.
Address #1062 .
> [SLO] fix reconcile bugs, add predicate to builder

- README.md
- controllers/setup.go
Adds log line about upcoming `v1beta1` CRD deprecation and warning in the readme.
Readme warning preview:
> [!WARNING]
> Operator release v0.1.7 removes support for DatadogAgent `v1alpha1` reconciliation (`v2APIEnabled` flag). v0.1.8 will remove conversion webhook as well and users will not be able to apply DadadogAgent `v1alpha1` manifest.
> 
> Operator release v1.8.0 will deprecate CRDs of `apiextensions.k8s.io/v1beta1` version. They will be kept in the repo but will not be updated. They will be removed in release v1.10.0.  
Write there any instructions and details you may have …
> Add v1beta1 CRD deprection warning

- pkg/defaulting/images.go
This PR is for upgrading default agent image version to 7.54.0.
Testing label overrides with 1.7.0+:
- Create a DDA with basic configuration
```
metadata:
name: datadog
spec:
global:
clusterName: my-example-cluster
credentials:
apiKey: <DATADOG_API_KEY>
```
- Check If the agent and cluster agent image tag are set to 7.54.0
- kubectl describe pod <AGENT_POD> | grep -i Image:
```
k describe pod <AGENT_POD> | grep -i Image:
Image:         gcr.io/datadoghq/agent:7.54.0
Image:         gcr.io/datadoghq/agent:7.54.0
Image: …
```
> Bump agent image versions to 7.54

- controllers/datadogagent/feature/kubernetesstatecore/configmap.go
* As with the Helm installation (https://github.com/DataDog/helm-charts/blob/bde0d7084967bc5e3b7177b642b168d7e09a97f0/charts/datadog/templates/_kubernetes_state_core_config.yaml#L41), aligns the default KSM Core ConfigMap : addition of pdbs, storageclasses & volumeattachments
* Customer request : https://datadog.zendesk.com/agent/tickets/1711557
* No additional RBACs are required as they were already present : 
* PDB Operator RBAC : https://github.com/DataDog/datadog-operator/blob/a900de12525356d6f1fb6fdc7915dea8aee907b9/config/rbac/role.yaml#L521-L532
* PDB KSM RBAC : https://github.com/DataDog/datadog-operator/blob/a900de12525356d6f1fb6fdc7915dea8aee907b9/controllers/datadogagent/feature/kubernetesstatecore/rbac.go#L67-L70
* storageclasses and volumeattachments Operator RBAC : …
> [DatadogAgent] Aligns KSM Core default ConfigMap with Helm : adds pdbs, storageclasses, volumeattachments

- docs/configuration.v1alpha1.md
- docs/configuration.v2alpha1.md
- hack/generate-docs/header.markdown
- hack/generate-docs/v1alpha1_footer.markdown
- hack/generate-docs/v2alpha1_footer.markdown
Fix dead links for example DDAs on https://github.com/DataDog/datadog-operator/blob/main/docs/configuration.v2alpha1.md. The `Manifest with Logs and metrics collection enabled` example file was removed entirely so I removed that link.
https://github.com/DataDog/datadog-operator/issues/1176
> Fix dead links for DDA v2alpha1 examples

- apis/datadoghq/v2alpha1/test/builder.go
- controllers/datadogagent/feature/admissioncontroller/feature_test.go
This PR is for refactoring cwsInstrumentation test in admission controller test file.
What inspired you to submit this pull request? 
It's a follow-up PR for refactoring admission controller test code #1207 
- tested with release v1.7.0
- Run the admissionController feature_test.go
- Check the result is OK.
```
Running tool: /opt/homebrew/bin/go test -timeout 30s -run ^Test_admissionControllerFeature_Configure$ github.com/DataDog/datadog-operator/controllers/datadogagent/feature/admissioncontroller
ok  	github.com/DataDog/datadog-operator/controllers/datadogagent/feature/admissioncontroller	0.670s
```
> Refactoring cwsInstrumentation test in AC test

- config/rbac/role.yaml
Update cluster role for https://github.com/DataDog/datadog-operator/pull/1146
Deploy the operator with `make deploy`.
Enable `admissionController.cwsInstrumentation` and make sure there are no RBAC errors like the following:
```
{"level":"ERROR","ts":"2024-06-04T18:17:32Z","msg":"Reconciler error","controller":"datadogagent","controllerGroup":"datadoghq.com","controllerKind":"DatadogAgent","datadogAgent":{"name":"datadog","namespace":"system"},"namespace":"system","name":"datadog","reconcileID":"acfb8cb6-e425-4e62-954b-4b2e3e051a63","error":"clusterroles.rbac.authorization.k8s.io …
```
> [kustomize] update operator manager rbac

- .github/workflows/build.yml
- .github/workflows/release.yaml
Update goreleaser args following v2 release according to https://goreleaser.com/deprecations/#-skip
> [tooling] update goreleaser skip flag

- config/manager/manager.yaml
- hack/patch-bundle.sh
- hack/redhat-bundle.sh
Add custom tool version for community operators. Key is `DD_TOOL_VERSION`, value changes based on the bundle:
1. k8s-operatorhub/community-operators: `operatorhub`
2. community-operators-prod: `redhat`
3. redhat-marketplace-operators: `redhat`
4. certified-operators: `redhat`
CECO-1184
* Run the bundle command `make VERSION=X.Y.Z LATEST_VERSION=X.Y.Z bundle` and check that the `DD_TOOL_VERSION` env var is in the `bundle` and `bundle-community-operators` clusterserviceversion files. The `bundle`'s value should be `redhat`. The `bundle-community-operators`'s value should be `operatorhub`
* Run `make bundle-redhat` (X.Y.Z must be …
> [CECO-1184] Add tool version for community operators

- main.go
- pkg/remoteconfig/updater.go
- In main.go, add a blocking call if the replica is not the leader
- In updater.go, clear the status parameter if corresponding rc parameter is empty
> [remote config] Respect leader election and update Status.RemoteConfigConfiguration if parameters are empty

- main.go
- pkg/remoteconfig/updater.go
* Have remote config respect leader election
* clear status params if corresponding config is empty
> [remote config] Respect leader election and update Status.RemoteConfigConfiguration if parameters are empty (#1228)

- main.go
In Operator v1.8 we will upgrade `controller-runtime` and Kubernetes API dependencies which only supports `leases` as leader election resource lock.
> Set LeaderElectionResourceLock to `leases` and remove `leader-election-resource` parameter

- docs/remote_config.md
Add doc about RemoteConfig feature
> [remoteconfig][beta] add doc

- controllers/datadogagent/controller_reconcile_v2.go
- controllers/metrics/const.go
- controllers/metrics/datadogagent.go
- controllers/metrics/datadogagentprofile.go
Adds metrics to indicate whether introspection and dap are enabled or not.
```
datadogagent_introspection_enabled 0
datadogagentprofile_enabled 1
```
In app metrics would be:
* `datadog.operator.datadogagent_introspection_enabled`
* `datadog.operator.datadogagentprofile_enabled`
CECO-1154
CECO-1155
* Deploy operator without introspection or profiles enabled. Check that those metrics report `0`
* Enable introspection and/or profiles. Check that the enabled feature(s) now shows metric value `1`
> [CECO-1154][CECO-1155] Add introspection and dap enabled metrics

- Makefile
With this change Operator will stop updating `v1beta1` versions of the CRDs but they will be kept in the repo.
`v1beta1` CRD versions will be removed in the Operator v1.10. 
> Stop generating `v1beta1` CRD versions

- .devcontainer/devcontainer.json
Fixes and updates the Development Container to the current Go version and add some configurations to ease development process.
The current dev container does not work with the following error messages:
```
bin/linux-aarch64/openapi-gen: /lib/aarch64-linux-gnu/libc.so.6: version `GLIBC_2.34' not found (required by bin/linux-aarch64/openapi-gen)
bin/linux-aarch64/openapi-gen: /lib/aarch64-linux-gnu/libc.so.6: version `GLIBC_2.32' not found (required by bin/linux-aarch64/openapi-gen)
```
It is also out-dated.
Build the devcontainer
```
➜  datadog-operator git:(wassim.dhif/devcontainer) devcontainer up --workspace-folder .
[1 ms] @devcontainers/cli 0.64.0. Node.js v22.2.0. darwin 23.5.0 arm64.
[312 ms] Resolving Feature dependencies for …
```
> chore(devcontainer): improve devcontainer and upgrade Go version

- Makefile
This reverts commit 6168a7aa17ff772a01df73f77f0b26b4122246f6.
Earlier commit wasn't properly tested, it contained a bug which hid issues with upgrade. This will likely be updated together with project version and operator-sdk.
> Revert "Bump kustomize version (#1250)"

- controllers/datadogagent/component/clusteragent/default.go
- controllers/datadogagent/component/clusteragent/default_test.go
Adds liveness and readiness probes to cluster agent. 
https://datadoghq.atlassian.net/browse/CECO-1191
This CRD was used:
```
metadata:
name: datadog
spec:
override:
nodeAgent:
containers:
trace-agent:
livenessProbe: 
httpGet:
path: /live
port: 7929
scheme: HTTP
initialDelaySeconds: 15
readinessProbe:
httpGet:
path: /live
port: 7929
scheme: HTTP
initialDelaySeconds: 15
global:
clusterName: kind-control
kubelet:
credentials:
apiSecret: …
```
> Added liveness and readiness probes (+ tests) to DCA

- controllers/datadogagent/feature/externalmetrics/feature.go
When the External Metrics Server is set to not register an API Service, we were not creating other RBACs needed for the EMS. This PR fixes that issue.
Bug fix
> [external metrics] fix configuration when registerAPIService is false

- Makefile
- bundle/manifests/datadoghq.com_datadogagentprofiles.yaml
A couple small fixes to the bundle on `main` and testing workflow:
- Add datadog agent profile CRD to `main` branch, this was missed inadvertently
- update `make` task to build and push bundle for testing to create a multiarch image
Ease of testing
> add datadog agent profiles CRD to bundle, and update bundle make command to build multiarch image

- docs/cluster_agent_setup.md
- docs/configuration.v2alpha1.md
- docs/getting_started.md
- docs/how-to-contribute.md
- hack/generate-docs/v2alpha1_footer.markdown
Fix links that were broken due to https://github.com/DataDog/datadog-operator/pull/1258
> [docs] fix broken links to examples

- .gitlab-ci.yml
- Makefile
- config/manifests/bases/datadog-operator.clusterserviceversion.yaml
- Update publish redhat jobs to use public-images tool
- Consolidate preflight checks into one. This now supports a multiarch image, so we will run the check/submit together with the pushed Redhat image after it's been pushed.
- Update CSV labels to indicate arch support
> [gitlab] add support for multiarch images in redhat

- apis/datadoghq/v1alpha1/datadogagentprofile_validation.go
- apis/datadoghq/v1alpha1/datadogagentprofile_validation_test.go
Remove validation that requires container resources to be configured in a profile. It should be possible to use profiles to override priorityClassName or env vars without needing to specify a container resource
https://datadoghq.atlassian.net/browse/CECO-1276
* Agent: n/a
* Deploy a profile with only priorityClassName or env var overrides set. There shouldn't be a validation error in the logs and the profile should be applied with the proper override
> [profiles] Remove validation for container resource

- Makefile
Pin version of kube-openapi. Dependabot is installing a newer version that doesn't have some of the flags used for our current build command:
```
k8s.io/kube-openapi v0.0.0-20240228011516-70dd3763d340
```
Other PRs use this version:
```
k8s.io/kube-openapi v0.0.0-20230717233707-2695361300d9
```
Seeing if pinning the version to the older one helps dependabot
> Pin kube-openapi version

- .github/dependabot.yaml
- go.mod
Run `go mod tidy` and add `qa/skip-qa` label for dependabot
build failure on dependabot prs
> Run go mod tidy and add dependabot label

- config/manager/kustomization.yaml
The `config/manager/kustomization.yaml` seems malformed therefor it causes this issue when trying to deploy:
```
Error: accumulating resources: accumulation err='accumulating resources from '../manager': '/Users/wassim.dhif/go/src/github.com/DataDog/datadog-operator/config/manager' must resolve to a file': couldn't make target for path '/Users/wassim.dhif/go/src/github.com/DataDog/datadog-operator/config/manager': error converting YAML to JSON: yaml: line 4: did not find expected key
```
Fix `make deploy` issue.
Run the `make deploy` command
```
➜  datadog-operator git:(dev/wassim.dhif/upgrade-devcontainer) ✗ make IMG=wdhifdatadog/operator IMG_CHECK=wdhifdatadog/operator-check deploy && kubectl create secret generic datadog-secret --from-literal api-key=$DD_API_KEY --from-literal …
```
> fix(kustomization): fix deploy file

- controllers/datadogagent_controller.go
- go.mod
Adds more conditionals to make make watch nodes more restrictive since we only need it for introspection or profiles
https://datadoghq.atlassian.net/browse/CECO-1267
* Agent: n/a
* Deploy the operator with either introspection or profiles enabled
* Changing node labels should cause an extra reconcile
* Deploy the operator without introspection and profiles enabled
* Changing node labels shouldn't cause a reconcile
> Watch nodes if profiles or introspection is enabled

- apis/datadoghq/common/common.go
- apis/datadoghq/common/const.go
- controllers/datadogagent/agent_test.go
- controllers/datadogagent/clusteragent_test.go
- controllers/datadogagent/component/agent/default.go
- controllers/datadogagent/component/clusteragent/default.go
- controllers/datadogagent/component/clusteragent/default_test.go
- controllers/datadogagent/component/clusterchecksrunner/default.go
Adds Kubernetes startup probe support for:
* Agent
* Cluster Agent
* Cluster Check Runner
This is needed to add support for the new Kubernetes Startup probe for the Agent components.
Note that currently the `/startup` endpoint is returning the default `/health` endpoint. Support for the dedicated `/startup` endpoint has been added in Agent `7.55`. No components currently register a startup health check.
* Deploy the Operator
```
➜  datadog-dev git:(main) ✗ k get pod
NAME                                             READY   STATUS    RESTARTS   AGE
datadog-agent-8mmmp                              5/5     Running   0          4m10s
datadog-cluster-agent-6f58f64977-pjvhs …
```
> feat(probe): add startup probes

- .devcontainer/devcontainer.json
- .github/CODEOWNERS
Upgrade devcontainer to Go `1.22` after https://github.com/DataDog/datadog-operator/pull/1247.
It also changes the `CODEOWNERS` file to have this being managed by @DataDog/container-platform and @DataDog/container-ecosystems.
Needed to keep building the Operator using the devcontainer.
* Building the devcontainer
```
➜  datadog-operator git:(dev/wassim.dhif/upgrade-devcontainer) ✗ devcontainer up --workspace-folder .
[1 ms] @devcontainers/cli 0.65.0. Node.js v22.3.0. darwin 23.5.0 arm64.
[830 ms] Resolving Feature dependencies for 'ghcr.io/devcontainers/features/docker-outside-of-docker:1'...
[2029 ms] Soft-dependency 'ghcr.io/devcontainers/features/common-utils' is not required.  Removing from installation order...
[2350 ms] Start: Run: docker buildx build --load --build-context …
```
> chore(devcontainer): bump Go version to 1.22

- .github/CODEOWNERS
Remove @DataDog/container-integrations from CODEOWNERS
The split between @DataDog/container-integrations and @DataDog/container-ecosystems is done since 2 years now.
I think it is time to remove the #container-integrations for the owner of this repository. Thanks to this change it will be more clear who is mandatory to review the pull request.
I think we should start to add each product team as in the CODEOWNERS of each features. So they get automatically added to the code review if someone modify their code.
> Update CODEOWNERS remove container-integrations from owners

- Makefile
Update make bundle command to include `--apis-dir` flag during the manifest generation step.
Since upgrading operator-sdk to `v1.34.1`, the `make bundle` command's manifest generation step removes the `displayName` and `description` for some CRDs. 
Run `make VERSION=x.y.z LATEST_VERSION=x.y.z bundle` and make sure the DatadogAgentProfile and DatadogSLO crds still have the `displayName` and `description` field under `spec.customresourcedefinitions.owned` in the `bundle/manifests/datadog-operator.clusterserviceversion.yaml` file.
> Update make bundle command to include `--apis-dir` flag

- apis/datadoghq/common/const.go
- apis/datadoghq/common/v1/types.go
- config/manager/manager.yaml
- controllers/datadogagent/component/agent/default.go
- controllers/datadogagent/controller.go
- controllers/datadogagent/feature/enabledefault/feature.go
- controllers/datadogagent/feature/types.go
- controllers/datadogagent/merger/utils.go
- controllers/setup.go
- main.go
This change adds minimal OTel agent container with minimal defaults in Operator. It's enabled by `otelAgentEnabled` argument (disabled by default).
To test locally off this branch you'll need a Kind cluster and Go 1.22:
```
make build && make docker-build
kind load docker-image --name mycluster $(make -s echo-img)
make deploy
kubens system
kubectl create secret generic datadog-secret --from-literal api-key=API_KEY
kubectl apply -f agent.yaml
kubectl apply -f otel-cm.yaml
```
Enabled internal testing while working on adding OTel feature and agent configs to the CRDs.
Verified that OTel agents starts and reaches running state …
> Add minimal OTel Agent container

- Makefile
- config/rbac/role.yaml
- controllers/datadogagent_controller.go
Fix path for controller_gen generate-manifests. This fixes the RBACs configured for the controller manager
Adds one missing kubebuilder tag
Deploy Datadog Operator with a DatadogAgent (most/all features enabled), ensure there are no RBAC errors in the logs.
> fix generated controller manager rbacs

- service.datadog.yaml
Add Datadog Operator service catalog file
> add service catalog file

- controllers/datadogagent/clusteragent_test.go
- controllers/datadogagent/component/clusteragent/default.go
- controllers/datadogagent/component/clusteragent/default_test.go
- controllers/datadogagent/feature/logcollection/feature.go
Currently Cluster Agent is not aligned with Agent and write `auth_token` to default location (i.e. folder of `datadog.yaml`). This causes issues on read-only filesystem or containers running with random UID (e.g. not `dd-agent` or `root`).
Bugfix
Deploy the Agent on OpenShift or with this security context:
```
override:
clusterAgent:
containers:
cluster-agent:
securityContext:
allowPrivilegeEscalation: false
capabilities:
drop:
- ALL
readOnlyRootFilesystem: false
runAsNonRoot: true
runAsUser: 1000370000
```
Exec in the Cluster Agent POD, running `agent` commands should work `agent status`, for instance.
> Use emptyDir for auth_token in Cluster Agent (aligned with Agent)

- .gitlab-ci.yml
Update nightly Gitlab jobs to trigger from Conductor and to trigger a child deployment pipeline
> update gitlab jobs for nightly deploy

- service.datadog.yaml
Add test instance for conductor
> [conductor] add test target

- controllers/datadogslo/slo.go
- controllers/datadogslo/slo_test.go
CONS-6488
`Quantity.AsApproximateFloat64` does some math to convert Quantity to `float64` needed for SLO API input so some floats may appear with additional decimals. Instead we convert Quantity to Decimal string and then parse as float. This may still have edge cases were string representation doesn't have exact `float64` so conversion isn't 1-to-1.
This impl ignores string to float parsing errors, assuming decimal string obtain from Quantity would be valid.
1. Enabled SLO CRD using `datadogSLOEnabled`
2. Apply SLO manifest and confirm in the app number match (to see …
> Improve resource.Quantity to float conversion for SLOs

- pkg/controller/utils/datadog/metrics_forwarder.go
- pkg/controller/utils/datadog/metrics_forwarder_test.go
Additional cleanup following v1alpha2 deprecation
> [cleanup] rm v2 from function names in metrics forwarder

- service.datadog.yaml
Disable failure notifications for now as it isn't working as expected
Also adjust the notification slack channel 
> [conductor] disable failure notifications for now

- controllers/datadogagent/controller_reconcile_agent.go
- controllers/datadogagent/finalizer.go
Deepcopy the node instead of adding only typemeta and objectmeta. On some nodes, the patch request would try to patch in an empty node status instead of only the modified labels. This attempts to prevent empty node statuses from being a part of the patch request
* Deploy the operator with profiles enabled
* Spin up a profile and check that the nodes targeted by the profile have the `agent.datadoghq.com/datadogagentprofile` label on them
> [profiles] Use deepcopy for patch

- .gitlab-ci.yml
Small fix for gitlab job kicked off by Conductor. Using a different envvar in the rule that seems more reliable.
> [gitlab] fix conductor envvar

- controllers/datadogagent/controller_reconcile_agent.go
- controllers/datadogagent/finalizer.go
* Use deepcopy obj for patch
* Consistent naming
cherry pick #1320
> [profiles] Use deepcopy for patch (#1320)

- .gitlab-ci.yml
- Don't run `test` or `e2e` stages when triggered by Conductor
- Don't publish `main` image when triggered by Conductor
- Set automatic rollout on Conductor trigger of child k8s-datadog-agent-ops pipeline
Trim time spent running Conductor job
Don't use e2e tests which currently error
Automatically start workload publishing without manual intervention
> [gitlab] small fixes for gitlab job rules

- service.datadog.yaml
Adjusting the CRON schedule for the nightly job. There appears to be a bug when setting time zone in the downstream job, so seeing if adjusting to earlier in the evening (`23` is 7p EST) helps.
`30 23 * * SUN-THU` -> 11:30pm UTC Sunday through Thursday
> [sdp] adjust cron schedule for nightly

- pkg/defaulting/images.go
* Agent: v7.55.2
* Cluster Agent: v7.55.2
> Bump default Agent version to 7.55.2

- docs/datadog_monitor.md
- Adds additional context for use specifying the `namespaces`
- https://datadog.zendesk.com/agent/tickets/1666229
- Thought possibly a good note due to ticket
N/A
* Agent: N/A
* Cluster Agent:  >= v1.20.X
* Datadog Operator v0.6+
- Was validated in OH with TEE in `minikube` sandbox.
- `DatadogMonitor` not found when Operator was in different `namespace` or vice-a-versa.
- [X ] PR has at least one valid label: `bug`, `enhancement`, `refactoring`, `documentation`, `tooling`, and/or `dependencies`
- [ X] PR has a milestone or the `qa/skip-qa` label
> Add details regarding watched namespaces for the DatadogMonitor objects

- apis/datadoghq/v1alpha1/datadogmonitor_types.go
- apis/datadoghq/v1alpha1/zz_generated.openapi.go
- check-operator.Dockerfile
- config/crd/bases/v1/datadoghq.com_datadogmonitors.yaml
* Adds `listType=set` to 2 monitor options : 
* https://registry.terraform.io/providers/DataDog/datadog/latest/docs/resources/monitor#notify_by
* https://registry.terraform.io/providers/DataDog/datadog/latest/docs/resources/monitor#renotify_statuses
* Changes `as` to `AS` in Operator Dockerfile 
* Warnings sent when using `make generate-openapi` / `make docker-build` : 
```bash
vscode ➜ /workspaces/datadog-operator (main) $ make generate-openapi
bin/linux-aarch64/openapi-gen --logtostderr=true -o "./" -i ./apis/datadoghq/v1alpha1 -O zz_generated.openapi -p ./apis/datadoghq/v1alpha1 -h ./hack/boilerplate.go.txt -r "-"
API rule violation: list_type_missing,./apis/datadoghq/v1alpha1,DatadogMonitorOptions,NotifyBy
API rule violation: …
```
> [Tooling] Remove some OpenAPI warning and docker build warning

- apis/datadoghq/v1alpha1/datadogpodautoscaler_types.go
- config/crd/bases/v1/datadoghq.com_datadogpodautoscalers.yaml
Remove XValidation rule in DPA as requires K8S >= 1.25
Bugfix.
> Remove XValidation rule in DPA as requires K8S >= 1.25

- controllers/datadogagent/feature/enabledefault/feature.go
- controllers/datadogagent/feature/enabledefault/feature_test.go
1. Install Operator
2. Edit deployment manifest to delete `DD_TOOL_VERSION`.
3. Wait for Agents to restart.
4. Check install info config - it should have `unknown` tool version (CM is mounted as a volume with name `installinfo`).
> Use `unknown` tool version when env var is not set

- pkg/defaulting/images.go
> Bump default Agent version to 7.55.2 (#1332)

- apis/datadoghq/v1alpha1/datadogpodautoscaler_types.go
- config/crd/bases/v1/datadoghq.com_datadogpodautoscalers.yaml
> Remove XValidation rule as requires K8S >= 1.25 (#1339)

- controllers/datadogagent/feature/enabledefault/feature.go
- controllers/datadogagent/feature/enabledefault/feature_test.go
> Use `unknown` tool version when env var is not set (#1345)

- Dockerfile
- check-operator.Dockerfile
- go.mod
Trying to address a [cve-2024-24790](https://avd.aquasec.com/nvd/2024/cve-2024-24790/), VULN-5906 by bumping Go to 1.22.4.
> Bump Go version in go.mod and Dockerfiles to 1.22.4

- pkg/defaulting/images.go
Bump default agent/cluster agent version to `7.56.0`
`7.56.0` was released.
> [default/images] Bump default agent/cluster agent version to `7.56.0`

- hack/redhat-bundle.sh
`make bundle-redhat` broke after `operator-manifest-tools` upgrade from 0.2.0 to 0.6.0. Issue is new version using `crane` as a default resolver (from the error output) and our script fails with authentication error
>   -r, --resolver string                The resolver to use; valid values are [script, skopeo, crane] (default "crane")
> Update operator-manifest-tools args for 0.6.0

- Dockerfile
- check-operator.Dockerfile
Fixes [FromAsCasing](https://docs.docker.com/reference/build-checks/from-as-casing/) warnings for `operator` and `check-operator` Dockerfiles.
Before
```
docker build . -t wdhifdatadog/operator --build-arg LDFLAGS="-w -s -X github.com/DataDog/datadog-operator/pkg/version.Commit=579a07c8b61d2e00c785748c7661578f59697e07 -X github.com/DataDog/datadog-operator/pkg/version.Version=v1.8.0-rc.4_579a07c8 -X github.com/DataDog/datadog-operator/pkg/version.BuildTime=2024-08-28/08:32:38" --build-arg GOARCH=""
[...]
1 warning found (use --debug to expand):
- FromAsCasing: 'as' and 'FROM' keywords' casing do not match (line 2)
docker build . -t wdhifdatadog/check-operator -f check-operator.Dockerfile --build-arg LDFLAGS="-w -s -X github.com/DataDog/datadog-operator/pkg/version.Commit=579a07c8b61d2e00c7 …
```
> chore(lint): fix FromAsCasing warnings

- apis/datadoghq/v1alpha1/datadogagentprofile_types.go
- apis/datadoghq/v1alpha1/zz_generated.deepcopy.go
- config/crd/bases/v1/datadoghq.com_datadogagentprofiles.yaml
- pkg/agentprofile/agent_profile.go
- pkg/agentprofile/agent_profile_test.go
Adds update strategy overrides to profiles
https://datadoghq.atlassian.net/browse/CECO-1014
* Deploy operator with [profiles enabled](https://github.com/DataDog/datadog-operator/blob/main/docs/datadog_agent_profiles.md#enabling-datadogagentprofiles)
* Deploy DDA
* Create a profile with a custom update strategy that is different from what is set in the DDA
* Check the profile daemonset to see if the update strategy was overridden
> [profiles] Add update strategy overrides to profiles

- test/e2e/kind_test.go
Increase `waitFor` duration for KSM end-to-end tests. 
Fix flaky test. It sometimes takes a while for the cluster agent and/CCR pods to start running the KSM check.
> Increase waitFor duration for KSM E2E tests

- .gitlab-ci.yml
Do not rebuild the container images during merge-queue pipeline execution
The goal of this PR is not optimise the merge-queue duration by removing unnecessary job from the workload.
> Do not rebuild image during merge-queue workflow

- pkg/defaulting/images.go
Bump default agent/cluster agent version to `7.56.2`
Release of `7.56.2`
> [default/images] Bump default agent/cluster agent version to `7.56.2`

- bundle/manifests/datadog-operator.clusterserviceversion.yaml
- config/rbac/role.yaml
- controllers/datadogagent/controller_test.go
- controllers/datadogagent/feature/admissioncontroller/rbac.go
- controllers/datadogagent_controller.go
- pkg/equality/equality.go
- pkg/kubernetes/const.go
- pkg/kubernetes/objects.go
- pkg/kubernetes/objectslist.go
Adds the necessary RBACs for the Cluster Agent to modify the `ValidatingWebhookConfigurations`.
This is needed to support the new `ValidatingAdmissionWebhook` controller in the Agent's Admission Controller.
Agent: v7.58.0
Cluster Agent: v7.58.0
Build the Operator and validate that the new `ValidatingAdmissionWebhook` is created with the new Agent.
```
➜ k describe validatingwebhookconfigurations.admissionregistration.k8s.io datadog-webhook
Name:         datadog-webhook
Namespace:
Labels:       <none>
Annotations:  <none>
API Version:  admissionregistration.k8s.io/v1
Kind:         ValidatingWebhookConfiguration
Metadata:
Creation Timestamp:  2024-08-28T09:07:22Z
Generation:          1
Resource Version:    832
UID:                 efd5e35d-8257-46ba-bdc7-b35268bf7c15
Events: …
```
> feat(admission controller): add ValidatingWebhookConfigurations RBAC

- api/datadoghq/v1alpha1/datadogdashboard_types.go
- api/datadoghq/v1alpha1/zz_generated.openapi.go
- config/crd/bases/v1/datadoghq.com_datadogdashboards.yaml
* Replaces `DashboardLastForceSyncTime` with `LastForceSyncTime`
* Removes OpenAPI violation when using `make generate`
```
API rule violation: names_match,./api/datadoghq/v1alpha1,DatadogDashboardStatus,LastForceSyncTime
```
* Will be cherry-picked to `v1.9`
* No Q/A needed, no functional change
> [Dashboard] Replace DashboardLastForceSyncTime with LastForceSyncTime

- api/utils/utils.go
- api/utils/utils_test.go
- internal/controller/datadogagent/component/agent/new.go
- internal/controller/datadogagent/controller_reconcile_v2.go
- pkg/agentprofile/agent_profile.go
- pkg/agentprofile/agent_profile_test.go
If we don't set a max unavailable in the DAP or the DDA, try to use the [edsMaxPodUnavailable](https://github.com/DataDog/datadog-operator/blob/2a7b83cae17fb1cb6304832f9dde548c9e4fd75e/cmd/main.go#L166) value before falling back to the kubernetes default.
* Spin up an operator pod with [DAP enabled](https://github.com/DataDog/datadog-operator/blob/main/docs/datadog_agent_profiles.md#enabling-datadogagentprofiles) and [edsMaxPodUnavailable](https://github.com/DataDog/datadog-operator/blob/2a7b83cae17fb1cb6304832f9dde548c9e4fd75e/cmd/main.go#L166) set to different values
* Create a …
> [profiles] Fall back to EDS options if needed

- api/utils/utils.go
- api/utils/utils_test.go
- internal/controller/datadogagent/component/agent/new.go
- internal/controller/datadogagent/controller_reconcile_v2.go
- pkg/agentprofile/agent_profile.go
- pkg/agentprofile/agent_profile_test.go
> Fall back to eds options if needed (#1414)

- api/datadoghq/v1alpha1/datadogagentprofile_types.go
- api/datadoghq/v1alpha1/zz_generated.openapi.go
- config/crd/bases/v1/datadoghq.com_datadogagentprofiles.yaml
Remove capitalization for `createStrategy`
Check the crd for `createStrategy` and not `CreateStrategy`
> Remove capitalization for profile field

- api/datadoghq/common/envvar.go
- pkg/config/config.go
- pkg/config/creds.go
- pkg/datadogclient/client.go
A small cleanup-related change for constants defined in pkg/config . Remove duplicate envvars and move one envvar to apicommon
Also, incorporate DD_DD_URL envvar option into datadog client setup
Make sure operator builds and runs as expected
> [cleanup] shuffle constants in pkg/config

- pkg/defaulting/images.go
* Updates the default image to `7.57.2` for Agent/cluster Agent
* incident-30436
* This will be backported to release `1.9.0`
Generic QA instructions when we update to new Agent version
> Update Agent/cluster Agent to 7.57.2

- internal/controller/datadogagent/controller_reconcile_v2.go
Fix error:
```
{"level":"ERROR","ts":"2024-09-20T17:30:02.617Z","logger":"controllers.DatadogAgent","msg":"unable to update DatadogAgentProfile status","datadogagent":{"name":"datadog","namespace":"system"},"component":"nodeAgent","daemonset.Namespace":"system","daemonset.Name":"datadog-agent","error":"an empty namespace may not be set when a resource name is provided"}
```
* Deploy the operator with [profiles enabled](https://github.com/DataDog/datadog-operator/blob/main/docs/datadog_agent_profiles.md) and [create strategy …
> [profiles] Don't update status for default profile

- pkg/defaulting/images.go
* Cherry-pick of https://github.com/DataDog/datadog-operator/pull/1430
* Update Agent/Cluster Agent to `7.57.2`
* incident-30436
Generic QA instructions when we update to new Agent version + ensure the init containers limit are set to `100Mi` when using APM SSI
> Update Agent/cluster Agent to `7.57.2`

- internal/controller/datadogslo/controller.go
* No-op change
* Running `make build` on `main` currently produces a diff for this file while it should not. This is linked to https://github.com/DataDog/datadog-operator/pull/1436/files#diff-c70a44743985a8fd8164e0cd7af09a1d2a0479201796e987f4d4bdc08150987dL61-L63 that changed the alignment for parameters that remained
> [chore] Fix alignment of Reconciler struct init in SLO controller

- .gitlab-ci.yml
This PR adds a gitlab job to trigger deployments of release candidates and final release images. Currently the workflow is configured for experimental env clusters only.
The job requires manual intervention to start; eventually the plan is to change it to be automatic at the end of the tag pipeline.
> [gitlab] trigger operator release candidate workflow

- internal/controller/datadogagent/store/store.go
Fixes a bug in the operator where when updating the DatadogAgent with an pre-existing CiliumNetworkPolicy created by the operator does not update the CiliumNetworkPolicy. The following errors are returned repeatedly:
```
{"level":"ERROR","ts":"2024-10-08T17:11:28.580Z","msg":"Reconciler error","controller":"datadogagent","controllerGroup":"datadoghq.com","controllerKind":"DatadogAgent","DatadogAgent":{"name":"datadog","namespace":"default"},"namespace":"default","name":"datadog","reconcileID":"8acb4181-dd52-433d-a67f-ca7cc7e0c7b1","error":"ciliumnetworkpolicies.cilium.io \"datadog-agent\" is invalid: metadata.resourceVersion: Invalid value: 0x0: must be specified for an update","errorCauses":[{"error":"ciliumnetworkpolicies.cilium.io \"datadog-agent\" is invalid: metadata.resourceVersion: …
```
> Fix CiliumNetworkPolicy not updating properly

- pkg/kubernetes/platforminfo_test.go
I was removing PSP #1459 and forgot this file :') 
> [cleanup] remove Pod Security Policy from `platforminfo_test`

- internal/controller/datadogagent/override/dependencies.go
- internal/controller/datadogagent/override/podtemplatespec.go
- internal/controller/datadogagent/override/podtemplatespec_test.go
This change will deploy different configmap names relative to the `customConfigurations` set for each override component (Agent/Cluster Agent/CCR). That way, it fixes an issue where the Operator `customConfigurations` option creates a single ConfigMap for all 3 Agent/Cluster Agent/CCR pods as it was using the same configmap name for all three.
CECO-1460
Fix an issue where the Operator customConfigurations option creates a single ConfigMap for all 3 Agent/Cluster Agent/CCR pods.
N/A
N/A
Apply the following `DatadogAgent` override settings:
```
spec:
override:
nodeAgent:
customConfigurations:
datadog.yaml: 
configData: |
tags: ["config:agent"]
clusterAgent:
customConfigurations:
datadog-cluster.yaml:
configData: |
tags: ["config:cluster-agent"]
clusterChecksRunner:
customConfigurations: …
```
> Create different configmap names for Agent/Cluster Agent/CCR when using customConfigurations

- internal/controller/datadogagent/feature/otlp/feature.go
When `global.networkPolicy.create` and OTLP is enabled, enables the necessary ingress ports in the NetworkPolicy or CiliumNetworkPolicy for OTLP ingest depending on the flavor that is configured in `global.networkPolicy.flavor`. Currently this is only supported for APM features.
Also refined the logic on the OTLP ports for the local service depending if the user has configured `features.otlp.receiver.protocols.grpc/http.hostPortConfig.enabled` and/or `features.otlp.receiver.protocols.grpc/http.hostPortConfig.hostPort`. This is in an effort to make it so that NetworkPolicy's ingress ports correspond with the local service (vice-versa) whenever the above `hostPortConfig`'s are configured, a follow-up to this PR: https://github.com/DataDog/datadog-operator/pull/1440
CECO-1468
Generally to …
> Include ports for networkpolicy or ciliumnetworkpolicy for OTLP ingest

- internal/controller/datadogmonitor/controller.go
Cherry-pick 427385c0c2fe9eb4e52be013339ba1cd2847fe70 from https://github.com/DataDog/datadog-operator/pull/1466
Refer to original PR, uncovered during QA
* Refer to https://github.com/DataDog/datadog-operator/pull/1466
> Do not log error if sync variable is not set (#1466)

- pkg/equality/equality.go
- pkg/equality/equality_test.go
Implements checking for differences in annotations and labels for objects.
Unable to update service account annotations when qa'ing https://github.com/DataDog/datadog-operator/pull/1425 
> Implement label and annotation equality checking

- pkg/equality/equality.go
- pkg/equality/equality_test.go
* Implement label and annotation equality checking
* Update pkg/equality/equality_test.go
---------
Cherry pick #1467 
> Implement label and annotation equality checking (#1467)

- pkg/remoteconfig/orchestrator_k8s_crd.go
> Overwrite custom resources by new data instead of appending to old data

- Makefile
- pkg/equality/equality.go
- pkg/equality/equality_test.go
When checking if secrets were the same to determine whether we needed to send an update request to k8s, the operator was checking that it was a configmap by mistake.
https://datadoghq.atlassian.net/browse/CECO-1697
Once a new rc is deployed on staging, check the operator rollout dashboard in staging and confirm that the number of update requests for secrets is reduced in the `k8s requests by target object` widget
> Fix secret equality checking

- internal/controller/datadogagent_controller.go
Add GenerationChanged predicate to DatadogAgent controller to prevent Status updates from triggering reconciles on the resource.
Before change (two reconcilers per period):
```
{"level":"INFO","ts":"2024-10-25T11:41:39.377Z","logger":"controllers.DatadogAgent","msg":"Reconciling DatadogAgent","datadogagent":{"name":"datadog","namespace":"system"}}
{"level":"INFO","ts":"2024-10-25T11:41:39.743Z","logger":"controllers.DatadogAgent","msg":"Reconciling DatadogAgent","datadogagent":{"name":"datadog","namespace":"system"}}
{"level":"INFO","ts":"2024-10-25T11:41:54.377Z","logger":"controllers.DatadogAgent","msg":"Reconciling DatadogAgent","datadogagent":{"name":"datadog","namespace":"system"}}
{"level":"INFO","ts":"2024-10-25T11:41:54.743Z","logger":"controllers.DatadogAgent","msg":"Reconciling …
```
> add generation changed predicate to dda controller

- pkg/defaulting/images.go
Bump default agent/DCA image version to 7.58.1
> Bump default agent/DCA image version to 7.58.1

- .golangci.toml
> bump golangci-lint timeout to 10m (#1494)

- pkg/defaulting/images.go
> Bump agent and cluster-agent image version to 7.58.2 (#1499)

- pkg/defaulting/images.go
Update the default `agent` and `cluster-agent` version to `7.59.0`.
`7.59.0` is out!
> Update the default `(cluster-)agent` version to `7.59.0`

- .gitlab-ci.yml
Automatically trigger release candidate workflow for tag pipelines
It was initially set to require a manual trigger so it could be tested
> [tooling][gitlab] automatically trigger release candidate workflow

- internal/controller/datadogagent/override/global.go
This PR adds the Agent Data Plane container to the list of containers which receive an overridden `runtimesocketdir` and `kubelet-ca` volume mount.
This is needed to ensure ADP can access the proper socket paths on the host.
N/A
* Agent: N/A
Ran Operator locally in Kind cluster and observed the ADP container got the same `runtimesocketdir` and `kubelet-ca` volume mounts as other containers in Agent pod.
> fix: include ADP container in certain pod-wide volume mount overrides

- internal/controller/datadogagent/component/agent/default.go
Updates the ADP container command to specify a `run` subcommand to the `agent-data-plane` instead of relying on it being a default.
We're making changes to ADP's CLI argument handling and need to specify the specific subcommand to use to run ADP.
N/A
* Agent: N/A
Ran Operator locally in a Kind cluster and observed that it used the updated command arguments when creating the ADP container.
> fix: specify 'run' subcommand to ADP binary

- internal/controller/datadogagent/feature/admissioncontroller/feature.go
Add network policies for the admission controller feature
https://github.com/DataDog/datadog-operator/issues/1490
https://datadoghq.atlassian.net/browse/CECO-1741
1. Create a cluster with a network plugin enabled
2. Deploy the operator
3. Deploy a DDA with network policies and the admission controller feature enabled
```yaml
networkPolicy:
create: true
flavor: <kubernetes or cilium>
```
4. Deploy an app that the admission controller should mutate. Example label and annotation below adds an init container that installs the python tracer to the app pod
```yaml
apiVersion: apps/v1
kind: Deployment
metadata:
name: redis
labels: …
```
> Add network policies for admission controller feature

- pkg/defaulting/images.go
Update latest default fips proxy container
In the DatadogAgent, set global.fips.enabled to `true` and check default image of the container
> update default fips-proxy image version to 1.1.6

- .github/workflows/release.yaml
Attempts to use [the automatic generated token](https://docs.github.com/en/actions/security-for-github-actions/security-guides/automatic-token-authentication#example-2-calling-the-rest-api) for authentication
sporadic rate limits https://datadoghq.atlassian.net/browse/CECO-628
> [tooling] use generated GITHUB_TOKEN for authentication

- .github/workflows/release.yaml
> (backport) [tooling] use generated GITHUB_TOKEN for authentication (#1541)

- pkg/defaulting/images.go
FIPS image update (cherry-pick from #1540 )
> (backport) update default fips-proxy image version to 1.1.6

- api/datadoghq/v1alpha1/datadogpodautoscaler_types.go
Add `Local` as valid type for autoscaler source.
Implementing local fallback
* Cluster Agent: v7.56.0
Will be tested as part of changes made to autoscaling controller for local fallback.
> Add `Local` as valid type for autoscaler source

- pkg/defaulting/images.go
* Update default Agent and cluster Agent to `7.60.0`
https://github.com/DataDog/datadog-agent/releases/tag/7.60.0 was released
> Update the default (cluster-)Agent version to 7.60.0

- pkg/defaulting/images.go
> [backport] Update Agent and cluster Agent to `7.60.0`

- internal/controller/datadogagent/component/clusteragent/default_test.go
- internal/controller/datadogagent/component/clusteragent/utils.go
- internal/controller/datadogagent/component/clusterchecksrunner/default.go
- internal/controller/datadogagent/component/clusterchecksrunner/default_test.go
- internal/controller/datadogagent/override/dependencies.go
- internal/controller/datadogagent/testutils/client_utils.go
- internal/controller/datadogagent_controller.go
- pkg/equality/equality.go
- pkg/kubernetes/objects.go
- pkg/kubernetes/objectslist.go
- pkg/kubernetes/platforminfo.go
- pkg/kubernetes/platforminfo_test.go
Cherry-picks https://github.com/DataDog/datadog-operator/pull/1580
> [backport] PDB v1beta1 support fix

- config/crd/bases/v1/datadoghq.com_datadogpodautoscalers_v1alpha1.json
Fix stale CRD manifest from #1519 
> Regenerate stale datadogpodautoscalers CRD

- internal/controller/datadogagent/feature/admissioncontroller/rbac.go
Adds the necessary RBACs for the Cluster Agent to `delete` the `datadog-webhook` Validating and Mutating webhook configurations.
This is needed to allow the Cluster Agent to delete its own Admission Webhooks.
Agent: v7.63.0
Cluster Agent: v7.63.0
Build the Operator and validate that the new `datadog-cluster-agent` `clusterroles.rbac.authorization.k8s.io` has the following permissions:
```
➜ kubectl describe clusterroles.rbac.authorization.k8s.io datadog-cluster-agent
Name:         datadog-cluster-agent
[...]
mutatingwebhookconfigurations.admissionregistration.k8s.io    []                 [datadog-webhook]                     [get list watch update delete]
validatingwebhookconfigurations.admissionregistration.k8s.io  []                 [datadog-webhook]                     [get list watch …
```
> feat(admission): add delete RBAC for datadog-webhook

- api/datadoghq/v2alpha1/datadogagent_types.go
- api/datadoghq/v2alpha1/zz_generated.openapi.go
- config/crd/bases/v1/datadoghq.com_datadogagents.yaml
- config/crd/bases/v1/datadoghq.com_datadogagents_v2alpha1.json
- docs/configuration.v2alpha1.md
Fixes API violation from https://github.com/DataDog/datadog-operator/pull/1559 
https://github.com/DataDog/datadog-operator/actions/runs/12434980195/job/34719814433#step:6:43 API rule violations occur when running `make generate`
Verify that error has been resolved in CI: https://github.com/DataDog/datadog-operator/actions/runs/12659013902/job/35277172303?pr=1607 looks good
> Fix API violation from OTel Agent

- internal/controller/datadogagent/feature/servicediscovery/feature.go
- internal/controller/datadogagent/feature/servicediscovery/feature_test.go
Add a missing cgroup mount to system-probe which is required to get container information for service discovery. 
This was not required for earlier agent releases but will be from version 7.61 of the agent.
Bug found during manual testing of latest agent release.
The same mount is already added for other features like USM/NPM.
Follow the instructions on https://github.com/datadog/datadog-operator/pull/1449 except use at least version `7.61.0-rc.10` of the agent. 
Run the following command in the system-probe container to check that the `container_id` is filled:
```
$ kubectl exec -it -n system datadog-agent-wh7nn -c system-probe -- /bin/bash
.... ,"container_id":"2405b0f93c5ed4039223c7b5ac098f32b3e6ae7671a743bca4023e5ac2e75c59"}] ...
```
> service discovery: Add missing cgroup mount

- internal/controller/datadogagent/feature/servicediscovery/feature.go
- internal/controller/datadogagent/feature/servicediscovery/feature_test.go
> service discovery: Add missing cgroup mount (#1610)

- service.datadog.yaml
Disable build impact analysis for Operator workflows.
> If your service uses artifacts from several repos (e.g chart in k8s-resources, app code in dd-go), you probably want to set this to true.
> [conductor] disable build impact analysis

- pkg/defaulting/images.go
Update latest agent/cluster agent version to `7.61.0`
`7.61.0` has been released.
* Agent: v7.61.0
* Cluster Agent: v7.61.0
> [default/images] Bump default agent/cluster agent version to 7.61.0

- internal/controller/datadogagent/feature/otelcollector/configmap_test.go
- internal/controller/datadogagent/feature/otelcollector/feature.go
- internal/controller/datadogagent/feature/otelcollector/feature_test.go
* Add annotations for otel configdata
* Use pointer receivers to match other features
When changing configdata, the pod was not restarting to use the updated configmap data
* Create a DDA with otel enabled and configdata set. Example: https://github.com/DataDog/datadog-operator/blob/1a69194e7c958641288a3f0489372acb2cecfa34/examples/datadogagent/datadog-agent-with-otel-agent.yaml#L17-L48
* Ensure the node agent pod and otel configmap (`<dda-name>-otel-agent-config`) have the same annotation `checksum/otel_agent-custom-config: <md5-hash>` 
* Change the DDA otel configdata section and apply the changes. For example, change …
> Add otel collector configdata annotations

- internal/controller/datadogagent/controller_reconcile_agent.go
- internal/controller/datadogagent/controller_reconcile_v2_common.go
- pkg/condition/condition.go
- pkg/condition/condition_test.go
Fixes https://github.com/DataDog/datadog-operator/issues/1561
1. Install older version of Operator
2. Edit operator clusterrole and to restrict operator on Daemonsets - delete `daemonsets` in this definition:
```yaml
...
- apiGroups:
- apps
resources:
- daemonsets
- deployments
verbs:
- create
- delete
- get
- list
- patch
- update
- watch
...
```
3. Apply minimal DDA and monitor status - observe DDA status with duplicates.
```yaml
agentList:
- available: 0
current: 0
desired: 0
ready: 0
state: Failed
status: Failed
upToDate: 0
- available: 0
current: 0
desired: 0
ready: 0
state: …
```
> Fix daemonset status duplication in DDA when DS can't be created

- api/datadoghq/v2alpha1/condition.go
- api/datadoghq/v2alpha1/condition_test.go
- internal/controller/datadogagent/controller_reconcile_agent.go
- internal/controller/datadogagent/controller_reconcile_v2_common.go
cherry-pick #1629 and apply changes to correct files which were moved in `main`.
> Fix daemonset status duplication in DDA when DS can't be created (#1629)

- bundle-community-operators/manifests/datadog-operator.clusterserviceversion.yaml
- bundle/manifests/datadog-operator.clusterserviceversion.yaml
- config/manager/kustomization.yaml
> release v1.12.0-rc.2

- pkg/defaulting/images.go
Updates the latest Agent and Cluster Agent version to 7.62.0
Agent 7.62.0 has been released
> Update latest Agent and Cluster Agent version to 7.62.0

- internal/controller/datadogagent/feature/gpu/feature.go
- internal/controller/datadogagent/feature/gpu/feature_test.go
add a missing cgroup mount to gpu monitoring feature of system-probe
gpu-probe is using cgroups mount to adjust device cgroups
[Jira ticket](https://datadoghq.atlassian.net/browse/EBPF-646)
similar to this [PR](https://github.com/DataDog/datadog-operator/pull/1617) that adds the mount for the service-discovery feature and same mount already added for NPM/USM
Agent: v7.64.x for the GPU monitoring feature.
Cluster Agent: N/A
1. Deploy the operator in a cluster
2. Deploy the agent resource with feature.gpu.enabled: yes and service_discovery, usm and npm are disabled.
3. Check that deployed agent has a cgroup mount in the system-probe container
> gpu: added cgroup mount to gpu feature

- api/datadoghq/v2alpha1/const.go
- api/datadoghq/v2alpha1/datadogagent_types.go
- api/datadoghq/v2alpha1/envvar.go
- config/crd/bases/v1/datadoghq.com_datadogagents.yaml
- config/crd/bases/v1/datadoghq.com_datadogagents_v2alpha1.json
- docs/configuration.v2alpha1.md
- internal/controller/datadogagent/defaults/datadogagent_default.go
- internal/controller/datadogagent/override/global.go
- internal/controller/datadogagent/override/global_test.go
- pkg/testutils/builder.go
This PR adds the mount for the PodResources socket.
The pod resources API is necessary for correctly assigning pods to GPU devices in GPU monitoring.
* Agent: v7.62
Tested locally by deploying the operator in a cluster, deploying an agent with default settings and ensuring that:
- The agent container has a mount for `/var/lib/kubelet/pod-resources/kubelet.sock` 
- The environment variable `DD_KUBERNETES_KUBELET_POD_RESOURCES_SOCKET` is correctly set to `/var/lib/kubelet/pod-resources/kubelet.sock`.
> Add PodResources mount to agent

- Makefile
Updated the `make generate-openapi` command in Makefile to result in an error when API rule violations are detected. 
Previously if we make a change to the CRDs that didn't follow the correct formatting to be populated correctly, no error would result when running commands locally (ex: `make generate`) and warnings wouldn't show up in CI. 
tested here: https://github.com/DataDog/datadog-operator/pull/1626 validation checks [failed](https://github.com/DataDog/datadog-operator/actions/runs/12797192223/job/35678544709)
> Update `make generate-openapi` to error when API violations occur

- Dockerfile
- Makefile
- Update openshift preflight version to v1.11.1
- Update docker `maintainer` label to `Datadog Inc.` due to redhat trademark error in preflight checks
`time="2025-02-04T22:11:54Z" level=error msg=release-url error="invalid preflight version, please download the latest version and re-submit"
Error: could not submit to pyxis: could not create test results: status code: 400: body: {"type": "about:blank", "title": "Bad Request", "detail": "Validation error: 'github.com/redhat-openshift-ecosystem/openshift-preflight' version '1.10.1' is not supported. Supported versions are: ['1.11.0', '1.11.1']", "status": 400, "trace_id": "0xe42cec93d3e34e6fbb91c99e80009941"}`
`time="2025-02-05T16:15:52Z" level=debug msg="running check" check=HasRequiredLabel
time="2025-02-05T16:15:52Z" level=debug …
> Fixes for operator release (openshift preflight version, docker maintainer label)

- internal/controller/datadogagent/feature/enabledefault/rbac.go
- pkg/kubernetes/rbac/const.go
This PR is the same as #1651 but all commits are signed.
This PR adds a clusterrole rule necessary to allow the agent to query the EKS metrics API as described in the official [AWS blog post](https://aws.amazon.com/blogs/containers/amazon-eks-enhances-kubernetes-control-plane-observability/).
Functional control plane metric reporting.
The testing documentation is found in the description of https://github.com/DataDog/helm-charts/pull/1687.
I deployed the operator
I used the operator to deploy the agent
I validated that the appropriate rules were granted to both the datadog-agent and datadog-cluster-checks-runner clusterroles.
> [CONTINT-4500] Add EKS Clusterrole Rule for EKS control plane metrics 

- config/rbac/role.yaml
- internal/controller/datadogagent_controller.go
* Adds EKS controlplane RBAC generation
https://github.com/DataDog/datadog-operator/pull/1666: following this merge, components cannot be reconciled since the operator itself does not have the RBAC to grant this rule
```json
{"level":"ERROR","ts":"2025-02-07T09:59:07.699Z","logger":"controllers.DatadogAgent","msg":"store.store Create","datadogagent":{"name":"datadog","namespace":"system"},"obj.namespace":"","obj.name":"datadog-agent","error":"clusterroles.rbac.authorization.k8s.io \"datadog-agent\" is forbidden: user \"system:serviceaccount:system:datadog-operator-controller-manager\" (groups=[\"system:serviceaccounts\" \"system:serviceaccounts:system\" \"system:authenticated\"]) is attempting to grant RBAC permissions not currently held:\n{APIGroups:[\"metrics.eks.amazonaws.com\"], …
```
> Generate EKS controlplane RBAC

- pkg/defaulting/images.go
Update latest Agent and Cluster Agent version to 7.62.2
Agent 7.62.2 has been [released](https://github.com/DataDog/datadog-agent/releases/tag/7.62.2)
> Update latest Agent and Cluster Agent version to 7.62.2

- .gitlab-ci.yml
Update the Gitlab CI internal image release to use GBI template and add one for GBI-fips.
Testing for custom image build jobs done [here](https://ddstaging.datadoghq.com/notebook/11205373/gbi?notebookType=legacy&range=724303&start=1739291907697&live=false). 
> Levan m/gitlab gbi image jobs

- .devcontainer/devcontainer.json
* Adds `make install-tools` as post start + defaults linter to the one used in CI
https://github.com/DataDog/datadog-operator/pull/1671 enforces GCI, so let's ensure we use the right linter
> (tooling) [devcontainer] Use gci lint + install tools

- internal/controller/datadogagent/feature/enabledefault/rbac.go
- internal/controller/datadogagent/feature/enabledefault/rbac_test.go
Fixes bug in parsing group resource parsing that prevented parsing groups containing periods correctly.
Fix the issue.
Same testing plan as [this](https://github.com/DataDog/datadog-operator/pull/1379)
But, here we should test with a resource of which the api group contains periods.
You should add the labels/annotations as tags configuration for ingresses. For example:
```
metadata:
name: datadog
namespace: system
spec:
global:
credentials:
apiSecret:
kubelet:
kubernetesResourcesLabelsAsTags:
ingresses.networking.k8s.io:
foo: foo
bar: bar
kubernetesResourcesAnnotationsAsTags:
daemonsets.apps:
agent.datadoghq.com/agentspechash: hash …
```
> Fix parsing group resource to allow groups with periods

- internal/controller/datadogagent/override/global.go
- internal/controller/datadogagent/override/global_test.go
Update new podresources mount to be isolated to agent container
Similar to https://github.com/DataDog/datadog-operator/pull/1650 , and also verify that the envvar (`DD_KUBERNETES_KUBELET_POD_RESOURCES_SOCKET `) and volumemount (`kubelet-pod-resources`) are only present in the Agent container.
> update podresources mount to only be in agent container

- internal/controller/datadogagent/override/global.go
- internal/controller/datadogagent/override/global_test.go
> [v1.13][cherry-pick] update podresources mount to only be in agent container (#1716)

- pkg/defaulting/images.go
> bump default agent images to 7.63.0 (#1722)

- internal/controller/datadogagent/component/agent/default.go
- pkg/defaulting/images.go
Use `7.63.0-ot-beta-jmx` instead of nightly image. This will need to be updated once OTel agent is GA (7.64.0), as the ot-beta image will be discontinued.
Run the OTel Collector feature, and ensure the otel agent starts/ works as expected. Confirm that the otel container image is `7.63.0-ot-beta-jmx`.
> Update OTel agent image

- .gitlab-ci.yml
- Dockerfile
- Makefile
- internal/controller/fipsonly.go
This change adds `FIPS_ENABLED` parameter to the Operator Dockerfile which is then used to build the image with `CGO_ENABLED=1 GOEXPERIMENT=boringcrypto`.
Removes `-w -s` ldflags to include debug symbols so image can be verified. Once testing using main tag, they'll be put back.
In Gitlab:
* We pass `FIPS_ENABLED` parameter in image building jobs (`build_operator_image_fips_amd64`, `build_operator_image_fips_arm64`). This is set to false by default.
* We extend these jobs and pass `FIPS_ENABLED=true`, and creating image with the new tag.
* We extend `publish_public_tag` job to reference fips image tags and generate main-fips tag.
Are there minimum versions of the Datadog Agent and/or Cluster Agent …
> Generate fips image compiled with Go boringcrypto

- .gitlab-ci.yml
- Makefile
Adds jobs to publish version tag and latest fips images to docker and RH.
Jobs are similar to the one added for `main` tag in https://github.com/DataDog/datadog-operator/pull/1731 and verified as follows:
```sh
$ docker pull datadog/operator:main-fips
main-fips: Pulling from datadog/operator
....
Digest: sha256:90d7e8df5126470fcabc7ecb5bb953eace778c31a0cfc3fb7a1f306f71023e39
Status: Downloaded newer image for datadog/operator:main-fips
docker.io/datadog/operator:main-fips
$ docker create --name operator-main-fips datadog/operator:main-fips
54df7908953a958acaeb5e99b6ce9b6eafa039aaf82371945540304fee6380c7
$ docker cp operator-main-fips:/manager ./manager-main-fips
Successfully copied 91.8MB to /workspaces/operator-2/manager-main-fips
$ go tool nm manager-main-fips | grep -i …
```
> Add gitlab workflows to publish fips images

- Makefile
Bump kustomize version to 5.6.0 following go version bump
> bump kustomize to 5.6.0

- .gitlab-ci.yml
- Makefile
* Add gitlab workflows to publish fips images
* Add back -w -s ldflags
> Add gitlab workflows to publish fips images (#1732)

- .gitlab-ci.yml
Update check_preflight_redhat_image image tag to remove the `v` (ex: `v1.13.0-rc.2` should be `1.13.0-rc.2`) 
Running this test on v1.13.0-rc.2 pipeline [failed](https://gitlab.ddbuild.io/DataDog/datadog-operator/-/jobs/824637698) because the check was trying to find an image with a tag that didn't exist
> Update check_preflight_redhat_image image tag

- internal/controller/datadogdashboard/dashboard.go
- internal/controller/datadogdashboard/dashboard_test.go
Remove `IsReadOnly` from dashboards since it is deprecated and being removed from the backend, which causes API calls to error
* Check that whichever org you're testing in prevents `is_read_only` API calls
* Deploy operator with [dashboards enabled](https://github.com/DataDog/helm-charts/blob/643aedf8cd8b400cf8f15da9cf698873e92e9064/charts/datadog-operator/values.yaml#L87-L89)
* Create a `DatadogDashboard` and check that it is created and doesn't cause any error logs in the operator. [Example dashboard](https://github.com/DataDog/datadog-operator/blob/main/examples/datadogdashboard/ …
> Remove IsReadOnly from dashboard

- pkg/defaulting/images.go
Bump default Agent/DCA to 7.63.2
https://github.com/DataDog/datadog-agent/releases/tag/7.63.2: 
> Disable the X25519Kyber768Draft00 key exchange mechanism to avoid issues with firewalls not supporting it, in particular AWS Network Firewall.
> bump default agent images to 7.63.2

- internal/controller/datadogagent/controller_reconcile_v2.go
- internal/controller/datadogagent/controller_reconcile_v2_helpers.go
- internal/controller/datadogagent/controller_reconcile_v2_helpers_test.go
* Moves some logic blocks from `controller_reconcile_v2.go` to helpers function to make it more readable and testable
* Some unit tests are added:
* `reconcileAgentProfiles` is not unit tested due to all its dependencies
* cleanup helper functions are not unit tested since they only aggregate errors from functions that are themselves unit tested
> [CECO-2016] Small controller reconcile v2 refactor

- pkg/defaulting/images.go
Update latest default fips proxy container
> update default fips-proxy image version to 1.1.8

- .gitlab-ci.yml
Configure the CI to always run E2E tests on release branches, i.e. if: $CI_COMMIT_TAG, without any manual clicks
* initially tested by setting both jobs to run automatically on this branch, confirmed that the e2e tests ran correctly in the [pipeline](https://gitlab.ddbuild.io/DataDog/datadog-operator/-/pipelines/58000006)
```
rules: 
- if: '$CI_COMMIT_BRANCH == "swang392/enable-e2e-ci"' # will be removed after testing
when: always 
- if: $CI_COMMIT_TAG
when: always
```
* next step: test on v1.13.0-rc.3, rules will be changed to run always on `$CI_COMMIT_TAG` …
> [CECO-2004] Always run e2e tests on release branches

- .gitlab-ci.yml
> [CECO-2004] Always run e2e tests on release branches (#1764)

- internal/controller/datadogagent/controller_reconcile_v2_common.go
- internal/controller/datadogagent/controller_reconcile_v2_common_test.go
Put https://github.com/DataDog/datadog-operator/pull/1667 behind an annotation for more testing and rollout control
Not all profile tasks are synced. Only DS changes are made with #1667, no node label or agent deletion changes. This means we should not change the profile affinity for a profile with this annotation set to true
* Follow the setup steps from https://github.com/DataDog/datadog-operator/pull/1667 to enable EDS and profiles in the operator
* Without the annotation, make a change to a DDA and ensure that profile agent pods are updated immediately while the EDS agent pods wait for the canary to finish before updating
* …
> Gate profile canary waits behind annotation

- internal/controller/datadogagent/controller_reconcile_agent.go
- internal/controller/datadogagent/controller_reconcile_agent_test.go
- internal/controller/datadogagent/controller_reconcile_ccr.go
- internal/controller/datadogagent/controller_reconcile_ccr_test.go
- internal/controller/datadogagent/controller_reconcile_dca.go
- internal/controller/datadogagent/controller_reconcile_dca_test.go
In cleanup functions, we filter ds/deploy with label `app.kubernetes.io/part-of` to only clean up resources associated to the DDA/DDAI owner. This label is based on namespace + DDA name with `-` replaced by `--` and is injected by `GetDefaultLabels`: https://github.com/DataDog/datadog-operator/blob/54ed5494f98ca4ea2cdcf1536597396812abcc22/internal/controller/datadogagent/object/labels.go#L25
Multiple DDA/DDAI can be reconciled without cleanup interferences
Covered by unit tests and tested on `kind`: same QA steps as https://github.com/DataDog/datadog-operator/pull/1448. Additional QA step: create 2 DDA (with different names) …
> Use `app.kubernetes.io/part-of` label to cleanup only owned ds/deployments

- internal/controller/datadogagent/controller_reconcile_agent.go
- internal/controller/datadogagent/controller_reconcile_agent_test.go
- internal/controller/datadogagent/controller_reconcile_ccr.go
- internal/controller/datadogagent/controller_reconcile_ccr_test.go
- internal/controller/datadogagent/controller_reconcile_dca.go
- internal/controller/datadogagent/controller_reconcile_dca_test.go
In cleanup functions, we filter ds/deploy with label `app.kubernetes.io/part-of` to only clean up resources associated to the DDA/DDAI owner. This label is based on namespace + DDA name with `-` replaced by `--` and is injected by `GetDefaultLabels`: https://github.com/DataDog/datadog-operator/blob/54ed5494f98ca4ea2cdcf1536597396812abcc22/internal/controller/datadogagent/object/labels.go#L25
Multiple DDA/DDAI can be reconciled without cleanup interferences
Covered by unit tests and tested on `kind`: same QA steps as https://github.com/DataDog/datadog-operator/pull/1448. Additional step: create 2 DDA (with different names) and …
> [CECO-2013] Use `app.kubernetes.io/part-of` label to cleanup only owned ds/deployments

- api/datadoghq/v2alpha1/datadogagent_validation.go
- internal/controller/datadogagent/controller.go
- internal/controller/datadogagent/controller_reconcile_v2.go
- internal/controller/datadogagent/controller_reconcile_v2_helpers.go
- internal/controller/datadogagent/controller_reconcile_v2_helpers_test.go
- internal/controller/datadogagent/controller_test.go
- internal/controller/datadogagent/controller_v2_test.go
- internal/controller/datadogagent/utils.go
- internal/controller/datadogagent_controller.go
- pkg/controller/utils/datadog/common.go
- pkg/controller/utils/datadog/metrics_forwarder.go
Use the object reconciler interface and separate out DDA validation
Newer and shinier way to do the same thing. Saves a few lines of code in the reconciler
[CECO-2101](https://datadoghq.atlassian.net/browse/CECO-2101)
* Should be no-op. Apply a DDA manifest. All components should spin up as normal
[CECO-2101]: https://datadoghq.atlassian.net/browse/CECO-2101?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> Use object reconciler

- internal/controller/datadogagent/feature/eventcollection/feature.go
This PR fixes an issue in the event collection feature by removing unnecessary environment variables set in the node-agent.
The recommended approach is to run the kubernetes_apiserver check in the cluster-agent instead of the node-agent, which is already how the operator is configured. The operator marks the cluster-agent as a required component in the feature code.
Currently, the kubernetes_apiserver check is configured in the node-agent, but it never actually runs. This is because the agent code includes a condition that prevents it from running unless DD_CLUSTER_AGENT_ENABLED is set to false. However, in the operator, this variable is set to true (as expected, since the cluster-agent is required).
In summary, there’s no need to set anything for the node-agent because the check won’t …
> [feature/eventcollection] Don't set anything for the node agent

- Dockerfile
Puts licenses in the proper directory, right now we have licences (with them) and empty licenses
> fix typo in license dir on operator image

- Makefile
- hack/install-openshift-preflight.sh
Update script to accept "latest" as the version to use
Update Makefile to set parameter "latest"
This can be tested in a linux environment by running the script: `hack/install-openshift-preflight.sh latest`
It can also be tested on a release pipeline, confirming that the latest version is being downloaded in the preflight jobs
> [tooling] use latest preflight version

- internal/controller/datadogagent/controller.go
- internal/controller/datadogagent/controller_reconcile_v2.go
- internal/controller/datadogagent/controller_reconcile_v2_helpers.go
- internal/controller/datadogagent/feature/admissioncontroller/feature.go
- internal/controller/datadogagent/feature/autoscaling/feature.go
- internal/controller/datadogagent/feature/clusterchecks/feature.go
- internal/controller/datadogagent/feature/cspm/feature.go
- internal/controller/datadogagent/feature/enabledefault/feature.go
- internal/controller/datadogagent/feature/eventcollection/feature.go
- internal/controller/datadogagent/feature/externalmetrics/feature.go
- internal/controller/datadogagent/feature/factory.go
- internal/controller/datadogagent/feature/helmcheck/feature.go
- internal/controller/datadogagent/feature/kubernetesstatecore/feature.go
- internal/controller/datadogagent/feature/orchestratorexplorer/envvar.go
- internal/controller/datadogagent/feature/orchestratorexplorer/feature.go
- internal/controller/datadogagent/feature/orchestratorexplorer/feature_test.go
- internal/controller/datadogagent/feature/remoteconfig/feature.go
- internal/controller/datadogagent/feature/test/factory_test.go
- internal/controller/datadogagent/feature/test/testsuite.go
- internal/controller/datadogagent/feature/types.go
- internal/controller/datadogagent/feature/types_test.go
- internal/controller/datadogagent/finalizer.go
* Splits features into configured and enabled features, where configured features are features that are not enabled but may require configuration
* Changes the way we define a `RequiredComponent`'s `IsEnabled` and `IsConfigured`
* `IsEnabled`: `nil` = feature disabled, `true` = feature enabled, `false` should not be used
* `IsConfigured`: `true` = at least one container specified in `RequiredComponent.Containers`, `false` = no containers in `RequiredComponent.Containers`
* Adds `RequiredComponent.Containers` to features that previously only set `RequiredComponent.IsEnabled`
* Adds a path to disable the orchestrator explorer feature
https://datadoghq.atlassian.net/browse/CECO-1895
Have only checked the orchestrator explorer and remote config features. Other features may be enabled by …
> Allow disabling features that are enabled by default

- Dockerfile
- bundle.Dockerfile
- check-operator.Dockerfile
Switch to [ubi-micro](https://docs.redhat.com/en/documentation/red_hat_enterprise_linux/8/html/building_running_and_managing_containers/assembly_types-of-container-images_building-running-and-managing-containers#con_understanding-the-ubi-micro-images_assembly_types-of-container-images) to reduce potential CVEs.
> Change Operator base image from ubi-minimal to ubi-micro

- .gitlab-ci.yml
- Separate `latest` image publish jobs into their own stage to reduce potential error
- Allow community operators job to run without depending on the preflight submission job
> [tooling][gitlab] separate publishing latest images, tweak community operators job

- Makefile
Sort `GIT_TAG` and `TAG_HASH` vars by semver rather than default sort. Drawn from https://gist.github.com/loisaidasam/b1e6879f3deb495c22cc?permalink_comment_id=3008151#gistcomment-3008151
Prevent 1.9.X from being the default latest tag when building locally
Run `make build` locally and make sure the default version used in the build command is the latest tag.
```
go build -ldflags '-w -s -X github.com/DataDog/datadog-operator/pkg/version.Commit=3ffc9e951b9046a90327c4a645bd02a66246f3e4 -X github.com/DataDog/datadog-operator/pkg/version.Version=[CHECK_THIS_VERSION] -X github.com/DataDog/datadog-operator/pkg/version.BuildTime=2025- …
```
> [tooling] sort git tag by semver

- internal/controller/datadogagent/feature/remoteconfig/feature.go
Following https://github.com/DataDog/datadog-operator/pull/1792, we can now configure RC feature (to disable it via env var) without having the component required. 
Avoid un-needed objects from being created if DCA component is not needed by any features (since RC was requiring DCA component, we would enter the enabledefault DCA dependencies even if all other features did not need it)
> [Remote config feature] Agent & DCA are not required components, but need to be configured

- internal/controller/datadogagent/feature/servicediscovery/feature.go
- internal/controller/datadogagent/feature/servicediscovery/feature_test.go
This PR adds additional mounts required for Service Discovery to run with eBPF Runtime-Compilation.
Add support for runtime-compilation
Runtime-Compilation requires mounting `/usr/src` which is not possible on GKE COS. The PR has a guard against that which requires introspection to be enabled.
* Agent: v7.64.0
The PR was tested on a GKE cluster:
- Install the operator on the cluster:
- The docker-build & docker-push tasks can be used to make it available to a registry the cluster can reach.
- An updated datadog-operator and datadog-crds Helm charts were used to install the operator, and allow setting the new config option.
- Install the agent using the operator.
- The …
> servicediscovery: add support for eBPF runtime-compilation

- Dockerfile
Install CA certificate bundle in operator base image
The Go client uses the CA bundle to communicate with the Datadog API for resources (e.g. DatadogMonitor). Without this bundle, we encounter errors:
`error validating monitor (url.Error): Post "https://api.datadoghq.com/api/v1/monitor/validate":
tls: failed to verify certificate: x509: certificate signed by unknown authority`
Deploy a DatadogMonitor or something that uses the Go client to communicate with DD API and ensures the object gets created/ no TLS error about unknown authority
> Add CA certificate bundle to ubi9-micro base

- internal/controller/datadogagent/feature/apm/feature.go
Adds the `DD_APM_ERROR_TRACKING_STANDALONE_ENABLED` flag to the `agent`
This env variable should be present in the core agent as well
> [errortracking] add error tracking standalone var to the core agent

- internal/controller/datadogagent/component/agent/new.go
Allow to configure SlowStartAdditiveIncrease
Needs to be tested internally on metrics clusters.
> [BARX-910] Allow to configure SlowStartAdditiveIncrease

- .github/workflows/backport-pr.yml
Only allow backport PR to be created when the `backport/<branch_name>` label is added AFTER it's been merged 
i fiddled with this a lot, but here's an example: 
- https://github.com/DataDog/datadog-operator/actions/runs/14088627686/job/39459290489. The job is failing because the noop change I tested it on causes a merge conflict
- example of replicating it manually 
- will test after this pr is merged by adding the temporary testing label I made, `backport/testing` to this PR
> Update backport PR conditions

- internal/controller/datadoggenericresource/synthetics_test.go
Changes foo id to integer string id
Avoid erroring sometimes: https://gitlab.ddbuild.io/DataDog/datadog-operator/-/jobs/867820771#L659
```
2025-03-27T14:08:36Z	ERROR	failed to finalize 	{"test:": "a DatadogGenericResource object (with the finalizer) has a deletion timestamp", "custom resource Id": "", "error": "error parsing resource ID: strconv.ParseInt: parsing \"\": invalid syntax"}
```
> (chore) Change test-id to integer string id

- .gitlab-ci.yml
The `e2e` test stage in gitlab was previously set to `manual` on conductor triggered jobs, which blocked the [pipeline](https://gitlab.ddbuild.io/DataDog/datadog-operator/-/pipelines/60125805) as the `release` and `deploy` stages could not run until `e2e` was manually triggered. 
Fixed by setting the `e2e` stage to never run on conductor triggered jobs. This causes the stage to be skipped. from Github Actions docs:
> A job that is skipped will report its status as "Success". 
This will allow subsequent nightly build pipeline stages to run
- verify that if e2e tests complete …
> [e2e] Disable e2e tests on nightly build

- .gitlab-ci.yml
- test/e2e/kind_test.go
- test/e2e/provisioners/kind.go
* Changes instance type to use m5.xlarge (4 vCPU, 16 GiB) instead of default `t3.medium`
* Enables timestamps in gitlab logs
Speed up E2e tests
Ease up troubleshooting when investigating bottlenecks
> (chore) E2E: use m5.xlarge instead of default t3.medium

- pkg/defaulting/images.go
Update latest default fips proxy container
> update default fips-proxy image version to 1.1.9

- internal/controller/datadogagent/component/clusterchecksrunner/default.go
Allow custom checks to run on cluster checks runners
https://datadoghq.atlassian.net/browse/CONS-7175
We mount this in helm: https://github.com/DataDog/helm-charts/blob/542ee739117f200b79d916b4dcc209ab0ee57220/charts/datadog/templates/agent-clusterchecks-deployment.yaml#L109-L113
> Add checksd volume to ccr init-config

- cmd/kubectl-datadog/clusteragent/leader/leader.go
Falls back to try getting leader from configmap for `clusteragent` even if leases are supported, in the case getting leader from lease failed
Allows to get leader from configmap even if leases are supported in the environment, in a situation where configmap is still being used for leader election of DCA
* As https://github.com/DataDog/datadog-operator/pull/1375, check by default, we try to retrieve leader when `leader_election_default_resource` is set to `lease`
* In an env with DCA leader election in configmap (https://github.com/DataDog/datadog-agent/blob/5e42ef8869290dcdec42772b0b71538485879f8b/pkg/config/setup/config.go#L515 …
> [kubectl plugin] Fallback to configmap leader attempt for `clusteragent` if lease failed

- internal/controller/datadogagent/component/agent/default.go
- internal/controller/datadogagent/component/clusteragent/default.go
- internal/controller/datadogagent/component/clusterchecksrunner/default.go
- pkg/constants/utils_test.go
- pkg/defaulting/images.go
- pkg/defaulting/images_test.go
Use convenience methods for default Agent and Cluster Agent images
Clean up unused convenience methods to reduce confusion
This change is noop
> [defaulting] clean up unused image methods

- api/datadoghq/v1alpha1/datadogpodautoscaler_types.go
- api/datadoghq/v1alpha2/datadogpodautoscaler_types.go
- config/crd/bases/v1/datadoghq.com_datadogpodautoscalers.yaml
- internal/controller/datadogagent/feature/orchestratorexplorer/feature.go
- internal/controller/datadogagent/feature/orchestratorexplorer/feature_test.go
- pkg/testutils/builder.go
Bump Autoscaling to `v1alpha2`, only version supported in 7.64+.
Similar to https://github.com/DataDog/helm-charts/pull/1767
Autoscaling working with 7.64+
Cluster Agent 7.64+
> [autoscaling] Move to v1alpha2 as only supported version for Cluster Agent 7.64+

- internal/controller/datadogagent/feature/gpu/envvar.go
- internal/controller/datadogagent/feature/gpu/feature.go
- internal/controller/datadogagent/feature/gpu/feature_test.go
* Agent: N/A
Agents that do not support this feature will just ignore the environment variable.
Unit tests validate that the flag is present.
> Add feature flag when GPU monitoring is enabled

- .github/workflows/backport-pr.yml
* use `datadog-githubops-containers[bot]` instead of `github-actions[bot]` and added keys in repo to create a temporary token
* fix formatting of backport PR title to standardize with datadog agent backport PRs
Test by adding the `backport/1.14` label to this PR after it is merged, verify that the resulting cherry-pick commit is signed
> Add commit signing to backport workflow PRs

- pkg/defaulting/images.go
* Bump Agent to 7.64.2
* Bump Agent to 7.64.3
> Bump Agent to 7.64.3 (#1847)

- .github/workflows/backport-pr.yml
* copies the milestone from the PR where the backport PR workflow is triggered and applies it to the backport PR
* backport PR fails the milestone check and we have to manually add it. If we add this, no other work is needed to create a backport other than adding a label. 
Test by adding the backport/1.14 label to this PR after it is merged, verify that the resulting cherry-pick PR has the right milestone.
> [tooling] Add milestone to automated backport PR 

- cmd/main.go
- internal/controller/setup.go
`SlowStartAdditiveIncrease` was added in https://github.com/DataDog/datadog-operator/pull/1821 but there is no config flag to set it
BARX-910
> [BARX-910] Add a config flag for SlowStartAdditiveIncrease

- api/datadoghq/v1alpha1/datadogpodautoscaler_types.go
- api/datadoghq/v1alpha2/datadogpodautoscaler_types.go
- config/crd/bases/v1/datadoghq.com_datadogpodautoscalers.yaml
- internal/controller/datadogagent/feature/orchestratorexplorer/feature.go
- internal/controller/datadogagent/feature/orchestratorexplorer/feature_test.go
- pkg/testutils/builder.go
> [autoscaling] Move to v1alpha2 as only supported version for Cluster Agent 7.64+ (#1845)

- cmd/main.go
- internal/controller/setup.go
Backport https://github.com/DataDog/datadog-operator/pull/1857
> [backport 1.14] Add flag to configure SlowStartAdditiveIncrease

- internal/controller/datadogagent/feature/sbom/feature.go
- internal/controller/datadogagent/feature/sbom/feature_test.go
The `sbom.containers_image.*` and `sbom.host.*` configuration should only target the core agent, and should only be applied to this container, not all containers. This PR fixes this issue by ensuring the env variables are only applied to the core agent and fixes the associated tests.
Given the following spec,
```
metadata:
name: datadog
spec:
global:
credentials:
apiKey: XXXXXX
features:
sbom:
enabled: true
containerImage:
enabled: true
host:
enabled: true
```
testing should ensure container and host sboms are still reported to …
> fix SBOM feature env vars applying to all agents instead of just core

- internal/controller/datadogslo/controller.go
- internal/controller/datadogslo/slo.go
CECO-2151/CONS-7192
In SLO finalizer we try to reconcile if Datadog API call to delete SLO resource fails, regardless of the failure. Which means - in a simple scenario where users first deletes SLO in UI and then deletes SLO customer resource leads to finalizer failures and customer resource never getting cleaned up. Current workaround is removing finalizer from the resource.
The change handles 404 Not Found http error code and lets controller finalizer resource.
1. Deploy Operator with configured API, APP key and SLOs enabled.
1. Apply sample SLO custom resource.
1. In the …
> SLO deletion, ignore 404 error in finalizer

- config/rbac/role.yaml
- internal/controller/datadogagent/finalizer.go
- internal/controller/datadogagent/finalizer_test.go
- internal/controller/datadogagent/store/store.go
- internal/controller/datadogagent/store/store_test.go
- internal/controller/datadogagent_controller.go
Clean up existing finalizer. Most dependencies should be deleted through owner refs so we don't need to recreate the dependencies in the store. Cluster scoped dependencies are delete manually based on label
https://datadoghq.atlassian.net/browse/CECO-2210
Create a DatadogAgent and delete it. Ensure dependencies related to the DDA are deleted, e.g. configmaps, secrets, etc. Be sure to check that cluster scoped resources such as clusterroles and clusterrolebindings are deleted.
> Clean up finalizer

- internal/controller/datadogagent/global/global.go
Add an `else if` so that the FIPS proxy sidecar will never be configured if `useFIPSAgent` is true.
> small fix for FIPS configuration

- api/datadoghq/v2alpha1/datadogagent_types.go
- api/datadoghq/v2alpha1/zz_generated.openapi.go
- config/crd/bases/v1/datadoghq.com_datadogagents.yaml
- config/crd/bases/v1/datadoghq.com_datadogagents_v2alpha1.json
- docs/configuration.v2alpha1.md
* Change the doc comment in otel feature to mention it's disabled by default as is done in code:
* https://github.com/DataDog/datadog-operator/blob/732b24c97a31dcf29e428aa65ed71a07caa2b750/internal/controller/datadogagent/defaults/datadogagent_default.go#L248
* https://github.com/DataDog/datadog-operator/blob/732b24c97a31dcf29e428aa65ed71a07caa2b750/internal/controller/datadogagent/defaults/datadogagent_default.go#L30
* While QAing, I had to "manually" enable the otel feature for it to start the otel Agent despite it being documented as enabled by default.
> [Doc] Documents that otel-agent is not enabled by default

- .github/workflows/backport-pr.yml
Backport PR workflows are failing to add the milestone to the backport PR because of an error in fetching the correct PR number. `backportData` is formatted as: `{<base>:<pr number>}` when the label added to a PR is `backport/<base>`. This fix will get the PR number regardless of the key, since that will change with each release. I missed this because I was testing with the label `backport/backport`
Tested in a private repo:
code changed
output from tibdex/backports step
parsed PR number is correct
milestone is correctly added to test pr
> [tooling] fix backport workflow pr number fetching

- .github/workflows/backport-pr.yml
Add `qa/skip-qa` label automatically to all PRs created by the backport label, to prevent duplicating QA cards in the release process.
> add skip-qa label to backport PRs by default

- .github/workflows/build.yml
- .github/workflows/main.yml
- .github/workflows/release.yaml
- .gitlab-ci.yml
- Dockerfile
- api/go.mod
- check-operator.Dockerfile
- go.mod
- go.work
- hack/update-golang.sh
- test/e2e/go.mod
* Updates to Go `1.23.8` running `make update-golang`
* Updates `update-golang.sh` script to look for `library/golang` for internal Golang mirrors
* Fixes CVE-2025-22871 (medium sev):
```shell
helpers (gobinary)
Total: 1 (UNKNOWN: 0, LOW: 0, MEDIUM: 1, HIGH: 0, CRITICAL: 0)
┌─────────┬────────────────┬──────────┬────────┬───────────────────┬────────────────┬──────────────────────────────────────────────────────────┐
│ Library │ Vulnerability  │ Severity │ Status │ Installed Version │ Fixed Version  │                          Title                           │
├─────────┼────────────────┼──────────┼────────┼───────────────────┼────────────────┼──────────────────────────────────────────────────────────┤
│ stdlib  │ CVE-2025-22871 │ MEDIUM   │ fixed  │ v1.23.6           │ 1.23.8, 1.24.2 │ …
```
> Update to Go 1.23.8

- internal/controller/datadogagent/global/dependencies.go
- internal/controller/datadogagent/merger/service.go
- pkg/equality/equality.go
Checks only selector, ports, and internal traffic policy for service equality
https://datadoghq.atlassian.net/browse/CECO-2266
k8s defaults cause the current service equality check to fail, which leads to unnecessary service update requests being sent to k8s
Check k8s audit logs to see how frequently update requests are sent for services created by the operator. Also visible in the operator rollout dashboard
> Limit service equality check

- internal/controller/datadogagent/feature/autoscaling/const.go
- internal/controller/datadogagent/feature/autoscaling/envvar.go
- internal/controller/datadogagent/feature/autoscaling/feature.go
- internal/controller/datadogagent/feature/autoscaling/feature_test.go
- internal/controller/datadogagentinternal/feature/autoscaling/const.go
- internal/controller/datadogagentinternal/feature/autoscaling/envvar.go
- internal/controller/datadogagentinternal/feature/autoscaling/feature.go
- internal/controller/datadogagentinternal/feature/autoscaling/feature_test.go
Set environment variables to enable local fallback by default when kubernetes autoscaling feature is enabled
Avoid users having to manually set env var overrides to make use of the local fallback feature
Should the corresponding changes be made in `datadogagentinternal/` as well?
* Agent: v7.65.0
* Cluster Agent: v7.65.0
1. Deploy the agent via the operator and enable autoscaling
```
metadata:
name: datadog
spec:
global:
clusterName: "jenn-operator"
credentials:
apiSecret:
logLevel: debug
kubelet:
features:
enabled: true
customResources:
- …
```
> [feature/autoscaling] Enable local fallback by default when autoscaling enabled

- .golangci.toml
* Adds `exportloopref` to the list of disabled linters
* Avoid warning when running lint commands:
```shell
vscode ➜ /workspaces/datadog-operator $ make lint
go vet ./...
bin/linux-aarch64/golangci-lint run ./... ./api/... ./test/e2e/...
WARN The linter 'exportloopref' is deprecated (since v1.60.2) due to: Since Go1.22 (loopvar) this linter is no longer relevant. Replaced by copyloopvar. 
```
* `copyloopvar` is enabled per `enable-all` replacing it, and we build using Go 1.23:
```shell
vscode ➜ /workspaces/datadog-operator (main) $ bin/linux-aarch64/golangci-lint linters
Enabled by your configuration linters:
asasalint: check for pass []any as any in variadic func(...any) [fast: false, auto-fix: false]
asciicheck: checks that all code identifiers does not have non-ASCII symbols in the …
```
> (chore) Disable `exportloopref` linter due to depreciation

- api/datadoghq/common/const.go
- internal/controller/datadogagent/controller_reconcile_agent.go
- internal/controller/datadogagent/controller_reconcile_agent_test.go
- internal/controller/datadogagent/ddai.go
- internal/controller/datadogagent/ddai_test.go
- internal/controller/datadogagentinternal/controller_reconcile_agent.go
- internal/controller/datadogagentinternal/controller_reconcile_agent_test.go
- internal/controller/datadogagentinternal/controller_reconcile_v2.go
- internal/controller/datadogagentinternal/controller_reconcile_v2_helpers.go
Ensure the DS remains the same when switching from DDA to DDAI and back. This should result in no DS or node agent pod restarts (as long as the DCA token is set in a secret).
Lots of this should be uncommented in future PRs and have been marked with `TODO`.
https://datadoghq.atlassian.net/browse/CECO-2014
> Keep DS same between DDA and DDAI

- internal/controller/datadogagent/component/clusterchecksrunner/default.go
Disables the process configuration from loading on the cluster check runner
CLC runner making periodic requests to the process endpoint 
N/A
Fixes issues on CLC runners present in Agent version 7.65+
N/A
> bug: Disable process config in clc runner

- repository.datadog.yml
I added `mergegate` exceptions for the github-actions bot, but the backport PR workflows made after merging my initial changes still failed the `mergegate` CI check. Updated the email address to point to the right bot.
Checked that the email address is correct:
> Fix mergegate exception bot email addresses

- internal/controller/datadogagentinternal/component/agent/default.go
- pkg/images/images.go
changed the otel image default that is being used, now includes the -full suffix
Otel image was outdated, using beta tag
On a local kind cluster, have spec.features.otelCollector.enabled set to true in the DDA manifest. Then describe an agent, and go under Containers.otel-agent and make sure that the image is gcr.io/datadoghq/agent:7.66.1-full (whatever agent version you use, just make sure it has "-full" as the suffix).
> New OTEL Image

- .gitlab-ci.yml
Allow e2e tests to fail so as not to block publishing RC images. 
> E2E enable allow_failure on release branches

- internal/controller/datadogagent/profile.go
- internal/controller/datadogagent/profile_test.go
Use DDA as ownerref instead of DAP as ownerref
Deleting profile DDAIs manually for deleted DAPs will be handled in a future PR
> Keep DDA ownerref for profile DDAI

- internal/controller/datadogagent/profile.go
- internal/controller/datadogagent/profile_test.go
- internal/controller/datadogagentinternal/controller_reconcile_agent.go
- internal/controller/datadogagentinternal/controller_reconcile_agent_test.go
* When creating profile DDAIs, include the label `agent.datadoghq.com/datadogagentprofile` in DDAI meta
* Removes `scheme` argument from `setProfileDDAIMeta` as it is not used
* When reconciling Agent, check if non-default profile label and if yes, use DS instead of EDS if enabled
* Keeping behaviour with DDA controller: we do not create EDS for profiles
* Create a profile
* Ensure label is present on DDAI
* Ensure DS gets created instead of EDS for profile pods, while EDS is present for non-profile/default pods
* Create a profile
* Ensure label is present on DDAI
> [CECO-2029][DatadogAgentInternal] Add profile label to non-default profile DDAIs and do not create EDS if non-default profile DDAI

- internal/controller/datadogagent/override/ddai_utils.go
- internal/controller/datadogagent/override/ddai_utils_test.go
- internal/controller/datadogagentinternal/component/clusterchecksrunner/default.go
* "Backports" https://github.com/DataDog/datadog-operator/pull/1979 to DDAI controller while `component` is still duplicated between both controllers, causing drifts
* Follow-up to https://github.com/DataDog/datadog-operator/pull/1976/s: add the DCA token annotation on CCR
* Test in staging, we want to reduce drift as much as possible
* Tested on `kind` by enabling / disabling DDAI with a `DatadogAgent` with CCR and `spec.global.clusterAgentToken` and ensured the deployment was stable (no restart, just patched ownerref)
> [CECO-2029][DatadogAgentInternal] Fix CCR when enabling DDAI

- internal/controller/datadogagent/ddai_test.go
- internal/controller/datadogagent/profile.go
- internal/controller/datadogagent/profile_test.go
Merge DDAI and profile affinities keeping the DDAI affinities instead of replacing them
🐛 
> Merge DDAI affinities instead of replacing when using profiles

- .gitlab-ci.yml
https://datadoghq.atlassian.net/browse/CECO-2315 Update base images in Operator since Ubuntu 20.04 was EOL in May 2025
verify that `build-operator-image` jobs in gitlab pipeline are using the update image on Ubuntu 22.04
> [CECO-2315] Update gitlab base image to use ubuntu 22.04

- cmd/main.go
- internal/controller/setup.go
- pkg/kubernetes/rbac/const.go
* Introduces `CleanupDatadogAgentInternalResources` that tries to list all DDAIs a minute after being elected leader when DDAI controller is disabled, and deletes them after patching to remove the finalizer
* We need to wait a small delay to have DDA patch ownerref otherwise, DDA has to re-create daemonsets and deploys
* Removing orphaned resources when DDAI controller is disabled, so they are not immediately re-reconciled when DDAI is re-enabled
> [CECO-2321][DatadogAgentInternal] Delete DDAIs if disabled

- pkg/controller/utils/metadata/metadata_forwarder.go
- pkg/controller/utils/metadata/metadata_forwarder_test.go
Follow up to #1999 to fix URL handling when DD_URL is set
Run the Datadog Operator. Check the logs to see if the metadata forwarder runs without issue.
Then try adding DD_SITE (datadoghq.com) on the Operator deployment.
Then try adding DD_URL (https://app.datadoghq.com) on the Operator deployment.
> fix dd_url handling

- internal/controller/datadogagent/feature/gpu/feature.go
- internal/controller/datadogagent/feature/gpu/feature_test.go
Exposes the `debugfs` mount in system-probe when GPU monitoring is enabled.
Ensure we can start the process event data stream, which is required for GPUM.
Related ticket: https://datadoghq.atlassian.net/browse/EBPF-768
* Agent: N/A
Covered by unit tests.
> Add missing debugfs mount for GPU monitoring

- pkg/images/images.go
Update default agent images to 7.68.2
Deploy a DatadogAgent with cluster check runners enabled and no image overrides. Ensure that 7.68.2 is running for the node agent, cluster checks runner and cluster agent.
> update default agent images to 7.68.2

- internal/controller/datadogagent/component/objects/network.go
Update network policy metadata to match current dependencies. We're changing the instance label value, so switch to using agent component
https://datadoghq.atlassian.net/browse/AGENTONB-2318
* Use a previous operator image w/o this pr and enable [network policies](https://github.com/DataDog/datadog-operator/blob/3b6feaaca09ca5178d9c06e08e3bdb5d0c39eb2b/api/datadoghq/v2alpha1/datadogagent_types.go#L1586). Check the pod selector uses `app.kubernetes.io/instance`
* Update the operator and check that the network policy pod selector changes from `app.kubernetes.io/instance` to `agent.datadoghq.com/component`
> Update network policy metadata

- api/datadoghq/common/datadogpodautoscaler_types.go
- config/crd/bases/v1/datadoghq.com_datadogpodautoscalers.yaml
- config/crd/bases/v1/datadoghq.com_datadogpodautoscalers_v1alpha1.json
- config/crd/bases/v1/datadoghq.com_datadogpodautoscalers_v1alpha2.json
Increase maximum stabilization window and up/downscale period seconds from 30m to 1h
Allow users to set a longer stabilization window to prevent constant flapping / quick up or downscales 
> [datadogpodautoscalers] Increase max stabilization window/scaling period from 30m to 1h

- internal/controller/datadogagentinternal/controller_reconcile_agent.go
* Ensures the same labels are used for DDAI daemonsets like DDA following #2054 
* Do not restart DS when enabling DDAI
* With profile enabled/disabled, check that when enabling DDAI, the pods are not restarted (no DS updates except ownerref, both for default DS and profile DS)
> [AGENTONB-2318][DatadogAgentInternal] Update DDAI DS selectors like DDA

- .github/chainguard/self.release.create-release.sts.yaml
Solves this error: https://github.com/DataDog/datadog-operator/actions/runs/16727988099/job/47348965719
Local tests:
```
DDOCTOSTS_ID_TOKEN=$(cat claim.txt) dd-octo-sts check --scope DataDog/datadog-operator --policy self.release.create-release
```
with the following claim.txt: 
[claim.txt](https://github.com/user-attachments/files/21581123/claim.txt)
> [SINT-3831] fix dd-octo-sts policy

- .github/chainguard/self.backport-pr.create-pr.sts.yaml
- .github/workflows/backport-pr.yml
This is part of an initiative lead by SDLC security to [harden Github security settings](https://datadoghq.atlassian.net/wiki/spaces/SECENG/pages/3913581900/GitHub+Workflow+Token+Permissions+GITHUB_TOKEN). To do so, we need to move away from GITHUB_TOKEN having the permission to approve and merge PRs, which is a behaviour we see in .github/workflows/release.yaml.
Instead, [dd-octo-sts](https://datadoghq.atlassian.net/wiki/spaces/SECENG/pages/4705912130/DD+Octo+STS) is an alternative to provide ephemeral scoped tokens delivering the same features with improved security.
This PR implements the migration to dd-octo-sts.
Follow-up of https://github.com/DataDog/datadog-operator/pull/2089, hence bearing the same labels
If the app that was used in this logic is not used anymore, let's get rid of …
> [SINT-3831] use dd-octo-sts for backport workflow

- pkg/images/images.go
Update latest default fips proxy container
enable the fips proxy
make sure the new image is being used by default
> [AGENTRUN-610] Update FIPS proxy version references to 1.1.15

- internal/controller/datadogagent/feature/gpu/feature.go
- internal/controller/datadogagent/feature/gpu/feature_test.go
Sets `DD_GPU_MONITORING_ENABLED` in the core agent, when `privilegedMode` is enabled (SP GPU module should run)
core-agent reads this flag in runtime to determine which collectors should be created, without setting it explicitly, we won't get the real value of this config, since it is passed as an env var to system-probe
this is a workaround until we have a better config sync and resolution between agent components
> GPUM: set DD_GPU_MONITORING_ENABLED in the core agent

- internal/controller/datadogagent/controller_v2_test.go
- internal/controller/datadogagent/feature/controlplanemonitoring/feature.go
Add etcd cert checks for node agent and cluster checks runner in controller tests
fixed naming for etcd certs, noop change (`CoreAgentContainerName` and `ClusterChecksRunnersContainerName` are equal)
[What inspired you to submit this pull request?](https://datadoghq.atlassian.net/browse/AGENTONB-2454)
noop changes, only testing improvements.
> Add etcd cert checks for control plane monitoring tests

- config/rbac/role.yaml
- internal/controller/datadogagent/feature/orchestratorexplorer/rbac.go
- internal/controller/datadogagent_controller.go
This PR updates orchestrator check's RBAC to List/watch on all Datadog custom resources if the orchestrator check is enabled
We want to collect all datadog custom resources in the orchestrator check 
https://github.com/DataDog/datadog-agent/pull/39989
Deploy the latest operator and check if orchestrator check's cluster role contains
```
- apiGroups:
- datadoghq.com
resources:
- '*'
verbs:
- list
- watch
```
> CAP-2779 update orchestrator check RBAC

- internal/controller/datadogagent/controller_v2_test.go
- internal/controller/datadogagent/feature/controlplanemonitoring/const.go
- internal/controller/datadogagent/feature/controlplanemonitoring/feature.go
- internal/controller/datadogagent/feature/controlplanemonitoring/feature_test.go
- Mount control plane checks to subfolders in `etc/datadog-agent/conf.d` instead of directly to the root. 
- Resolves issue where when control plane monitoring is enabled (by default), other contents of the root folder get wiped. 
- Update controller testing with the updated control plane monitoring configuration in DCA
Feedback from #1984 
Tested on Openshift and EKS; the testing instructions below are for Openshift. 
* Cluster Agent: v7.69.1
- Deploy custom operator to openshift cluster ([instructions](https://datadoghq.atlassian.net/wiki/x/5AJWOQE)) with the flag `--introspectionEnabled=true` configured in `spec.container.args` in `bundle/manifests/datadog-operator.clusterserviceversion.yaml` …
> Mount control plane checks to subfolders 

- pkg/images/images.go
Update FIPS proxy version references to 1.1.16
enable the fips proxy
make sure the new image is being used by default
> [AGENTRUN-678] Update FIPS proxy version references to 1.1.16

- .gitlab-ci.yml
* Merge the `.new_e2e_template` GitLab job template with the `e2e` job because this template was used only at a single location.
* Add a `retry` option to e2e tests because they’re currently a bit flaky.
E2e tests are flaky and we need to retry them manually.
Look at CI status.
> Add retries to e2e tests CI jobs

- config/rbac/role.yaml
- internal/controller/datadogagent/feature/orchestratorexplorer/rbac.go
- internal/controller/datadogagent_controller.go
- pkg/kubernetes/rbac/const.go
Update orchestrator check permission to include:
- Argo Rollouts (argoproj.io/v1alpha1/rollouts)
- karpenter.sh/*
- karpenter.k8s.aws/*
- karpenter.azure.com/*
required by https://github.com/DataDog/datadog-agent/pull/40430
> add permission for argorollouts and karpenter

- docs/installation.md
Just adds a small section on the install page that links more visibly to the config page. Only a docs change.
Customers were having trouble being directed to the configuration spec.
> README: add link to configuration page

- internal/controller/datadogagent/feature/cws/feature.go
- internal/controller/datadogagent/feature/cws/feature_test.go
This PR removes a few unused mounts/envvars/volumes etc applied on the security agent when the CWS feature is used that are not used and only valid on the system-probe.
> [CWS] clean up unused security agent features

- internal/controller/datadogagent/store/store.go
* Ensures we set `resourceVersion` for PDBs to properly reconciliate them following manual edits
https://github.com/DataDog/datadog-operator/issues/2186 and https://stackoverflow.com/questions/71581444/how-to-fix-metadata-resourceversion-invalid-value-must-be-specified-for-an/73639549#73639549
* Create DDA with PDBs on either DCA or CCR
* Label them with `k label pdb XXX foo=bar`
* Ensure the label is removed at the next reconciliation loop and no error logs:
```json
{"level":"ERROR","ts":"2025-09-18T14:28:00.674Z","logger":"controllers.DatadogAgent","msg":"store.store …
```
> [AGENTONB-2523] Set `resourceVersion` in PodDisruptionBudget reconciliation

- LICENSE-3rdparty.csv
- go.mod
- go.sum
- pkg/controller/utils/datadog/metrics_forwarder.go
- pkg/controller/utils/datadog/metrics_forwarder_test.go
Finishes migration from zorkian to official go client by using go client for validation and sending events. 
Apply any datadog resource yaml (monitor/agent/slos/dashboard). There should be a "Detect..." event shown in the [event management page](https://app.datadoghq.com/event/explorer?). 
As for testing validation, as long as there is no error (which there is none) from `delegatedValidateCreds` it is working.
> [metrics-forwarder] Use official go client for Validation and sending events

- internal/controller/datadogagent/controller_reconcile_v2.go
- internal/controller/datadogagent/controller_reconcile_v2_common.go
- internal/controller/datadogagent/ddai.go
- internal/controller/datadogagent/ddai_test.go
- internal/controller/datadogagentinternal/controller_reconcile_v2.go
- internal/controller/datadogagentinternal/controller_reconcile_v2_common.go
- pkg/agentprofile/agent_profile.go
- pkg/agentprofile/status.go
- pkg/condition/condition.go
Reduce status update frequency for ddai and dda
https://datadoghq.atlassian.net/browse/AGENTONB-1698
https://datadoghq.atlassian.net/browse/AGENTONB-2556
https://datadoghq.atlassian.net/browse/AGENTONB-2557
Check internal dashboard to confirm requests to k8s have reduced
> Reduce status update frequency

- .github/chainguard/self.stale.manage-stale.sts.yml
- .github/workflows/check-issue-status.yml
- .github/workflows/issue-labeler.yml
- .github/workflows/stale.yml
Add workflows for the management of stale issues/PR
- Set a pending label at issue creation
- Removes this label whenever a Datatog employee adds a comment to an issue
- Adds a schedule call for setting issues as stale or closing stale issues
[datadoghq.atlassian.net/browse/ACIX-1024](https://datadoghq.atlassian.net/browse/ACIX-1024)
Improvement of our interactions with external contributors
This workflow is the same as the one set in the datadog-agent repository. As described in the [repository management document](https://docs.google.com/document/d/1hRCYeiLtJ6TdGmrrB5UJ2sF-Dbd9rbQPW2OqPNxJ5kc/edit?tab=t.0#heading=h.hcw3d3cr97p), in agreement with Open Source community.
> feat(github): Add workflows for stale issues/PR management

- internal/controller/datadogagent/feature/usm/feature.go
- internal/controller/datadogagent/feature/usm/feature_test.go
Match the volume mounts of USM to the process-agent to the ones set by CNM
We didn't mount the correct volumes to the process agent, hence, if CNM wasn't enabled or after runProcessChecksInCoreAgent config turned on by default, the process-agent container didn't have the correct mounts
> usm: Match volume mounts to the CNM
