DataDog/datadog-operator

- pkg/controller/datadogagentdeployment/agent_test.go
Split Test_newExtendedDaemonSetFromInstance to simplify dev experience running the test.
Should become a bit easier to contribute more tests and run these tests individually.
> Refactor and split Test_newExtendedDaemonSetFromInstance

- pkg/controller/utils/datadog/forwarders_manager.go
- pkg/controller/utils/datadog/metrics_forwarder.go
- pkg/controller/utils/datadog/metrics_forwarder_test.go
- pkg/secrets/secrets.go
- pkg/secrets/secrets_test.go
- pkg/secrets/test/decryptor/dummy_decryptor.py
- pkg/secrets/types.go
- pkg/secrets/utils.go
- pkg/secrets/utils_test.go
Support decrypting secrets using a secret backend binary
Avoid declaring plaintext secrets in the CR manifest
> Support secret backend

- deploy/crds/datadoghq.com_datadogagents_crd.yaml
- pkg/apis/datadoghq/v1alpha1/const.go
- pkg/apis/datadoghq/v1alpha1/datadogagent_default.go
- pkg/apis/datadoghq/v1alpha1/datadogagent_types.go
- pkg/apis/datadoghq/v1alpha1/test/new.go
- pkg/apis/datadoghq/v1alpha1/zz_generated.deepcopy.go
- pkg/apis/datadoghq/v1alpha1/zz_generated.openapi.go
- pkg/controller/datadogagent/clusteragent.go
- pkg/controller/datadogagent/datadogagent_controller_test.go
- pkg/controller/datadogagent/service.go
Adds configuration setting for the metrics provider external port.
> Add configuration for metrics provider port

- pkg/controller/datadogagent/agent.go
- pkg/controller/datadogagent/datadogagent_controller.go
> Test flaky end2end test

- deploy/olm-catalog/datadog-operator/0.1.1/datadoghq.com_datadogagents_crd.yaml
configuration update after several PR merges on Master
files changes after:
```console
$ make generate
$ make VERSION=0.1.1 generate-olm
```
> run 'make generate-olm' after PR merged

- .gitlab-ci.yml
- .golangci.toml
- pkg/apis/datadoghq/v1alpha1/const.go
- pkg/apis/datadoghq/v1alpha1/datadogagent_default.go
- pkg/apis/datadoghq/v1alpha1/datadogagent_types.go
- pkg/apis/datadoghq/v1alpha1/test/new.go
- pkg/controller/datadogagent/agent.go
- pkg/controller/datadogagent/agent_test.go
- pkg/controller/datadogagent/clusteragent.go
- pkg/controller/datadogagent/clusteragent_metricsserver.go
- pkg/controller/datadogagent/clusteragent_test.go
- pkg/controller/datadogagent/clusterchecksrunner.go
- pkg/controller/datadogagent/common_configmap.go
- pkg/controller/datadogagent/common_rbac.go
- pkg/controller/datadogagent/const.go
- pkg/controller/datadogagent/datadogagent_controller.go
- pkg/controller/datadogagent/datadogagent_controller_test.go
- pkg/controller/datadogagent/poddisruptionbudget.go
- pkg/controller/datadogagent/secret.go
- pkg/controller/datadogagent/service.go
- pkg/controller/datadogagent/utils.go
- pkg/controller/utils/comparison/comparison.go
- pkg/controller/utils/condition/condition.go
- pkg/controller/utils/datadog/forwarders_manager.go
- pkg/controller/utils/datadog/metrics_forwarder.go
- pkg/controller/utils/shared_utils.go
- pkg/secrets/secrets.go
- version/version.go
* introduce new golangci configuration
* fix all golangci errors
> introduce golangci configuration

- .gitlab-ci.yml
- Makefile
fix tagging and release process
> fix release process tagging

- .github/CODEOWNERS
Documentation team does now exist and is the new sherif in Bad-grammar town !
> Change Baklava to documentation team

- pkg/controller/datadogagent/agent.go
Signed-off-by: cedric lamoriniere <cedric.lamoriniere@datadoghq.com>
> fix agent status update

- LICENSE
- NOTICE
Fix LICENSE file and introduce NOTICE file
Solve the comment: https://github.com/DataDog/datadog-operator/pull/49#discussion_r396636891
> Fix License file

- chart/datadog-operator/Chart.yaml
- chart/datadog-operator/values.yaml
- deploy/olm-catalog/datadog-operator/0.1.3/datadog-operator.v0.1.3.clusterserviceversion.yaml
- deploy/olm-catalog/datadog-operator/0.1.3/datadoghq.com_datadogagents_crd.yaml
- deploy/olm-catalog/datadog-operator/datadog-operator.package.yaml
- deploy/operator.yaml
- version/version.go
files update for release `v0.1.3`
> datadog-operator release v0.1.3

- Dockerfile
Update Dockerfile with the information require for Redhat certification.
doc: https://redhat-connect.gitbook.io/partner-guide-for-red-hat-openshift-and-container/
> Update Dockerfile for redhat scan

- pkg/apis/datadoghq/v1alpha1/const.go
- pkg/controller/datadogagent/clusteragent.go
We need permissions to query `/stats/summary` in the kubelet check
> Fix kubelet rbacs

- examples/datadog-agent-with-dca-clusterchecksrunner.yaml
follow-up on https://github.com/DataDog/datadog-operator/pull/64
> Fix clc runner field

- .github/workflows/main.yml
- test/e2e/datadogagent_test.go
Update kind version in github workflow.
> Update kind version in github workflow

- pkg/controller/datadogagent/secret.go
Fix the encoding of API key, APP key and DCA token in secret
> Fix the encoding of API key, APP key and DCA token in secret

- pkg/apis/datadoghq/v1alpha1/datadogagent_default.go
- pkg/controller/datadogagent/agent.go
- pkg/controller/datadogagent/clusteragent.go
- pkg/controller/datadogagent/clusteragent_test.go
Avoid hitting nil pointers
The operator shouldn't crash
> Fix panics

- .gitlab-ci.yml
add `push_tag_to_docker_hub` and `push_latest_to_docker_hub`
> [Gitlab] Add dockerhub jobs

- README.md
Update README to reflect Beta status of the project
Not really Alpha anymore.
> Update README to reflect Beta status of the project

- hack/release/README.md
Add more details to the release steps
> Update release steps

- Dockerfile
- chart/datadog-operator/Chart.yaml
- chart/datadog-operator/values.yaml
- deploy/olm-catalog/datadog-operator/0.2.1/datadog-operator.v0.2.1.clusterserviceversion.yaml
- deploy/olm-catalog/datadog-operator/0.2.1/datadoghq.com_datadogagents_crd.yaml
- deploy/olm-catalog/datadog-operator/datadog-operator.package.yaml
- deploy/operator.yaml
merge to master release v0.2.1 release commit
Always merge release on master
> merge to master release v0.2.1

- deploy/olm-catalog/csv-config.yaml
- deploy/olm-catalog/datadog-operator/0.2.0/datadog-operator.v0.2.0.clusterserviceversion.yaml
- deploy/olm-catalog/datadog-operator/0.2.1/datadog-operator.v0.2.1.clusterserviceversion.yaml
- hack/generate-olm-bundle.sh
the OLM bundle should contains all the CSV (ClusterServiceVersion) and not only the last release.
> Fix olm bundle release

- docs/getting_started.md
This Getting Started should point to the latest release, instead of a fixed old release.
> Point to the latest release

- README.md
Updates a leftover alpha release marker to beta in the README file
The motivation is to bring the documentation up to date with the release status
N/A
> Update alpha to beta in readme file

- chart/datadog-operator/templates/deployment.yaml
Remove the flag `--zap-stacktrace-level` 
`--zap-stacktrace-level` requires a new build
> Fix helm chart

- pkg/apis/datadoghq/v1alpha1/datadogagent_default.go
fix defaulting for the CRI socket option
> fix defaulting for the CRI socket option

- pkg/apis/datadoghq/v1alpha1/datadogagent_default.go
Fix dockerSocketPath defaulting
> Fix dockerSocketPath defaulting

- pkg/controller/datadogagent/clusterchecksrunner.go
Previously, if the ClusterChecksRunner deployment had already been
deleted (say, because the ClusterChecks have been disabled), the status
would not be updated, giving the impression that the ClusterChecksRunner
was still enabled, even though that was not the case.
To prevent that issue, now `cleanupClusterChecksRunner` always updates
the status, regardless of having to delete the deployment.
> Remove ClusterChecksRunner status when deployment is gone

- deploy/crds/datadoghq.com_datadogmetrics_crd.yaml
- pkg/apis/datadoghq/v1alpha1/datadogmetric_types.go
Following @CharlyF feedback on DDM usability, adding a field to display autoscaler references
> Add autoscaler references in DDM status to improve usability

- deploy/clusterrole.yaml
- deploy/olm-catalog/datadog-operator/0.2.2/datadog-operator.v0.2.2.clusterserviceversion.yaml
- deploy/olm-catalog/datadog-operator/0.2.2/datadoghq.com_datadogagents_crd.yaml
- deploy/olm-catalog/datadog-operator/datadog-operator.package.yaml
Currently generated manually from 0.2.1 as we have too many changes on master to generate directly using operator-sdk.
> Add version 0.2.2 OLM fixing deployment on OpenShift Dedicated

- .github/workflows/pr-linter.yml
Add new github worklow to validate metadata attach to each PR: labels, milestone
Improve the releasing by having enough information attached to each PR want we want to release a new version
> add github workflow for pr linter

- deploy/crds/v1/datadoghq.com_datadogagents_crd.yaml
- deploy/crds/v1beta1/datadoghq.com_datadogagents_crd.yaml
update `deploy/crds/v1/datadoghq.com_datadogagents_crd.yaml` and `deploy/crds/v1beta1/datadoghq.com_datadogagents_crd.yaml`
> Fix crds generation

- .github/workflows/pr-linter.yml
- controllers/datadogagent_controller_test.go
> Improve test stability

- api/v1alpha1/const.go
- controllers/datadogagent/agent_test.go
- controllers/datadogagent/clusterchecksrunner.go
- controllers/datadogagent/clusterchecksrunner_test.go
- controllers/datadogagent/utils.go
Update liveness and readiness probes to make them use the internal health check of the agent.
> Update liveness and readiness probes

- main.go
- pkg/secrets/secrets.go
Fix secret backend command CLI flag
> Fix secret backend command CLI flag

- controllers/datadogagent/clusterchecksrunner.go
The code introduced by #162 tried to apply a NetworkPolicy for the cluster checks runner that was meant for the cluster agent instead. This PR addresses that by applying the correct NetworkPolicy as used in the [helm chart](https://github.com/DataDog/helm-charts/blob/master/charts/datadog/templates/agent-clusterchecks-network-policy.yaml).
> Correctly apply Cluster Checks Runner NetworkPolicy

- Makefile
- docs/how-to-contribute.md
Adding helper output to the makefile.
Please Note: 
- that make now defaults to help and one can choose a command from there. 
- I just added some comments and sections because I don't know all of them. Feel free to add some additionally later. 
```
⛵ gke_datadog-sandbox_europe-west1-b_nam-test (datadog) in datadog-operator on  nnguyen/add-make-help via 🐹 v1.15.3 took 4s 
❯ make
Usage: make <OPTIONS> ... <TARGETS>
Available targets are:
Usage:
make <target>
Development
all                        Build test
build                      Builds manager + kubectl plugin
fmt                        Run go fmt against code
vet                        Run go vet against code
Deploy
manager                    Build manager binary
run                        Run against the configured Kubernetes …
```
> [makefile] add helper functions 

- Dockerfile
- Makefile
- api/v1alpha1/datadogmetric_types.go
- api/v1alpha1/zz_generated.openapi.go
- bundle-redhat/manifests/datadog-operator.clusterserviceversion.yaml
- bundle-redhat/manifests/datadoghq.com_datadogagents.yaml
- bundle-redhat/manifests/datadoghq.com_datadogmetrics.yaml
- bundle-redhat/metadata/annotations.yaml
- bundle-redhat/tests/scorecard/config.yaml
- bundle.Dockerfile
- bundle.redhat.Dockerfile
- bundle/manifests/datadog-operator.clusterserviceversion.yaml
- bundle/manifests/datadoghq.com_datadogmetrics.yaml
- bundle/metadata/annotations.yaml
- config/crd/bases/v1/datadoghq.com_datadogmetrics.yaml
- config/crd/bases/v1beta1/datadoghq.com_datadogmetrics.yaml
- config/default/kustomization.yaml
- config/manager/manager.yaml
- config/manifests/bases/datadog-operator.clusterserviceversion.yaml
- config/rbac/leader_election_role_binding.yaml
- config/rbac/role.yaml
- config/rbac/role_binding.yaml
- config/samples/datadogmetric-v1alpha1.yaml
- controllers/datadogagent_controller.go
- hack/redhat-bundle.sh
After Operator V1 migration, we need some re-adjustment to properly publish in upstream repositories.
> Fixes related to Operator releasing process (RH and OperatorHub)

- .gitlab-ci.yml
- Dockerfile
- Makefile
Add ARM64 images and publish using dedicated pipeline, automating pushing to all external registries.
Make sure images are published to all registries on tag. Make sure both ARM64 and AMD64 are pushed.
> Add ARM64 images and publish using dedicated pipeline

- .gitlab-ci.yml
Add a rolling update tag `master` corresponding to `master` branch on external repositories.
Check `master` tag exists on public repositories
> Add a master tag corresponding to master branch

- docs/installation.md
Update documentation with Operator Lifecycle Manager instruction.
Explain how to override the default Operator pod's resources
N/A
Install the operator with OLM, try to used the example `Subscription`. The Pod resources should be used.
> Add documentation about OLM installation

- .gitlab-ci.yml
> Fix automatic triggering of publishing jobs on tags

- pkg/config/config.go
Noticed a `DPANIC` due to the log key being missing
Show log lines properly
Make sure there is no longer a `DPANIC` log line during set up of the controllers
> add log keys

- README.md
> Update Releasing doc link in Readme.md

- .gitlab-ci.yml
Remove gitlab workaround needed with previous gitlab version
Simplify gitlab configuration
> Cleanup gitlab-ci config

- .gitlab-ci.yml
* Use ddbuild.io registry for gitlab runner image.
* Authenticate docker pull to build operator images
Fix docker pull rate-limit issue with golang base image
> Fix dockerhub pull image in gitlabci

- controllers/datadogagent/clusteragent.go
Address issues related to RBAC configuration associated with new features.
Make sure no `Failed to watch *v1.Namespace` or `Failed to watch *v1.ConfigMap` errors arise in the logs
> fix rbac for cluster agent

- docs/configuration.md
- hack/redhat-bundle.sh
* gcr.io is not trusted by the redhat operator bundle validation, so default images in example to dockerhub for now.
Fix operator bundle validation for the redhat marketplace.
> Fix redhat bundle validation

- controllers/datadogagent/clusteragent.go
Add cronjobs/jobs list/watch for the cluster-agent
Needed to enable jobs/cronjobs collection in the cluster agent
> add cronjobs/jobs list/watch for the cluster-agent

- docs/datadog_monitor.md
Add documentation for getting started with `DatadogMonitor` using the operator
Better user experience
N/A
> [datadogmonitor] add getting started doc

- examples/datadogmonitor/datadog-monitor-crashloopbackoff.yaml
- examples/datadogmonitor/datadog-monitor-deployment-replicas.yaml
- examples/datadogmonitor/datadog-monitor-imagepullbackoff.yaml
- examples/datadogmonitor/datadog-monitor-nodes-unavailable.yaml
- examples/datadogmonitor/datadog-monitor-pods-failed-state.yaml
- examples/datadogmonitor/datadog-monitor-statefulset-replicas.yaml
Update tags in examples to use standard tags
N/A
> fix example DatadogMonitor tags

- controllers/datadogmonitor/controller.go
Currently the DatadogMonitor is an infinite update loop due to the update of `Status.MonitorStateLastUpdateTime` timestamp, which triggers a change, which gets reconciled, triggering a timestamp change, etc...
Unfortunately `controller-runtime` does not support Watch with a resync per controller, so we do it manually.
Create some `DatadogMonitor` CR. Without any `.Spec` changes, these objects should be updated ~every minute, you can easily check this by running `kubectl get datadogmonitor -w`
> Avoid continuous requeuing of DatadogMonitors due to MonitorStateLastUpdateTime

- docs/installation.md
OLM doc update
fix broken link
> OLM doc update

- docs/datadog_monitor.md
Fix a very small YAML indentation issue
> Small indentation issue

- examples/datadogmonitor/datadog-monitor-deployment-replicas.yaml
Update metric typo in example `DatadogMonitor`
> [examples/datadogmonitor] fix metric typo in example monitor

- controllers/datadogagent/clusteragent.go
> [dca] support sts

- main.go
Allow custom values for leader election
No impact on Operator itself. You can verify that setting the leaseDuration actually changes the leader election lease by looking as logs (or APIServer audit logs)
> Add variable to set lease duration

- .github/workflows/release.yaml
Only run the CI release workflow on specific branches: `main` and `v*` such as `v0.6.x`
Do not create random release when adding a "custom" tag.
> Limit release of official branch

- api/v1alpha1/datadogagent_default.go
> Fix behaviour change with CLC defaulting

- controllers/datadogagent/clusteragent.go
- controllers/datadogagent/clusterchecksrunner.go
Just a minor cleanup opportunity that I saw while @vboulineau was explaining the code structure to me.
> [style] Simplify `needUpdate` assignments in controllers

- pkg/defaulting/images.go
Update latest agent image versions
> Update agent and cluster agent image tags to 7.31.1 and 1.15.1

- bundle-redhat/manifests/datadog-operator.clusterserviceversion.yaml
These image tags were missed in PR https://github.com/DataDog/datadog-operator/pull/376
> remove agent image tags in alm example of cluster service version (redhat)

- config/samples/datadog-operator-hub-example.yaml
This is used in the bundle script; removing so the image tag isn't hard-coded anymore.
> Remove image references in example file

- controllers/datadogagent/agent_test.go
- controllers/datadogagent/utils.go
See https://github.com/DataDog/helm-charts/pull/483
> [system-probe] fix chown capability

- docs/installation.md
> doc: how to configure API/APP key with OLM

- apis/datadoghq/v1alpha1/datadogagent_types.go
- apis/datadoghq/v1alpha1/zz_generated.openapi.go
- apis/datadoghq/v2alpha1/datadogagent_types.go
- apis/datadoghq/v2alpha1/zz_generated.openapi.go
- config/crd/bases/v1/datadoghq.com_datadogagents.yaml
> fix: DNSSelectorEndpoints definition

- controllers/datadogagent/orchestrator.go
- controllers/datadogagent/testdata/orchestrator_clusterrole.yaml
- controllers/datadogagent_controller.go
Add rbac for ingresses collection
new resource in the orchestrator check
Deploy DCA 1.19 with ingress collection enabled
> feat: (orch) support ingresses collection

- examples/datadogmonitor/audit-alert-monitor-test.yaml
- examples/datadogmonitor/event-alert-monitor-test.yaml
- examples/datadogmonitor/event-v2-alert-monitor-test.yaml
- examples/datadogmonitor/log-alert-monitor-test.yaml
- examples/datadogmonitor/process-alert-monitor-test.yaml
- examples/datadogmonitor/rum-alert-monitor-test.yaml
- examples/datadogmonitor/slo-alert-monitor-test.yaml
- examples/datadogmonitor/trace-analytics-alert-monitor-test.yaml
Note that Operator 0.8 is required for new monitor types
> add minimum version note to new datadogmonitor examples

- controllers/datadogagent/controller.go
> register missing features

- controllers/datadogagent/controller.go
- controllers/datadogagent/controller_reconcile_v2.go
- controllers/datadogagent/feature/cspm/feature.go
- controllers/datadogagent/feature/dummy/feature.go
- controllers/datadogagent/feature/enabledefault/feature.go
- controllers/datadogagent/feature/kubernetesstatecore/configmap_test.go
- controllers/datadogagent/feature/kubernetesstatecore/feature.go
- controllers/datadogagent/feature/logcollection/feature.go
- controllers/datadogagent/feature/npm/feature.go
- controllers/datadogagent/feature/oom_kill/feature.go
- controllers/datadogagent/feature/prometheus_scrape/feature.go
- controllers/datadogagent/feature/tcp_queue_length/feature.go
- controllers/datadogagent/feature/test/testsuite.go
- controllers/datadogagent/feature/types.go
- controllers/datadogagent/feature/usm/feature.go
- Add RequiredComponents access in ManageDependencies func
- remove enable field from feature when not needed
allow each feature to know which components are enabled.
> Feature factory interface changes

- apis/datadoghq/v1alpha1/secret.go
- controllers/datadogagent/feature/types.go
- controllers/datadogagent/merger/secret.go
- controllers/datadogagent/merger/secret_test.go
- controllers/datadogagent/secret_agent.go
- controllers/datadogagent/secret_clusteragent.go
- controllers/datadogagent/secret_common.go
- controllers/datadogagent/secret_test.go
- introduce SecretManager
- refactor v1alpha1 secret cred functions
Simplify `features` implementation.
> Introduce SecretManager

- controllers/datadogagent/systemprobe.go
Update the seccomp profile for system-probe.
Recent changes to fix issues with missing syscalls in the seccomp profile.
> Update system-probe secccomp profile

- Dockerfile
> Update base image to fix CVEs (#523)

- controllers/datadogagent/systemprobe.go
Cherry pick https://github.com/DataDog/datadog-operator/pull/501 onto v0.8 branch
> Update system-probe secccomp profile (#501)

- .gitlab-ci.yml
- Makefile
Fix CI as a follow up to #505 
> [ci] fix following bundle changes

- .gitlab-ci.yml
- Makefile
Fix CI failures for Redhat preflight jobs
> [ci] fixes to redhat preflight jobs

- apis/datadoghq/v1alpha1/datadogagent_conversion.go
Fixes a confusing error log message.
> [v1alpha1/conversion] Fix confusing log msg

- pkg/defaulting/images.go
Update default agent image tags to 7.37.1 and 1.21.0
> Update default agent image tags to 7.37.1 and 1.21.0

- pkg/defaulting/images.go
> update default agent image tags (#538)

- controllers/datadogagent/merger/rbac.go
Fixes a panic (writing to nil map) when starting the operator using v2 (`KUSTOMIZE_CONFIG=config/test-v2`).
> [merger/rbac] Initialize maps

- controllers/datadogagent/feature/enabledefault/feature.go
Refactor. Deletes the redundant "namespace" attr in the "default" feature.
The namespace is already accessible via the owner object.
Skip.
> [feature/default] Delete redundant "namespace" attr

- Makefile
- hack/install-operator-sdk.sh
- hack/install-yq.sh
This PR enables at least a basic development workflow for arm64 setups.
> arm64 setup

- apis/datadoghq/common/const.go
- apis/datadoghq/v1alpha1/const.go
- controllers/datadogagent/clusteragent.go
- controllers/datadogagent/component/clusterchecksrunner/default.go
- controllers/datadogagent/controller.go
- controllers/datadogagent/feature/clusterchecks/feature.go
- controllers/datadogagent/feature/clusterchecks/feature_test.go
- controllers/datadogagent/feature/enabledefault/feature.go
- controllers/datadogagent/feature/ids.go
- controllers/datadogagent/utils.go
- controllers/datadogagent_controller_v2_test.go
- controllers/testutils/agent.go
Implements the ClusterChecks feature.
Test that the feature works.
> [features] Add ClusterChecks feature

- controllers/datadogagent/controller_test.go
- controllers/datadogagent/poddisruptionbudget.go
cherry-picking from a contributor, gitlab pipeline did not run in the original pr https://github.com/DataDog/datadog-operator/pull/508
> Do not create a pdb if DCA has a single replica

- controllers/datadogagent_controller_v2_test.go
- controllers/testutils/agent.go
Adds an integration test for the orchestrator explorer feature.
Skip.
> [controller_v2_test] Test orchestrator explorer

- controllers/datadogagent_controller_v2_test.go
Refactor. Simplifies the integration tests for the reconciler V2. All the tests follow the same structure, so we can extract a common test function to avoid duplicating code.
Skip.
> [controller_v2_test] Extract common test func

- controllers/datadogagent/controller_reconcile_v2.go
- controllers/datadogagent/feature/clusterchecks/feature.go
- controllers/datadogagent/feature/cspm/feature.go
- controllers/datadogagent/feature/cws/feature.go
- controllers/datadogagent/feature/dogstatsd/feature.go
- controllers/datadogagent/feature/dummy/feature.go
- controllers/datadogagent/feature/enabledefault/feature.go
- controllers/datadogagent/feature/eventcollection/feature.go
- controllers/datadogagent/feature/factory.go
- controllers/datadogagent/feature/ids.go
- controllers/datadogagent/feature/kubernetesstatecore/feature.go
- controllers/datadogagent/feature/logcollection/feature.go
- controllers/datadogagent/feature/npm/feature.go
- controllers/datadogagent/feature/oomkill/feature.go
- controllers/datadogagent/feature/orchestratorexplorer/feature.go
- controllers/datadogagent/feature/prometheusscrape/feature.go
- controllers/datadogagent/feature/tcpqueuelength/feature.go
- controllers/datadogagent/feature/types.go
- controllers/datadogagent/feature/usm/feature.go
Adds the `ID` function to the `Feature` interface. This allows us to have more useful logs.
Before:
```
{"level":"INFO","ts":"2022-07-25T09:10:19Z","logger":"controllers.DatadogAgent","msg":"Dependency ManageDependencies","datadogagent":"system/datadog","featureID":0}
{"level":"INFO","ts":"2022-07-25T09:10:19Z","logger":"controllers.DatadogAgent","msg":"Dependency ManageDependencies","datadogagent":"system/datadog","featureID":1}
{"level":"INFO","ts":"2022-07-25T09:10:19Z","logger":"controllers.DatadogAgent","msg":"Dependency ManageDependencies","datadogagent":"system/datadog","featureID":2}
{"level":"INFO","ts":"2022-07-25T09:10:19Z","logger":"controllers.DatadogAgent","msg":"Dependency ManageDependencies","datadogagent":"system/datadog","featureID":3} …
```
> [features] Assign IDs to features for more useful logs

- apis/datadoghq/v2alpha1/utils.go
- apis/datadoghq/v2alpha1/utils_test.go
Support overriding service accounts in the DDA.
> Adding support to override service accounts for components

- controllers/datadogagent/feature/cws/const.go
This PR changes the name of the custom CWS policy file loaded by the operator. It needs to end with `.policy`.
> CWS: fix custom policy file name

- Makefile
Using kustomize v4 fixes the issue.
> Building on M1 will can't use kustomize3

- apis/datadoghq/v2alpha1/datadogagent_default_test.go
I merged https://github.com/DataDog/datadog-operator/pull/677 quickly after https://github.com/DataDog/datadog-operator/pull/676 and missed out that it should have been rebased.
Fix test.
> Fix incorrect variable used in test

- controllers/datadogagent/clusteragent.go
- controllers/datadogagent/feature/externalmetrics/feature.go
- controllers/datadogagent/feature/externalmetrics/rbac.go
- controllers/datadogagent/feature/orchestratorexplorer/rbac.go
- controllers/datadogagent_controller.go
We were creating (attempting to create) a Rolebinding to consume from the CM `extension-apiserver-authentication-reader`.
> Fix duplicate RBAC breaking External Metrics Provider

- Makefile
- apis/datadoghq/v2alpha1/datadogagent_types.go
- apis/datadoghq/v2alpha1/zz_generated.openapi.go
- config/crd/bases/v1/datadoghq.com_datadogagents.yaml
- config/crd/bases/v1beta1/datadoghq.com_datadogagents.yaml
Simple update to the comment in the type file.
> Fixing comment for HostPort being disabled

- controllers/datadogagent/feature/otlp/feature.go
- controllers/datadogagent/feature/otlp/feature_test.go
The corresponding hostPort is not opened so the agent can't receive payloads.
Fix OTLP.
> Adding hostport for OTLP

- controllers/datadogagent/agent_test.go
- controllers/datadogagent/component/agent/default.go
- controllers/datadogagent/utils.go
This PR ports the following fixes : 
https://github.com/DataDog/helm-charts/pull/868
https://github.com/DataDog/helm-charts/pull/871
It fixes system-probe access to auth_token
> [CWS] fix auth token access for system-probe

- controllers/datadogagent/agent_test.go
- controllers/datadogagent/utils.go
backport of https://github.com/DataDog/datadog-operator/pull/695
> [CWS] fix auth_token access for system-probe

- .github/workflows/build.yml
- .github/workflows/main.yml
- .github/workflows/release.yaml
- .goreleaser-for-darwin.yaml
- .goreleaser-for-linux.yaml
- .goreleaser-for-windows.yaml
- check-operator.Dockerfile
- go.mod
- hack/release/datadog-plugin-tmpl.yaml
- hack/release/generate-plugin-manifest.sh
This PR modify the kubectl plugin release process to:
* add ARM architecture support.
* CGO compilation
inspired by: https://github.com/DataDog/extendeddaemonset/pull/153
Support ARM user and more kubectl authentication mechanism.
> Add plugin ARM/CGO release tooling

- .github/workflows/pr-linter.yml
Dependabot uses the label `dependencies` when bumping library versions. Example PR: https://github.com/DataDog/datadog-operator/pull/713
> Add dependencies to valid labels

- controllers/datadogagent/override/global.go
Allow tags to go on DCA and CCR, not only the node agent.
> Add global tagging options to DCA and CCR

- controllers/datadogagent/clusteragent_test.go
- controllers/datadogagent/clusterchecksrunner_test.go
- controllers/datadogagent/component/new.go
Includes the app.kubernetes.io/component label to the resources yaml 
https://datadoghq.atlassian.net/browse/CONTECO-12
> adding app.kubernetes.io/component label

- .gitlab-ci.yml
cherry-pick #727 on v0.8 to fix CI
Allow us to release futur v0.8 version
> cherry-pick #727 on v0.8

- main.go
Increase default goroutines limit to 400, and make it configurable. Related Helm chart change https://github.com/DataDog/helm-charts/pull/978.
https://github.com/DataDog/datadog-operator/issues/666
Deploy locally built image using updated Helm chart on local Kind.
> Parametrize maximuGoroutines

- .github/workflows/release.yaml
Fix release process
a previous replace-all `eds->datadog` makes an unattended update in this file.
> Fix worflow release.yaml

- README.md
Adding `0.8.x -> 1.0.0` migration nuances to the readme.
https://github.com/DataDog/datadog-operator/issues/754
> Document 1.0.0 migration nuances

- cmd/check-operator/upgrade/upgrade.go
- cmd/kubectl-datadog/get/get.go
- pkg/plugin/common/statuswrapper.go
> Fix small typo

- examples/datadogagent/v2alpha1/datadog-agent-all.yaml
- examples/datadogagent/v2alpha1/datadog-agent-apm.yaml
Clean up on one of the examples and fix the `all-example`
> Fixing examples

- controllers/datadogagent/component/agent/default.go
> add statx to system-probe seccomp

- apis/datadoghq/v2alpha1/datadogagent_types.go
- config/crd/bases/v1/datadoghq.com_datadogagents.yaml
- config/crd/bases/v1beta1/datadoghq.com_datadogagents.yaml
- docs/configuration.v2alpha1.md
CI linter was failing with `Duplicate words (Security) found (dupword)`
> Fix duplicate sequential words for linter

- README.md
Matching public documentation in the readme:
https://docs.datadoghq.com/containers/datadog_operator/#why-use-the-datadog-operator-instead-of-a-helm-chart-or-daemonset
Updated README.md
Consistent message in the documentation matching the README.
> Update README.md to reflect Operator vs Helm changes

- .github/workflows/build.yml
Per this https://github.com/actions/runner-images/issues/7452#issuecomment-1512772272
> Attempt at fixing github workflow

- apis/datadoghq/v2alpha1/datadogagent_types.go
- apis/datadoghq/v2alpha1/zz_generated.openapi.go
We did not have the openapi generator on this struct, which would prevent the openapi validation from working correctly.
> Updating OpenAPI for seccompConfig

- bundle/manifests/datadog-operator.clusterserviceversion.yaml
- config/manager/manager.yaml
- hack/os-env.sh
- hack/patch-bundle.sh
This PR is against `v1.0`:
- Update bundle following fix from PR #806 (and cherry-picked onto the branch) 
- Remove extraneous label selector in clusterserviceversion
- Update os-env.sh hack for arm64
> [v1.0] fix CSV

- hack/os-env.sh
- hack/redhat-bundle.sh
Fix usage of `sed` for arm architectures. Added condition to define `SED` env var and updated usage in the redhat bundle script
> [tools] fix sed cmd for ARM and fix redhat bundle script

- apis/datadoghq/v2alpha1/datadogagent_types.go
- apis/datadoghq/v2alpha1/zz_generated.openapi.go
- config/crd/bases/v1/datadoghq.com_datadogagents.yaml
- config/crd/bases/v1beta1/datadoghq.com_datadogagents.yaml
Fixes error: `API rule violation: list_type_missing,./apis/datadoghq/v2alpha1,OrchestratorExplorerFeatureConfig,CustomResources`
> Add list type for custom resources

- bundle.Dockerfile
- bundle/manifests/datadog-operator-webhook-service_v1_service.yaml
- bundle/manifests/datadog-operator.clusterserviceversion.yaml
- bundle/manifests/datadoghq.com_datadogagents.yaml
- bundle/manifests/datadoghq.com_datadogmetrics.yaml
- bundle/manifests/datadoghq.com_datadogmonitors.yaml
- bundle/metadata/annotations.yaml
- config/manager/kustomization.yaml
- config/manager/manager.yaml
- config/manifests/bases/datadog-operator.clusterserviceversion.yaml
- hack/patch-bundle.sh
Update bundles to match latest 1.0.3 release
> Update bundles for latest release

- controllers/setup.go
- pkg/config/config.go
- pkg/controller/utils/datadog/metrics_forwarder.go
- pkg/datadogclient/client.go
> [v1.1][datadogmonitor] add support for site envvar

- controllers/datadogagent/feature/otlp/feature.go
Cherry-pick https://github.com/DataDog/datadog-operator/pull/828
> [v1.1] add grpc port and http port to service when otlp is enabled (#828)

- .golangci.toml
> [tooling] ci lint fix

- apis/datadoghq/common/const.go
- apis/datadoghq/v2alpha1/datadogagent_default.go
- controllers/datadogagent/agent_test.go
- controllers/datadogagent/component/agent/default.go
- controllers/datadogagent/feature/apm/feature.go
- controllers/datadogagent/feature/apm/feature_test.go
- controllers/datadogagent/feature/dogstatsd/feature.go
- controllers/datadogagent/feature/dogstatsd/feature_test.go
- controllers/datadogagent/merger/volume_mount.go
- controllers/datadogagent/utils_test.go
> [v1.1] update dsd and apm socket paths (#849)

- apis/datadoghq/common/envvar.go
- controllers/datadogagent/clusteragent.go
- controllers/datadogagent/clusteragent_test.go
- controllers/datadogagent/component/clusteragent/default.go
> [v1.1] Pass pod name to the cluster-agent

- controllers/datadogagent/feature/kubernetesstatecore/feature.go
Following PR #799, a minimum image condition was added for certain parameters. It was discovered that the defaulted image wasn't being respected.
This PR fixes it so that we now check if the overridden image version is too low, rather than checking if the set image version is high enough.
It also refactors a bit to ensure CCR images are checked first since that component will run the check if CCRs are enabled.
It also fixes an issue that was incorrectly checking the node agent image instead of the cluster agent image when the check runs on the cluster agent.
Test 
1. the output of `agent status` on the component running the check, to make sure the `kubernetes_state_core` check is running properly …
> [ksmfeature] fix recognition of default image

- controllers/datadogagent/component/clusterchecksrunner/default.go
- controllers/datadogagent/feature/enabledefault/feature.go
An issue was reported where the ClusterRole for the Cluster Checks Runner wasn't being created. This fixes it by creating the ClusterRole and ClusterRoleBinding by default if the CCRs are enabled.
Bugfix
- Deploy the operator
- Enable CCR in the DatadogAgent
```
features:
clusterChecks:
enabled: true
useClusterChecksRunners: true
```
- use `kubectl get clusterrole` and `kubectl get clusterrolebinding` to make sure the respective resources, both called `datadog-cluster-checks-runner`, are created
> add default clusterrole creation for cluster checks runner

- controllers/datadogagent/component/clusterchecksrunner/default.go
- controllers/datadogagent/feature/enabledefault/feature.go
> [v1.1] add default clusterrole creation for cluster checks runner

- apis/datadoghq/common/const.go
- controllers/datadogagent/component/utils.go
- controllers/datadogagent/feature/apm/feature.go
- controllers/datadogagent/feature/dogstatsd/feature.go
- controllers/datadogagent/feature/dogstatsd/feature_test.go
Cherry-pick https://github.com/DataDog/datadog-operator/pull/841
> Fix agent local service creation for dogstatsd and apm (#841)

- controllers/datadogagent/feature/apm/feature.go
- controllers/datadogagent/feature/otlp/feature.go
Set the agent's internal traffic policy to `Local` for features using the service
> Set local internal traffic policy for relevant features

- controllers/datadogagent/feature/kubernetesstatecore/feature.go
> [v1.1][ksmfeature] fix bug where service account was being overwritten

- pkg/utils/version.go
- pkg/utils/version_test.go
> [v1.1] format agent version check

- controllers/datadogagent/component/clusterchecksrunner/default.go
> [v1.1] add additional permissions to ccr clusterrole (#868)

- .github/PULL_REQUEST_TEMPLATE.md
- .github/workflows/pr-linter.yml
* Add a checklist to the PR template
* Add a section about minimum required agent/dca versions to PR template
* Add a workflow to check for milestone
> Update pr template and add check for milestone

- LICENSE-3rdparty.csv
- controllers/datadogmonitor/controller.go
- controllers/datadogmonitor/controller_test.go
- controllers/datadogmonitor/monitor.go
- controllers/datadogmonitor/monitor_test.go
- controllers/datadogmonitor_controller.go
- controllers/setup.go
- go.mod
- go.sum
- pkg/datadogclient/client.go
Update Datadog API Go client and make necessary changes in the DatadogMonitor controller.
Get latest functionality from the client.
This change should be noop.
N/A
> [datadogmonitor] update dd api client

- bundle/manifests/datadog-operator.clusterserviceversion.yaml
- config/samples/datadog-operator-hub-example.yaml
Update community operator-hub bundle DatadogAgent example to use v2alpha1. 
> Update operator-hub bundle examples

- .gitlab-ci.yml
Fix image name used in internal push jobs
> [gitlab] fix image name

- pkg/defaulting/images.go
> default agent/dca to 7.47.0

- config/default/kustomization.yaml
Make testing easier by commenting out unneeded configs for kustomize
> [kustomize] comment out webhook and certmanager config

- docs/how-to-contribute.md
> Update contribution guide

- docs/getting_started.md
Added a small stub section with a link from getting_started.md to integrations_autodiscovery.md, 
I found it difficult to find reference on how to configure agent integrations with the Operator
> Mirza.nurkic/add link to integrations

- docs/custom-operator-image.md
- docs/installation.md
Add instruction to create a custom container image with a CA certificat
document user support case request
> Add(doc): custom operator image

- main.go
> fix spaces after periods and small wording tweak (#925)

- pkg/defaulting/images.go
> [defaulting/images] Update agents to 7.47.1 (#930)

- apis/datadoghq/v2alpha1/test/builder.go
- controllers/datadogagent/feature/dogstatsd/feature_test.go
- controllers/datadogagent/feature/dogstatsd/feature_v1alpha1_test.go
- controllers/datadogagent/feature/eventcollection/feature_test.go
- controllers/datadogagent/feature/eventcollection/feature_v1alpha1_test.go
- controllers/datadogagent/feature/liveprocess/feature_test.go
- controllers/datadogagent/feature/liveprocess/feature_v1alpha1_test.go
- controllers/datadogagent/feature/logcollection/feature_test.go
- controllers/datadogagent/feature/logcollection/feature_v1alpha1_test.go
- controllers/datadogagent/feature/orchestratorexplorer/feature_test.go
- controllers/datadogagent/feature/orchestratorexplorer/feature_v1alpha1_test.go
- controllers/datadogagent/feature/prometheusscrape/feature_test.go
- controllers/datadogagent/feature/prometheusscrape/feature_v1alpha1_test.go
- controllers/datadogagent/feature/remoteconfig/feature_test.go
Rewriting several existing `feature_test.go` files to make them like rest of table tests. Also broke out `v1alpha1` tests, they'll be deleted soon.
Variables aren't scoped to test making it hard to read, this makes changes difficult to make.
> Refactor feature tests

- bundle/manifests/datadog-operator.clusterserviceversion.yaml
- bundle/manifests/datadoghq.com_datadogagents.yaml
- bundle/manifests/datadoghq.com_datadogmonitors.yaml
- config/manager/kustomization.yaml
Update bundles to match latest 1.2.0 release
* Agent: n/a
> Update bundles to match 1.2.0 release

- docs/getting_started.md
- docs/how-to-contribute.md
- docs/installation.md
Update How to contribute, Getting Started and Installation docs
Better clarity
> [docs] update a few docs

- bundle/manifests/datadog-operator.clusterserviceversion.yaml
- config/manager/kustomization.yaml
> Update bundles to match v1.2.1 release

- apis/datadoghq/v1alpha1/zz_generated.openapi.go
- config/crd/bases/v1/datadoghq.com_datadogslos.yaml
- config/crd/bases/v1beta1/datadoghq.com_datadogslos.yaml
Fix generated files following merge of #807 
> [slo] fix generated files

- config/samples/datadoghq_v1alpha1_datadogagentprofile.yaml
Add a sample manifest for DatadogAgentProfiles
* Agent: n/a
> DatadogAgentProfile sample manifest

- hack/patch-bundle.sh
> [cherry-pick] update patch-bundle script to include spec.replaces field in bundle (#990)

- .github/dependabot.yaml
Add dependabot configuration file to support version updates
Less tech debt/easier maintenance
> add dependabot.yaml file

- .github/dependabot.yaml
Add dependabot configuration file to support version updates
Less tech debt/easier maintenance
> add dependabot.yaml file (#989)

- bundle/manifests/datadog-operator.clusterserviceversion.yaml
- bundle/manifests/datadoghq.com_datadogagents.yaml
- bundle/manifests/datadoghq.com_datadogslos.yaml
- config/manager/kustomization.yaml
Update bundle files in `main` to match recent release version.
> Update bundles to match 1.3.0 release

- apis/datadoghq/v2alpha1/datadogagent_types.go
- apis/datadoghq/v2alpha1/zz_generated.deepcopy.go
- apis/datadoghq/v2alpha1/zz_generated.openapi.go
- config/crd/bases/v1/datadoghq.com_datadogagents.yaml
- config/crd/bases/v1beta1/datadoghq.com_datadogagents.yaml
- controllers/datadogagent/component/agent/default.go
- controllers/datadogagent/component/agent/new.go
- controllers/datadogagent/component/new.go
- controllers/datadogagent/component/utils.go
- controllers/datadogagent/controller.go
- controllers/datadogagent/controller_reconcile_agent.go
- controllers/datadogagent/controller_reconcile_agent_test.go
- controllers/datadogagent/controller_reconcile_v2.go
- controllers/datadogagent/controller_reconcile_v2_common.go
- controllers/datadogagent_controller_v2_test.go
- controllers/setup.go
- main.go
- pkg/controller/utils/datadog/metrics_forwarder.go
- pkg/kubernetes/provider.go
- pkg/kubernetes/provider_test.go
- pkg/plugin/common/statuswrapper.go
* Add flag
* Fix types to match existing types fields for smoother migration
* Fix override name behavior
* Agent: n/a
> [introspection] Add flag, fix types, override name

- apis/datadoghq/common/v1/types.go
- apis/datadoghq/v2alpha1/datadogagent_types.go
- apis/datadoghq/v2alpha1/zz_generated.openapi.go
- config/crd/bases/v1/datadoghq.com_datadogagents.yaml
- config/crd/bases/v1beta1/datadoghq.com_datadogagents.yaml
- docs/configuration.v2alpha1.md
"Non-privileged" was changed to "unprivileged" during development, but found a couple places that were missed
Noticed while QAing, because the container log states the container name
> update non-privileged to unprivileged

- apis/datadoghq/common/v1/types.go
- apis/datadoghq/v2alpha1/datadogagent_types.go
- apis/datadoghq/v2alpha1/zz_generated.openapi.go
- config/crd/bases/v1/datadoghq.com_datadogagents.yaml
- config/crd/bases/v1beta1/datadoghq.com_datadogagents.yaml
- docs/configuration.v2alpha1.md
> [cherry-pick] update non-privileged to unprivileged (#1040)

- controllers/datadogagent_controller.go
Fixes the `builder.Watches` call for Profiles.
> [profiles] Fix Watches call for Profiles

- .gitlab-ci.yml
Automatically run nightly image push job on `main` branch
> [gitlab] auto push nightly image

- apis/datadoghq/common/const.go
- controllers/datadogagent/feature/sbom/feature.go
- controllers/datadogagent/feature/sbom/feature_test.go
> [backport] Mount host files for proper os detection in SBOMs

- .gitlab-ci.yml
- Makefile
Migrate Gitlab runners according to new processes
> [gitlab] update runners for build jobs

- Makefile
Noticed an issue after merging #1056 
> [gitlab] add missing parameter in gitlab jobs

- pkg/defaulting/images.go
Cherry pick https://github.com/datadog/datadog-operator/pull/1038
> [cherry-pick][defaulting/images] Update agents to 7.50.3 (#1038)

- apis/datadoghq/v2alpha1/test/builder.go
- controllers/datadogagent/feature/apm/feature.go
- controllers/datadogagent/feature/apm/feature_test.go
- controllers/datadogagent/feature/dogstatsd/feature.go
- controllers/datadogagent/feature/dogstatsd/feature_test.go
- controllers/datadogagent/feature/dogstatsd/feature_v1alpha1_test.go
> [cherry-pick] Fix hostport custom port settings (#1067)

- .gitlab-ci.yml
- Makefile
- hack/publish-community-bundles.sh
> Add gitlab post-release job to create community operator PRs (#1036)

- pkg/defaulting/images.go
[defaulting/images] Update agents to 7.51.0
> [defaulting/images] Update agents to 7.51.0

- bundle/manifests/datadoghq.com_datadogagents.yaml
- hack/patch-bundle.sh
- hack/redhat-bundle.sh
> update bundle script and base bundle (#1094)

- hack/publish-community-bundles.sh
Following merge of https://github.com/DataDog/datadog-operator/pull/1094 , this script needs to be updated to use the bundles correctly
> fix publish-community-bundles script

- hack/publish-community-bundles.sh
> fix publish-community-bundles script (#1096)

- docs/introspection.md
Add public docs about introspection
* Agent: n/a
> [CECO-941][docs] Add introspection docs

- .gitlab-ci.yml
- Makefile
Missed a small update in https://github.com/DataDog/datadog-operator/pull/1104
> [gitlab] fix make task

- config/default/kustomization.yaml
> [tooling] another small fix for bundle (#1112)

- controllers/datadogagent/feature/helmcheck/feature.go
- controllers/datadogagent/feature/helmcheck/feature_test.go
> Add md5 hash config annotation to helm check (#1111)

- docs/datadog_agent_profiles.md
Adds initial documentation for DAPs
CECO-729
> [docs][CECO-729] Add DAP docs

- pkg/defaulting/images.go
> Update agents to 7.52.1

- config/samples/datadoghq_v1alpha1_datadogslo.yaml
- config/samples/kustomization.yaml
Add datadogslo sample
Release preparation
> Add datadogslo sample

- controllers/datadogagent/controller_reconcile_agent.go
- controllers/datadogagent/controller_reconcile_agent_test.go
- controllers/datadogagent/controller_reconcile_v2.go
> Combine DS cleanup methods (#1100)

- controllers/datadogagent/orchestrator.go
- controllers/datadogagent/testdata/orchestrator_clusterrole.yaml
- controllers/datadogagent_controller.go
Update RBACs for storageclass and limitrange collection in the orchestrator check.
> [orchestrator check] Update RBACs for storageclass and limitrange collection

- pkg/defaulting/images.go
> Update agent image versions to 7.53

- controllers/datadogagent/orchestrator.go
- controllers/datadogagent/testdata/orchestrator_clusterrole.yaml
- controllers/datadogagent_controller.go
> Update RBACs for storageclass and limitrange collection (#1159)

- pkg/defaulting/images.go
> Bump agent image versions to 7.53 (#1160)

- controllers/datadogagent/feature/orchestratorexplorer/rbac.go
> add limitranges and storageclasses rbacs to orch explorer feature

- controllers/datadogagent/feature/orchestratorexplorer/rbac.go
> add limitranges and storageclasses rbacs to orch explorer feature (#1166)

- Makefile
> [cherry-pick] Disable provenance gitlab (#1133)

- Makefile
> Bump openshift-preflight version to 1.9.4

- Makefile
(cherry picked from commit 4838b3cae44ea0329ba036b9f25a8fe4a6cf7f2e)
> bump openshift-preflight version to 1.9.4 (#1183)

- pkg/plugin/common/const.go
- pkg/plugin/common/utils.go
- pkg/plugin/common/utils_test.go
> [plugin] VULN-6817 escape dots in regex

- Makefile
For generated code, use `./apis` instead of all directories
Make sure generated code succeeds (and no expected file diffs are missing)
> [tooling] specify ./apis for generated code

- Makefile
> [tooling] specify ./apis for generated code (#1211)

- config/rbac/role.yaml
> [v1.7] update operator manager rbac (#1217)

- .github/workflows/build.yml
- .github/workflows/release.yaml
> [tooling] update goreleaser skip flag (#1219)

- apis/datadoghq/v2alpha1/datadogagent_types.go
Change spacing in types file of new structs to be consistent with existing ones
> fix spacing in types file

- bundle/manifests/datadog-operator.clusterserviceversion.yaml
- bundle/manifests/datadoghq.com_datadogagents.yaml
- bundle/manifests/datadoghq.com_datadogmonitors.yaml
Update bundle on `main` branch from the latest release
> update bundle from operator 1.7.0

- Makefile
> Bump kustomize version

- apis/datadoghq/v2alpha1/datadogagent_default_test.go
> fix default agent test

- config/manager/kustomization.yaml
Missed this update following the release of 1.7.0
> fix kustomize manager tag

- service.datadog.yaml
> use service catalog schema version v2

- service.datadog.yaml
> [service catalog] update fields for v2 schema

- main.go
Add more profiler types to profiling
> Add more profiler types

- .gitlab-ci.yml
- service.datadog.yaml
Update Gitlab jobs to trigger operator nightly workflow publication
Update conductor configuration to trigger deployment upon successful publication
> [gitlab] update nightly operator deployment job

- .gitlab-ci.yml
Temporarily output env to a gitlab job
Conductor testing
> [temp] output env in gitlab job

- .gitlab-ci.yml
Fix envvar missed in https://github.com/DataDog/datadog-operator/pull/1321
> [gitlab] fix incorrect var

- main.go
> Add more profiler types (#1310)

- Dockerfile
- check-operator.Dockerfile
- go.mod
> Bump Go version in go.mod and Dockerfiles to 1.22.4 (#1349)

- docs/datadog_agent_profiles.md
List settings that were added in operator 1.8.0
> [docs] Update dap docs for 1.8.0 release

- repository.datadog.yml
Add more merge queue configuration to make it works
Currently it is not possible to use "merge queue" on this project
> Update mergequeue configuration

- Makefile
* Remove v in image tag
* Review suggestions
Cherry pick #1403 
> Remove "v" in image tag (#1403)

- api/datadoghq/v1alpha1/datadogagentprofile_types.go
- config/crd/bases/v1/datadoghq.com_datadogagentprofiles.yaml
* Clarify update strategy description
* Fix autogenerated files
Cherry pick #1413 
> [profiles] Update UpdateStrategy description (#1413)

- docs/datadog_agent_profiles.md
Document new override feature available in operator v1.9
> [profiles] Update DatadogAgentProfile docs for 1.9.0

- api/datadoghq/v1alpha1/datadogagentprofile_types.go
- api/datadoghq/v1alpha1/zz_generated.openapi.go
- config/crd/bases/v1/datadoghq.com_datadogagentprofiles.yaml
> Remove capitalization for profile field (#1423)

- internal/controller/datadogagent/controller_reconcile_v2.go
> Don't update status for default profile (#1434)

- bundle/manifests/datadog-operator.clusterserviceversion.yaml
- bundle/manifests/datadoghq.com_datadogagentprofiles.yaml
- config/manager/kustomization.yaml
> release v1.9.0-rc.3

- docs/datadog_dashboard.md
- docs/datadog_monitor.md
Add documentation for DatadogDashboard.
> [docs] add doc for datadogdashboard

- service.datadog.yaml
Update workflow name following change in internal chart
> [conductor] update workflow name

- bundle/manifests/datadog-operator.clusterserviceversion.yaml
- config/manager/kustomization.yaml
> release v1.9.0

- .gitlab-ci.yml
Missed one place that required the workflow name update following https://github.com/DataDog/datadog-operator/pull/1453
> [gitlab] fix workflow name

- config/manager/kustomization.yaml
Set the correct image name and tag.
> fix(kustomize): set correct image name and tag

- pkg/defaulting/images.go
> Update agent / cluster-agent to 7.58.0 (#1476)

- bundle/manifests/datadog-operator.clusterserviceversion.yaml
- config/manager/kustomization.yaml
> release v1.10.0-rc.2

- .gitlab-ci.yml
Incorporate gitlab resource fixes from #1445  onto v1.10 to fix CI jobs
> [v1.10] set resource settings for build and unit_tests in gitlab

- Makefile
Update openshift preflight version
> Update openshift preflight version

- .github/workflows/release.yaml
Pin goreleaser to v2.4.1 in the release workflow. 
Fix CI for release
> pin goreleaser v2.4.1 for release workflow

- Makefile
> Update openshift preflight version (#1460)

- .github/workflows/release.yaml
> pin goreleaser v2.4.1 for release workflow (#1506)

- pkg/remoteconfig/orchestrator_k8s_crd.go
> [Orch] Set CRDs in cases of revoking config

- pkg/remoteconfig/orchestrator_k8s_crd.go
> [Orch] Set CRDs in cases of revoking config (#1505)

- bundle/manifests/datadog-operator.clusterserviceversion.yaml
- config/manager/kustomization.yaml
> release v1.10.0-rc.4

- bundle/manifests/datadog-operator.clusterserviceversion.yaml
- config/manager/kustomization.yaml
> release v1.10.0

- .github/workflows/build.yml
- .github/workflows/codeql-analysis.yml
- .github/workflows/main.yml
- .github/workflows/pr-linter.yml
- .github/workflows/release.yaml
> Configure Github workflow and job level permissions

- docs/how-to-contribute.md
> small doc fix

- bundle/manifests/datadog-operator.clusterserviceversion.yaml
- bundle/manifests/datadoghq.com_datadogagents.yaml
- config/manager/kustomization.yaml
> Update bundle and manager config from v1.10

- .github/workflows/pr-linter.yml
Updates the linter so it doesn't post reviews (requiring write permissions) and only fails workflow. 
> Fix pr-linter workflow

- hack/publish-community-bundles.sh
> fix bundle name for rh-certified PRs (#1527)

- docs/secret_management.md
> [documentation] Secrets management in Operator 1.11+ (#1555)

- bundle-community-operators/manifests/datadog-operator.clusterserviceversion.yaml
- bundle/manifests/datadog-operator.clusterserviceversion.yaml
- config/manager/kustomization.yaml
> release v1.11.0-rc.3

- bundle-community-operators/manifests/datadog-operator.clusterserviceversion.yaml
- bundle/manifests/datadog-operator.clusterserviceversion.yaml
- config/manager/kustomization.yaml
> release v1.11.0

- bundle-community-operators/manifests/datadog-operator.clusterserviceversion.yaml
- bundle/manifests/datadog-operator.clusterserviceversion.yaml
- config/manager/kustomization.yaml
> release v1.11.1-rc.1

- bundle-community-operators/manifests/datadog-operator.clusterserviceversion.yaml
- bundle/manifests/datadog-operator.clusterserviceversion.yaml
- config/manager/kustomization.yaml
> [chore] Release v1.11.1

- bundle/manifests/datadog-operator.clusterserviceversion.yaml
- bundle/manifests/datadoghq.com_datadogagentprofiles.yaml
- bundle/manifests/datadoghq.com_datadogagents.yaml
- bundle/manifests/datadoghq.com_datadogdashboards.yaml
- bundle/manifests/datadoghq.com_datadogmetrics.yaml
- bundle/manifests/datadoghq.com_datadogmonitors.yaml
- bundle/manifests/datadoghq.com_datadogpodautoscalers.yaml
- bundle/manifests/datadoghq.com_datadogslos.yaml
- config/manager/kustomization.yaml
Merges v1.11 branch bundle and kustomization into `main`
1.11.1 bundles have been released everywhere, so updating `main` as last release task
> Update bundle and manager config from v1.11

- config/rbac/role.yaml
- internal/controller/datadogagent_controller.go
Small adjustments to clusterrole to better align with internal configuration
> make small adjustments to clusterrole

- bundle-community-operators/manifests/datadog-operator.clusterserviceversion.yaml
- bundle/manifests/datadog-operator.clusterserviceversion.yaml
- config/manager/kustomization.yaml
release v1.12.0-rc.3
operator release process
> release v1.12.0-rc.3

- .github/workflows/release.yaml
> Upgrade github artifact upload/download actions (#1656)

- bundle-community-operators/manifests/datadog-operator.clusterserviceversion.yaml
- bundle/manifests/datadog-operator.clusterserviceversion.yaml
- config/manager/kustomization.yaml
> release v1.12.0

- Dockerfile
- Makefile
> Redhat preflight fixes for operator release (#1661)

- pkg/defaulting/images.go
> update latest agent and cluster agent version to 7.62.2 (#1676)

- .gitlab-ci.yml
Update environments var for release candidate deployments
Downstream updates to the release candidate workflow
> [gitlab] update release candidate deployment environments

- bundle-community-operators/manifests/datadog-operator.clusterserviceversion.yaml
- bundle/manifests/datadog-operator.clusterserviceversion.yaml
- config/manager/kustomization.yaml
> release v1.12.1-rc.1

- .gitlab-ci.yml
> [gitlab] update rc deployment environments (#1679)

- bundle-community-operators/manifests/datadog-operator.clusterserviceversion.yaml
- bundle/manifests/datadog-operator.clusterserviceversion.yaml
- config/manager/kustomization.yaml
> release v1.12.1

- docs/datadog_generic_resource_dev.md
- examples/datadoggenericresource/monitor-sample.yaml
* Updates the monitor example to fix the jsonSpec (closing brace) + use fake monitors ID
* Updates the generic resource dev doc after the decision on refactor
> (documentation) Update DatadogGenericResource contribute documentation

- bundle/manifests/datadog-operator.clusterserviceversion.yaml
- bundle/manifests/datadoghq.com_datadogagentprofiles.yaml
- bundle/manifests/datadoghq.com_datadogagents.yaml
- bundle/manifests/datadoghq.com_datadoggenericresources.yaml
- bundle/manifests/datadoghq.com_datadogpodautoscalers.yaml
- config/manager/kustomization.yaml
Merges v1.12 branch bundle and kustomization into main
> Update bundle and manager config from v1.12

- internal/controller/datadogagent/component/agent/default.go
- pkg/defaulting/images.go
> Update OTel agent image (#1728)

- .gitlab-ci.yml
- Dockerfile
- Makefile
- internal/controller/fipsonly.go
> Generate fips image compiled with Go boringcrypto (#1731)

- bundle-community-operators/manifests/datadog-operator.clusterserviceversion.yaml
- bundle-community-operators/manifests/datadoghq.com_datadogagents.yaml
- bundle/manifests/datadog-operator.clusterserviceversion.yaml
- bundle/manifests/datadoghq.com_datadogagents.yaml
- config/manager/kustomization.yaml
> release v1.13.0-rc.2

- .gitlab-ci.yml
> Update check_preflight_redhat_image image tag (#1740)

- pkg/defaulting/images.go
Cherry-pick https://github.com/DataDog/datadog-operator/pull/1744 
Original PR motivation
> Cherry-pick: bump 7.63.2 (#1744)

- .gitlab-ci.yml
> Pass fips image tag to internal fips template

- .gitlab-ci.yml
> Pass fips image tag to internal fips template (#1748)

- docs/datadog_slo.md
Add docs page for SLO controller
We neglected to take care of this when the controller was created
> add doc page for slos

- pkg/defaulting/images.go
> Agent/DCA bump 7.63.3 (#1760)

- internal/controller/datadogagent/controller_reconcile_v2.go
> small fix for error handling

- .gitlab-ci.yml
> Fix internal fips image tag

- .gitlab-ci.yml
> Fix internal fips image tag (#1770)

- internal/controller/datadogagent/controller_reconcile_v2_common.go
- internal/controller/datadogagent/controller_reconcile_v2_common_test.go
> Gate profile canary waits behind annotation (#1758)

- bundle-community-operators/manifests/datadog-operator.clusterserviceversion.yaml
- bundle/manifests/datadog-operator.clusterserviceversion.yaml
- config/manager/kustomization.yaml
> release v1.13.0-rc.3

- bundle-community-operators/manifests/datadog-operator.clusterserviceversion.yaml
- bundle/manifests/datadog-operator.clusterserviceversion.yaml
- config/manager/kustomization.yaml
> release v1.13.0-rc.4

- .github/workflows/main.yml
- Makefile
- docs/how-to-contribute.md
- internal/controller/datadogagent_controller_profiles_test.go
- internal/controller/datadogagent_controller_test.go
- internal/controller/suite_v2_test.go
I've recreated https://github.com/DataDog/datadog-operator/pull/1673 in upstream.
See https://github.com/DataDog/datadog-operator/pull/1673.
N/A
N/A
N/A
> Clean up integration tests

- bundle-community-operators/manifests/datadog-operator.clusterserviceversion.yaml
- bundle/manifests/datadog-operator.clusterserviceversion.yaml
- config/manager/kustomization.yaml
Release Datadog Operator 1.13.0
> release v1.13.0

- docs/data_collected.md
- docs/installation.md
Just fixes some links. Makes one absolute, removes another that is a 404.
> fixing links in docs

- examples/datadogagent/datadog-agent-with-extra-confd.yaml
> [documentation] add example for configuring extra confd

- api/datadoghq/v1alpha2/datadogpodautoscaler_types.go
- config/crd/bases/v1/datadoghq.com_datadogpodautoscalers.yaml
- config/crd/bases/v1/datadoghq.com_datadogpodautoscalers_v1alpha2.json
We want to make the `objectives` mandatory now with a least 1 target.
No testing required.
> [autoscaling] Make objectives required CRD v1alpha2

- .github/workflows/backport-pr.yml
test to check Backport PR GHA workflow changes
> [testing backport] noop change 

- .github/workflows/backport-pr.yml
> testing backport gha (noop)

- .github/workflows/backport-pr.yml
> more backport testing

- pkg/defaulting/images.go
> Bump Agent to 7.64.1

- internal/controller/datadogagent/feature/orchestratorexplorer/rbac.go
Orchestrator needs it since 7.64.1
> Add permission for PDB

- internal/controller/datadogagent/feature/orchestratorexplorer/rbac.go
> Add permission for PDB (#1841)

- pkg/defaulting/images.go
> Bump Agent to 7.64.3

- bundle-community-operators/manifests/datadog-operator.clusterserviceversion.yaml
- bundle/manifests/datadog-operator.clusterserviceversion.yaml
- config/manager/kustomization.yaml
> Release v1.14.0-rc.2

- api/datadoghq/common/datadogpodautoscaler_types.go
Add `External` as a valid type for autoscaler source.
Adding support for external recommendations 
This will be tested as part of validation of external recommender support
> [autoscaling] Add external recommendation source

- bundle-community-operators/manifests/datadog-operator.clusterserviceversion.yaml
- bundle/manifests/datadog-operator.clusterserviceversion.yaml
- config/manager/kustomization.yaml
> release v1.14.0

- .gitignore
Add `.cursor/*` to gitignore
Ignoring local cursor settings, like rules
> (chore) Add cursor to gitignore, e.g. for rules

- pkg/defaulting/images.go
Update agent images to `7.65.0`
> Update agent image to 7.65.0

- api/datadoghq/v1alpha2/datadogpodautoscaler_conversion.go
- api/datadoghq/v1alpha2/datadogpodautoscaler_conversion_test.go
Fix the conversion of Autoscaling mode. Code is not actually used in the operator.
No test required.
> Fix Autoscaling ApplyMode conversion

- pkg/images/images.go
Update agent images to `7.65.2`
> Update agent images to 7.65.2

- bundle-community-operators/manifests/datadog-operator.clusterserviceversion.yaml
- bundle-community-operators/manifests/datadoghq.com_datadogagents.yaml
- bundle/manifests/datadog-operator.clusterserviceversion.yaml
- bundle/manifests/datadoghq.com_datadogagents.yaml
- config/manager/kustomization.yaml
> release v1.15.0-rc.2

- go.work.sum
- test/e2e/go.mod
Bump golang.org/x/net to v0.40.0 to address VULN-10394
CVE
> Bump golang.org/x/net to v0.40.0

- bundle-community-operators/manifests/datadog-operator.clusterserviceversion.yaml
- bundle/manifests/datadog-operator.clusterserviceversion.yaml
- config/manager/kustomization.yaml
> release v1.15.1-rc.1

- bundle-community-operators/manifests/datadog-operator.clusterserviceversion.yaml
- bundle/manifests/datadog-operator.clusterserviceversion.yaml
- config/manager/kustomization.yaml
> release v1.15.1

- repository.datadog.yml
https://github.com/DataDog/datadog-operator/pull/1978
Bypass mergegate for unsigned GH bot commits
> Cherry-pick 1978

- pkg/images/images.go
> Update default Agent to 7.67.0

- bundle-community-operators/manifests/datadog-operator.clusterserviceversion.yaml
- bundle/manifests/datadog-operator.clusterserviceversion.yaml
- config/manager/kustomization.yaml
> Release v1.16.0-rc.2

- docs/datadog_agent_profiles.md
* Specifies the DAP profile CRD should be installed to use DAP
* User internal feedback
> [Documentation] Clarify how to onboard to DAP using Helm chart

- internal/controller/datadogagentinternal/controller_reconcile_v2.go
Keep dependency labels consistent by using a copy of the DDAI with the DDA's name as the owner in the store
Prevent invalid labels too long errors
> Pass DDAI with DDA name to store

- internal/controller/datadogagent/controller.go
- internal/controller/datadogagent/controller_reconcile_v2.go
- internal/controller/datadogagent/merge.go
- internal/controller/datadogagent/merge_test.go
- internal/controller/datadogagent/profile.go
- internal/controller/datadogagent/profile_test.go
Fieldmanager only needs to be set up once (I think)
https://datadoghq.atlassian.net/browse/CECO-2026
> Move fieldmanager

- bundle-community-operators/manifests/datadog-operator.clusterserviceversion.yaml
- bundle/manifests/datadog-operator.clusterserviceversion.yaml
- config/manager/kustomization.yaml
> Release v1.16.0

- pkg/controller/utils/datadog/metrics_forwarder.go
There is a known issue where sometimes the event create object retrieved does not have object metadata. We depend on this to send an operator metric for custom resources.
Adding a fallback to get the object kind if it is an empty string.
- Deploy the Datadog Operator.
- Apply a DatadogAgent manifest.
- Check the Operator logs that there are no errors with the metrics forwarder initialization.
- Make sure that the `datadog.operator.datadog_agent.custom_resource.count` is reporting as expected
- Delete the DatadogAgent instance, wait a few seconds and then re-apply the manifest. Make …
> [metrics forwarder] add fallback for getting object kind

- pkg/controller/utils/metadata/metadata_forwarder.go
- pkg/controller/utils/metadata/metadata_forwarder_test.go
Fixes issue where requestURL was malformed when using Site parameter on DDA spec.
> [metadata forwarder] fix requestURL, add test

- pkg/controller/utils/datadog/metrics_forwarder.go
Move a log line in the metrics forwarder; its current placement is not useful.
N/A
> [metrics forwarder] move log line

- bundle-community-operators/manifests/datadog-operator.clusterserviceversion.yaml
- bundle/manifests/datadog-operator.clusterserviceversion.yaml
- config/manager/kustomization.yaml
> release v1.17.0-rc.3

- bundle/manifests/datadog-operator.clusterserviceversion.yaml
- bundle/manifests/datadoghq.com_datadogagentinternals.yaml
- bundle/manifests/datadoghq.com_datadogagentprofiles.yaml
- bundle/manifests/datadoghq.com_datadogagents.yaml
- bundle/manifests/datadoghq.com_datadogmonitors.yaml
- bundle/manifests/datadoghq.com_datadogpodautoscalers.yaml
- config/manager/kustomization.yaml
Update bundles after 1.17.0 release
https://datadoghq.atlassian.net/browse/AGENTONB-2433
> Update bundle for v1.17.0

- bundle-community-operators/manifests/datadog-operator.clusterserviceversion.yaml
- bundle/manifests/datadog-operator.clusterserviceversion.yaml
- config/manager/kustomization.yaml
> Release v1.18.0-rc.3

- bundle-community-operators/manifests/datadog-operator.clusterserviceversion.yaml
- bundle/manifests/datadog-operator.clusterserviceversion.yaml
- config/manager/kustomization.yaml
> release v1.18.0-rc.4

- bundle/manifests/datadog-operator.clusterserviceversion.yaml
- bundle/manifests/datadoghq.com_datadogagentinternals.yaml
- bundle/manifests/datadoghq.com_datadogagentprofiles.yaml
- bundle/manifests/datadoghq.com_datadogagents.yaml
- bundle/manifests/datadoghq.com_datadogpodautoscalers.yaml
- config/manager/kustomization.yaml
1.18.0 bundle and kustomization in main
> v1.18.0 bundle

- README.md
- docs/agent_metadata_changes.md
Suggestions for metadata change docs
> Metadata change doc suggestions

- api/datadoghq/v1alpha2/datadogpodautoscaler_types.go
- api/datadoghq/v1alpha2/zz_generated.deepcopy.go
- config/crd/bases/v1/datadoghq.com_datadogpodautoscalers.yaml
- config/crd/bases/v1/datadoghq.com_datadogpodautoscalers_v1alpha2.json
Allow multiple local fallback objectives
> Switch DP fallback objective to list
